### ISSUE TITLE
Check sync of deleted time entries

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1011]
We saw some crashing that we couldn't explain. The only anomaly we found so far is that the respective database had unsynced deleted time entries.

This needs more investigation, but as of right now I'm not convinced that deleted time entries are synced correctly.

It appears like we inject the data source instead of the database into the `DeleteLocalTimeEntryState`, which when deleting, it will only set the delete flag, not actually delete the entity from the database.

I may or may not have understood this, but someone should definitely take a look and make sure deletion syncs correctly.

Cases to cover:

- time entry with negative ID is deleted locally (flag is set): when the syncing finds this, delete it in the database for good (instead of doing any api calls)
- time entry with non-negative ID is deleted locally: do the delete call to backend, on success delete in database, on fail... I do not know, might depend on error

**Comment by simonrozsival** [comment]
All the delete states of the sync should use the database - this is obviously a mistake. The data source classes are used only because of UI updates - the deleted entities are already hidden, so we don't have to update the UI there.

I will do functional tests to see if I can reproduce the inconsistency and then fix it.
