### ISSUE TITLE
Stopping time entry causes brief flicker in log

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1113]
This is especially visible if there are multiple days of data in the log. I think this may be related to how we remove a whole day from the list and reinsert it when time entries in the list are updated.

**Comment by willsb** [comment]
MvvmCross has a `UseAnimations` property. To whoever gets this issue, investigate whether enabling this property solves everything. If it doesn't, looking at MvvmCross' source code is a good starting point on how to make the TableView animated. 

Also, it might make sense to make the class that handles the grouping (which is also the one that calculates the total duration of time for a day) both mutable and bindable. This way we don't have to re-create the group, instead only recalculating its duration. I know, mutability is evil, but UI is, for better or worse, full of side-effects. If `UseAnimations` doesn't work out of the box, making the changes I mentioned might make it work.

**Comment by willsb** [comment]
I’ve tested my proposed fix wit `UseAnimations` yesterday and it doesn’t work because nested observable collections are not supported at all. We need to somehow subscribe to every ObservableCollection that gets added and react to each individual OnCollectionChanged event. 

The ideal fix for this would be to somehow calculate the diffs and then request the TableView/RecyclerView to animate the set of changes for us. The second part of the above comment remains truth: the collections need to be made mutable in order to allow animations to behave the way we expect them to behave.
