### ISSUE TITLE
Implement retry loop when pulling data

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1114]
We are kicking off several requests at once when pulling, which mostly works just fine, but there will always be moments when this causes problems, and we have to be able to handle those gracefully.

Specifically, we need to make sure that 429s (too many requests) and random server errors are handled correctly so that the requests are retried after a moment and the data is still pulled correctly.

I think we should somehow make it smart enough to handle the working requests in order, and retry those that failed, ideally while interacting with the existing retry loop. But I'm not quite sure how to do this best, while still pulling data in parallel as much as possible, and persisting data in the correct order for realm references to resolve correctly.

I don't think that pulling entity lists one by one is a good option, because pull sync will take a lot longer in that case.

The best idea I have right now is:

- kick off all requests, and keep them in a container object as right now
- try resolving the returned entities one by one, just like right now
- when an error is detected, go to the retry loop and pass the container object along, as well as a way to get back to the same state that just failed (we could change the retry loop to take a transition as parameter, that it will output once status is confirmed OK, and the required interval as elapsed)
- do the above for each entity, until all data has arrived

Potentially, we could decide to retry ALL failed requests instead of just one by one after exiting the retry loop, but that might just repeat the same issue over and over, and in most cases all or most of the requests will succeed anyways.

Other ideas or even entirely different views on this issue are very welcome.

**Comment by simonrozsival** [comment]
My (simple/naive) suggestion:

- pull everything (`FetchAllSinceState`)
- process entity types one by one (the same way we do right now)
    - when we detect, that the HTTP request failed for some reason, we either
        - rethrow (401, 410, 418)
        - enter retry loop (429, server errors)
        - is there a third option?
     - if HTTP worked well, process as usual and continue
- when entering the retry loop (same code as in the push sync), wait until the server is reachable again (resolves 5xx and 429) or fail after some time (1 minute)
     - if the server is reachable again, start the whole process from the start (`FetchAllSinceState`)

The reasoning why starting from the start:
- a lot might change in a different client in the meantime (retry loop might have taken a long time, but a different client (using different version of the API maybe?) might change the workspace, projects, ... which might be used by some entities and will fail the `BatchUpdate` if we skip pulling the entity types which synced OK previously, so we should pull all entities' types
- we make 7 concurrent HTTP calls, that should not cause 429 on its own if we don't repeat pull sync several times in a row and each of the HTTP calls is processed quickly (e.g., all return empty arrays). We could add some random delay to each of the requests, to prevent this, but I would say YAGNI applies here

As I described above, I don't think we should repeat only some HTTP requests, if the others were processed as expected.

Another case for repeating the pull sync, which we don't do now, might be that `BatchUpdate` failed in some case. We don't catch any exceptions in the `BasePersistState` and it probably won't even happen in the history of the universe - user would have to create e.g. a new project and a time entry for this project in some other client while we pull the data and specifically he/she would do it in such way, that we receive the time entry, but not the project, so we fail to fetch dependencies in `BatchUpdate`, which will throw and will cause the whole sync process to fail and emit `Failed` state in the `ProgressObservable`, which will be shown to the user. No invalid data will be written to the database since the transaction failed and wasn't committed, User will fix this by forcing full sync again, this time it will most likely work.

**Comment by amulware** [comment]
> a lot might change
Not really if we have a limit of one minute, but this (rare) case could indeed lead into an infinite retry of pulling TEs if a tag is missing.

I think I'm ok with your approach, but with one question: Are we currently updating the since parameters after each batch-persist? Or only at the end of the process?

I think this should be done after each persist to make sure we don't keep refetching lots of data that we already have.

**Comment by simonrozsival** [comment]
We are saving the since param after each entity type is processed successfully,

**Comment by amulware** [comment]
Then I say go ahead with your approach!
