### ISSUE TITLE
Organise views/VCs/etc. by screen

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1225]
I.e. have one folder/namespace for everything belonging with the calendar, one for everything belonging with the main view, one for everything related to time entry editing, etc. as it makes sense.

The opinions of people who actually write code are welcome, but I think organising it this way makes it much easier to find what you are looking for, and to have access to several related pieces of code.

**Comment by willsb** [comment]
Since files are scattered throughout projects there isn't much value added to refactoring *everything* into modules. 

Folders that have too many files, however, can benefit from more subdivisions, so I say we keep the current hierarchy and split things where needed, like we are already doing with [iOS Views](https://github.com/toggl/mobileapp/tree/develop/Toggl.Daneel/Views)

**Comment by amulware** [comment]
Do others agree? @simonrozsival @arturs105 @kornelijepetak?

**Comment by simonrozsival** [comment]
Organizing the views in some way sounds good, especially the VCs' folder contains a lot of files, so I agree with what @willsb says.

**Comment by arturs105** [comment]
Although I agree that organising stuff better would be useful, i don't think we can group view controllers by screen, since most of the VCs would either remain in the ViewControllers folder, or most subfolders would have only 3 files (.cs, .designer.cs, .xib). We could try to group selection view controllers together (`SelectProjectViewController`, `SelectTagsViewController` etc.), and edit view controllers, though i don't know how i feel about this.

**Comment by willsb** [comment]
Seems like there isn't much to gain from this change. Guess we are very tidy already 🤷‍♂️

**Comment by amulware** [comment]
Please make appropriate changes, or close this.

**Comment by simonrozsival** [comment]
IMO we should close this for now.

**Comment by willsb** [comment]
Closing for great justice
