### ISSUE TITLE
Forgot your password flow

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1267]
- [x] When user taps 'Forgot your password?' ask him to enter email to reset the password or use already entered email.
- [x] Display 'We just sent you an email. Please follow the link in the email to reset your password.' if resetting password succeeded and let a user enter his new password.
- [x] Use error and success messages from #831 to indicate different error and success states.

### Forgot password
![forgot your password](https://user-images.githubusercontent.com/5064445/34812945-a457de4e-f6b0-11e7-9a7c-a20d89307908.png)

Zeplin: https://zpl.io/am1wJme

### Success
![forgot your password ok](https://user-images.githubusercontent.com/5064445/34814319-e30800a6-f6b5-11e7-846b-28946f6c392d.png)

Zeplin: https://zpl.io/VkYzNOq

### Error
![forgot your password error](https://user-images.githubusercontent.com/5064445/34814360-04d708b2-f6b6-11e7-8bbc-e71f5ebfae74.png)

Zeplin: https://zpl.io/2yJEX1K

**Comment by kornelijepetak** [comment]
@pe0ny I have realized that this is part of a view that is different across platforms.
The difference is that on iOS, both labels (`Login with google`, `Forgot your password?`) are visible both during entering email and password.

On Droid, `Login with google` is shown only on Email phase, and `forgot your password?` only on password page.

Is there any specific reason why this is different on iOS/Android?

Things would be much easier if the whole flow (what is visible in what state, but not necessarily the position of elements) would be consistent across platforms. Currently we need to hack the view model to achieve this and nobody likes this.

In discussion with @amulware, @willsb and @apocalypticfish we reached a conclusion that 
* users expect the `Forgot your password` from the get-go, otherwise they might not even be aware that this feature is available.
* users (usually) expect to be asked for email after clicking on `Forgot your password` so maybe we should reset the email field in that case.

The UI issue related to all that is that we are using FAB on droid which is in the lower right corner, which would clash with `Forgot your password?` label if it was there. So the solution is to rearrange the elements somewhat (maybe put Forgot your password above google login, dunno?). On iOS it's simpler cause the `Next` button is on top.

**Comment by pe0ny** [comment]
All the points above make sense, so I would go with go with the solution where "Forgot your password" option is available below the email input field:

![log in - step1](https://user-images.githubusercontent.com/5064445/37595743-9a11128c-2b82-11e8-9caa-1f16ae66a27e.png)

Zeplin: https://zpl.io/aXKpLmx

> users (usually) expect to be asked for email after clicking on Forgot your password so maybe we should reset the email field in that case.

Why should reset it? If user has typed in the email already and then taps "Forgot password" I would keep the email because it's highly likely that he/she wants to reset pw with this email.

**Comment by pe0ny** [comment]
Also, please replace the Google sign in button.

**Comment by amulware** [comment]
I think 'Forgot password?' sounds really awkward. Can we maybe it 'Forgot your password?'

**Comment by pe0ny** [comment]
Sure, let's change it to "Forgot your password?"

**Comment by ApocalypticFish** [comment]
https://english.stackexchange.com/questions/670/is-it-correct-to-use-forgot-password-or-forgotten-password

**Comment by ApocalypticFish** [comment]
It might just be me but I think we should keep even simple language like this the same across all apps 
![image](https://user-images.githubusercontent.com/18132080/37646168-326b01b8-2c29-11e8-8d45-9987629cd402.png)

**Comment by kornelijepetak** [comment]
@pe0ny has spoken. It's `Forgot your password?`.
