### ISSUE TITLE
Make dragging whole interval in wheel behave correctly

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1361]
'Correctly' meaning: the way we arbitrarily define it as follows:

- [x] Dragging the interval changes both start and stop time
- [x] Dragging the interval NEVER changes the duration (not even the seconds)
- [x] Dragging the interval causes the start-time to round to full minutes
- [x] To keep duration the same, the end time has to be modified appropriately when the start time changes

**Comment by simonrozsival** [comment]
I am not really sure how to implement this. I came to one conclusion: we shouldn't have internal state (second-precision values) and display values rounded to minutes. That won't work well for us. Instead, we should only update the values when the handles are dragged and only update them if they will snap to a rounded value.

Also dragging the whole interval should work in a different way than it is right now: it should, in fact, move just the start value and snap it to minutes and then calculate the end value by adding the duration to start and not by adding the same spans to both start and end values (fails because of rounding).

I will think this through and rewrite this tomorrow and hopefully, it works then.

**Comment by amulware** [comment]
That sounds fine to me.

**Comment by simonrozsival** [comment]
I will try to implement this now and if it works, then we're done here, if not, I would like to consult other options.

**Comment by simonrozsival** [comment]
I fixed the behavior, now I think it is perfect.
