### ISSUE TITLE
[onboarding] phase 3: project/tag adding in TE creation view

### ISSUE THREAD

**Issue by fonorobert** [toggl/mobileapp#1521]
Phase 3 of onboarding flow.
Phase 1: #1519 
Phase 2: #1520 
Phase 4: #1522 

Add: 
- [ ] highlight to @ and # symbols in TE create view

# Design
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5a8414e312ae889d71a0f88a

![screenshot from 2018-02-14 14-49-39](https://user-images.githubusercontent.com/6963710/36208696-fa61bcb6-1199-11e8-9c61-61c0560f79a4.png)

“@” and “#” symbols highlighted in project/tag fields in TE create view.

**Show:**
- If user hasn’t added a project or tag via TE creation view yet
and
- If user has at least one project or tag available to assign

**Comment by pe0ny** [comment]
@fonorobert Just to confirm, we wanted to show this to existing users as well, right?
So should we move the first condition then "If user completed phase 2" and say conditions 2 and 3 should be both met?

**Comment by fonorobert** [comment]
@pe0ny yep yep, correct again :)

**Comment by amulware** [comment]
After talking about this with @apocalypticfish, and also from @willsb's reports after recent customer meetings, I have the following thoughts:

- some users don't seem to realise at all that there are buttons below the text entry (project/tag/time/whatever) and that those are like... super useful (not even counting the @# shortcuts)
- I think we should teach them about those first
- Especially, because tapping those will enter a @/# anyways, so they'll learn that those can be used probably automatically (and if not, whatever)
- highlighting those empty-state-buttons that look hardly even tappable as it is won't teach them about the other functions below, and even worse, as soon as the user enters ANYTHING, they probably disappear because the autocomplete list pops up

Therefore, I propose that we change this to instead show a popup bubble thing with a little pointer to the project/tag buttons right about the keyboard with something like "Add a project to your time entry" or "Categorize your time with projects" (the latter also hinting at the benefit to the user).

**Comment by fonorobert** [comment]
originally we were going back and forth between highlighting the inputs or the buttons and ended up on the highlights partly to avoid another "looky here" type of tooltip. that said, i see the point you're making and i'm ok with switching this step to a tooltip for the buttons instead, maybe that does make more sense. interested to hear what others think as well though :)

**Comment by amulware** [comment]
Note to devs: we agreed internally that the design here will change.

**Comment by ApocalypticFish** [comment]
We've had a few users come back and complain about how once they've created an entry and entered a description then the next step is pressing the green tick and then they have to go back into the entry to change it. So those buttons aren't apparent for a few users. Not sure on what's the best way to address this though.

**Comment by amulware** [comment]
@ApocalypticFish the current updated plan is to be more in their face and have a bubble pointing at those buttons above the keyboard. mostly to make sure they are aware those are there. I HOPE (we will measure) that's enough for users to get it.

**Comment by ApocalypticFish** [comment]
Anything to make them more obvious in some way has to be a good thing I think. Even like a red dot in the corner of them until someone clicks on them for the first time in the same way that new apps would do on the iPhone

**Comment by lizaPlotnikova** [comment]
Design update: 

<img width="339" alt="screen shot 2018-03-21 at 5 06 38 pm" src="https://user-images.githubusercontent.com/24964497/37738841-a13cf352-2d2e-11e8-9a8c-ff0a863b2e07.png">

https://zpl.io/bJNLRQ6

I think same conditions for showing still apply.
