### ISSUE TITLE
Crash in PrimeRadiant.EntityNotFound

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#1525]
`Toggl.PrimeRadiant.Exceptions.EntityNotFoundException: Entity not found in database`

[:blue_book: example stack trace](https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/aab2a860434bd82d099a74c9dc10336f78da8d4d)

The stack trace is not that helpful on this one. However, this appears in 1.3.1 *and* 1.3.2 (albeit in smaller numbers). My wild guess is that there are some invalid entries that got stuck or some sync issues that happened between updates or something. I see [some other](https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/56e28da18f5b41487e58ae0c5497d18905e87877?appVersion=1.3&period=last7Days) very similar crashes that are explicitely related to continuing suggestions. I guess if the suggestion is based on a time entry that had since been deleted (on another client), this would cause such a mess. 

We should definitely not crash the app in this situation, however, but probably inform the user that the suggestion is stale, redo the sync or simply remove the suggestion. @amulware @pe0ny What should be the follow up for stale suggestions?

I will monitor this crash in 1.3.2 and see if there are any improvements. Support will advise users to update and (in worse case scenario) reinstall the app. For now this would be enough I think.

**Comment by amulware** [comment]
About suggestions: they should not depend on time entries in any way. They should have all data needed to start a new entry and a fetch should not be necessary, so it should never crash.

**Comment by amulware** [comment]
There also is an issue to make suggestions reload on app wake, so they will update themselves sufficiently in the future.

**Comment by kornelijepetak** [comment]
You are right, there are no hard references to TEs. There are, however ProjectId, TaskId and WorkspaceId that could have gone away in the meantime. What will backend return for that, that I don't know by heart.

**Comment by amulware** [comment]
Ah, I see. We should definitely see about this.

We have to make sure:
- that starting suggestions works with projects created in the app, and takes local ids into account correctly
- that suggestions get refreshed after every pull sync, which could (in the future) delete projects

I'm not sure exactly how there could be an issue here right now, unless it's somehow not taking into account local ids, but even then, since the suggestions never update, you would have to go through quite complicated steps, creating a project in offline mode, making sure there are several entries so it shows up as suggestion, restarting the app to update suggestions, and then syncing and using the suggestion to make it break.

Maybe there is something simpler going on that I can't think of right now. (I hope there is)

**Comment by kornelijepetak** [comment]
Like I said, it's hard to determine from the stack trace what's really going on. But this `EntityNotFound` exception is nothing unheard of.

**Comment by simonrozsival** [comment]
The problem with suggestions is described in #1474 and the `EntityNotFoundException` in fact means that there are two running TEs.

Refreshing suggestions after pull sync might certainly help in some cases 👍

**Comment by amulware** [comment]
Closing as out-of-date.
