### ISSUE TITLE
Start view: Do not show billable field for free WS

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1576]
Do not show billable field to users who are under the free WS.

**Comment by kornelijepetak** [comment]
Hey, @willsb 

I have tried to fix this, but there's a strange problem, related to visibility.
You had already put in place a binding that should have solved this, but it did not work.

When I changed it like this, it worked:
![image](https://user-images.githubusercontent.com/7033216/37601057-63d0f9f6-2b89-11e8-925d-b0d9f816439d.png)

However, this works with `hide = true` which means that visibility will be set to **hidden** instead of **gone**. If I remove `true` so that visibility becomes `gone`, this is what happens (when that icon is no longer layouted):

![image](https://user-images.githubusercontent.com/7033216/37600957-1cd793e8-2b89-11e8-93f3-b903a4641ba6.png)

and I was unable to solve this by various layouting.

Can you take a look at this issue?

**Comment by pe0ny** [comment]
Just in case, before you start fixing this, check out the new Start view UI #1743

**Comment by kornelijepetak** [comment]
I am aware of the new UI.
This problem will probably remain all the same.

However, I believe that when #1743 is being done, it will implicitly solve this issue.
So I will leave this issue open until #1743 is resolved.

**Comment by willsb** [comment]
`android:layout_alignWithParentIfMissing="true"`
