### ISSUE TITLE
Allow continue-swipe on suggestions

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1684]
That felt natural to me, but it doesn't work. Needs to be shot down, or designed by @pe0ny

**Comment by simonrozsival** [comment]
I would personally expect it to be "dismissable" by swiping - so that there is more room for the log if those suggestions aren't accurate.

**Comment by amulware** [comment]
DIsmiss by swiping in the delete direction? :D

**Comment by willsb** [comment]
Continue by swiping a card doesn't make much sense, but dismissing does. I don't know how dismissing can be implemented trivially, though, without persisting the suggestions

**Comment by amulware** [comment]
Well, the dismiss could be only temporary, until they get repopulated. But let's not worry about that right now. Suggestions will get a major update in the future.

**Comment by pe0ny** [comment]
Imo it doesn't make sense to allow users to use the swipe gesture to continue suggestions because for card elements it seems rather counterintuitive. Like mentioned above, I would expect swipe to dismiss/remove a card. Which this could to - idea for the future: User can dismiss suggestions if these doesn't make sense and the app should take this into account when suggesting next time. 
Is it ok if i close this issue for now? @amulware  I'll make a note to myself and let's get back to this when we start rethinking/improving suggestions in general.

**Comment by amulware** [comment]
Closing.
