### ISSUE TITLE
Reports calendar shortcuts are not obviously scrolling

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1705]
I haven't checked other phones, but on an iPhone 8 I can hardly tell that I can scroll the shortcuts under the calendar, given how the last one is cut off.

<img width="487" alt="screen shot 2018-03-13 at 09 34 02" src="https://user-images.githubusercontent.com/3987892/37333864-471f6d6a-26a2-11e8-8740-79849288cf0d.png">

In fact I at first thought it was a smudge on my screen. 🙊

Maybe there is a way to make the shortcuts a bit wider so that the last one is always cut off in the text, not this close to the border.

Just an idea for @pe0ny

**Comment by kornelijepetak** [comment]
I propose a thin horizontal scrollbar, like in two shades of gray... I also didn't notice this until you've just spoken about it.

**Comment by amulware** [comment]
On iOS, scrollbars canonically fade out though when not scrolling (not sure about Android). But it's up to @pe0ny.

**Comment by pe0ny** [comment]
I agree with Paul that at the moment it looks more like a glitch. I'm not a fan of the scrolling bars, so I would rather change the width of the shortcuts. 

At the moment each shortcut has its own size based on the text. Let's make all the shortcuts width 96pt, so it looks nice on all screens: SE, 8, 8plus and X. Padding between shortcuts should be 12pt instead of 10pt.

<img width="900" alt="screen shot 2018-03-13 at 17 12 32" src="https://user-images.githubusercontent.com/5064445/37372704-bf1f7154-26e1-11e8-8fb5-bb3c802af600.png">

Zeplin: https://zpl.io/anryEXr
