### ISSUE TITLE
Forgot Password showing failed when successfully reset

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#1726]
When attempting to reset the password for a valid email on 1.4.1 it displays that the reset has failed but it has sent the reset and on a second attempt it displays that it needs five minutes before password reset attempts.

**Comment by amulware** [comment]
The relevant API test checks out.

**Comment by simonrozsival** [comment]
I cannot reproduce this - that must be something backend-related, because the message we display is exactly what backend gives us. Maybe what you can describe could happen if there was some networking problem - backend could send the email, but we didn't get a response from the server, so we displayed an error.

**Comment by amulware** [comment]
Unless there is more clarification or reproduction steps, feel free to close this tomorrow or so.

**Comment by simonrozsival** [comment]
@ApocalypticFish Please reopen this if you can still reproduce this issue and please add the steps to the description or in a comment.
