### ISSUE TITLE
Find and fix bottlenecks in the start time entry suggestions

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#1728]
A user complained of sluggishness when typing the description of a time entry 🙊 

We need to stress test the app by trying to create a time entry in a workspace with a bunch projects/clients/tasks and see how bad the situation is. 
This needs to be done in an actual device (preferably an iPhone 6/SE).

After that we need to measure performance and find possible points of improvement.

**Comment by amulware** [comment]
I have this issue on an iPhone 6s. I don't even have a lot of data, but typing just lags behind a little bit and it's not super pleasant.

**Comment by amulware** [comment]
I tried recording a video (posted internally), but it's hard to see it there since even the keyboard lags behind my typing. I noticed that this does not seem to be a problem in a test account with little data, but only in my real account with hundreds of time entries, all with nice descriptions and all that.

For testing, try putting a Delay(500) or so into the (realm) query that fetches the suggestions? The UI shouldn't freeze, no matter how long the query takes. If needed, we can always delay the query itself until the user stops typing too.

**Comment by sofokli1** [comment]
I am not having any luck with this so I am leaving this to someone else more familiar with observables and threading.

My finding are the following:
I think the issues is in the `Prepare` func line 264 of the StartTimeEntryViewModel.
I tried adding 2 ObserveOn calls as below
```csharp
querySubject.AsObservable()
                .StartWith(textFieldInfo)
                .ObserveOn(Scheduler.Default)
                .Select(QueryInfo.ParseFieldInfo)
                .Do(onParsedQuery)
                .SelectMany(autocompleteProvider.Query)
                .Merge(queryByTypeObservable)
                .ObserveOn(SynchronizationContext.Current)
                .Subscribe(onSuggestions)
                .DisposedBy(disposeBag);
```
This crashes with the error message

The problem is that autocompleteProvider.Query loads all the projects and tags for every typed character using some interactor. This constant loading and filtering seems to be an issue when having too many data.

Other approach that I can suggest here is to have some kind of delay before performing the query. the delay resets every time the user changes the text. if no changes after the delay passes we perform the query.

Alternatively it might make sense to have some more filters when fetching data. Instead of getAll we could fetch those that were used recently (like past 2 weeks) which is a reasonable assumption.

**Comment by khoi** [comment]
Adding `Delay` as @amulware suggested also causes the exception `Realm accessed from incorrect thread.` 
```
commit d18969b4115c3035835cafc15b8c940ccf8e8956
Author: khoi <khoiracle@gmail.com>
Date:   Mon Aug 20 16:14:35 2018 +0700

    --wip--

diff --git a/Toggl.Foundation/Autocomplete/AutocompleteProvider.cs b/Toggl.Foundation/Autocomplete/AutocompleteProvider.cs
index 280922c4..7c74a8b9 100644
--- a/Toggl.Foundation/Autocomplete/AutocompleteProvider.cs
+++ b/Toggl.Foundation/Autocomplete/AutocompleteProvider.cs
@@ -26,15 +26,15 @@ namespace Toggl.Foundation.Autocomplete
             switch (queryInfo.SuggestionType)
             {
                 case AutocompleteSuggestionType.Projects:
-                    return interactorFactory.GetProjectsAutocompleteSuggestions(wordsToQuery).Execute();
+                    return interactorFactory.GetProjectsAutocompleteSuggestions(wordsToQuery).Execute().Delay(TimeSpan.FromSeconds(2));
 
                 case AutocompleteSuggestionType.Tags:
-                    return interactorFactory.GetTagsAutocompleteSuggestions(wordsToQuery).Execute();
+                    return interactorFactory.GetTagsAutocompleteSuggestions(wordsToQuery).Execute().Delay(TimeSpan.FromSeconds(2));
             }
 
             return wordsToQuery.Count == 0
-                ? Observable.Return(QuerySymbolSuggestion.Suggestions)
-                : interactorFactory.GetTimeEntriesAutocompleteSuggestions(wordsToQuery).Execute();
+                ? Observable.Return(QuerySymbolSuggestion.Suggestions).Delay(TimeSpan.FromSeconds(2))
+                : interactorFactory.GetTimeEntriesAutocompleteSuggestions(wordsToQuery).Execute().Delay(TimeSpan.FromSeconds(2));
         }
     }
 }
```

**Comment by simonrozsival** [comment]
Today I made several observations:
- the whole querying happens on the UI thread
- even when I move everything to a background thread, selecting suggestions is VERY slow when the user has many time entries...
- ... because all of the searching happens in memory, not in Realm (and there is probably not a way to do it in Realm)
    - we look for time entries, which contain all of the queried words as a substring of the description, or the substring of project name, or the substring of task name, or the substring of client's name - this means that we transitively access the project, task, client - this cannot be done in Realm, this has to be done in memory

_The solution_ to this is:
- have extra string properties `ProjectName`, `TaskName`, `ClientName` in `RealmTimeEntry` (similarly for projects) which would be used for searching
- we would need to store all of these _lowercased_ and we would also have to store a copy of `Description` - `LowercaseDescription`, because we use a method `ContainsIgnoringCase("substr")`, which is not supported by Realm, but simple `Contains` IS supported

Also we should probably not show "all of the results" in the table view, but AT MOST 15 of them or so. 

We should probably also limit the length of the query which we search for - we should filter only with 3 letter words or longer (ignore all of the `a`, `an`, `at`, `on`, `in`, ... which is contained in every other time entry).

By these few simple changes we can move everything away from the managed .NET runtime and let Realm do the heavy lifting and achieve 🚀 speed.

Any ideas? Any tips? Is there something I am missing? Other ideas?! :)

**Comment by amulware** [comment]
Postponing discussion to 🇪🇪/ 🇮🇹  :)

**Comment by amulware** [comment]
Something to consider: If the previous search string is a substring of the new one, the new search result is a subset of the previous one. If we don't have queries running concurrently, we might be able to use that to our advantage (speaking of - do we run multiple queries at once when typing fast?).

**Comment by heytherewill** [comment]
The discussion here is superseded by [this](https://github.com/orgs/toggl/teams/mobile/discussions/11) 

Also, I'm closing this because since #3700 the queries sluggishness should no longer be perceivable
