### ISSUE TITLE
Track project and tag addition in TE creation view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1777]
There are three different ways to open the project/tag list:
- typing @/#
- using the button right above the keyboard
- using the button that shows below the text field, that has to share space with the auto completion

Let's have two events, with a property that represents the three options above each.

I think it's fine to send when the user opens the project/tag list, we don't have to worry about whether they select stuff for now.

**Comment by Odrakir** [comment]
Should we track this for both TE creation and TE editing? Should we differentiate those?

**Comment by pe0ny** [comment]
We already have an issue for the edit view as well #1778 and yep, we should differentiate those.

**Comment by amulware** [comment]
Yeah, please check the referenced issues. There is some overlap, and we should probably do this in some smart way. :D

**Comment by Odrakir** [comment]
But you do want different events for edit/create and not the same event with different parameters, right?

**Comment by amulware** [comment]
yeah, we want at least two different kinds of events. Maybe even more. I haven't thought much about what makes the most sense.

**Comment by simonrozsival** [comment]
We would have to have specific commands for tapping the button and typing the symbols - then from these commands we would call some common logic. It would make the code a bit uglier, but it would do the job...

**Comment by Odrakir** [comment]
Ok, this is almost done, but still, every way of showing project/tag suggestions end up adding "@" or "#" to the text field, so in order to not track text field input when indeed it was a button tap I end up having to set a property in the ViewModel only to track this.

It works but it's ugly and, in my opinion, it has too much logic for something like this. Is it good enough if every method tracks text change but also the buttons track each event separately?

**Comment by amulware** [comment]
So four events, instead of two then?

One each when the character is added to the text, and one each that records just the non-keyboard button presses, which is a subset of the first thing?

If it makes that much of a difference, sure, this will do.
