### ISSUE TITLE
Edit view: Done/Save buttons don't behave as they should

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1844]
Steps to reproduce:
1. Open the edit view
2. Tap 'Done'
3. 'Save' appears 
4. Tap 'Save' - edit view closes

When user is not editing the description, then 'Done' shouldn't be visible at all. Only 'Save' which saves and closes the edit view.

**Comment by kornelijepetak** [comment]
When you open the Edit View, the description should have focus, hence the `Done` label instead of save. 

This might be related to #1845 and not reproducible on other phones. I assume this happens for the same reasons. @willsb can you confirm the correct behaviour on your phone? My phone and emulator works correctly.

However, the question remains if description being focused on start is a desired behaviour? @pe0ny?

**Comment by willsb** [comment]
On my phone the text field is focused, but the soft input does not appear

**Comment by pe0ny** [comment]
In the edit view nothing shouldn't be focused.
