### ISSUE TITLE
Toolbar is missing reports icon

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1852]
Toolbar is missing Reports icon/button when user navigates to 
a) reports view 
or b) to settings view

Reports icon should be visible at all times.

**Update:**
https://github.com/toggl/mobileapp/issues/1852#issuecomment-378911703

**Comment by kornelijepetak** [comment]
@pe0ny Guidance needed 👇 

I remember that there was a discussion about the _3 main screens_ - timer, reports, settings...
But we all agreed that the timer is "_mainer_" among them and that it makes much more sense for the `back` button in reports and settnings to return to `timer` screen instead of closing the app.
I see now that we did implement things in that manner. I suppose that this is also the reason why there is no reports icon in settings screen and settings icon in reports screen.

So I need quick answers to the following:

1) Do you still want the back button to close the app in all three pages (which seems really counter-intuitive from settings screen, I might say).

2) Do you still want all three buttons to be visible on all three _main_ screens? (If `back` button mentioned in the first point always lead to the `timer` screen, then I guess having only the timer and the current screen makes more sense, IMO)

3) How should `back` button work - go to `Timer screen` or go to the previous active screen?

**Comment by pe0ny** [comment]
While testing the app I agree with you 100% that the system back button should return to the previous page instead of closing the app.

1. No.
2. Yes, it makes sense to show all three buttons there and highlight the active one. So, in that case, I don't have to back to the timer page if I wanna go from reports to settings.
3. Currently, it's implemented the way it always goes back to Timer screen, right? Let's keep it like this for now.

**Comment by pe0ny** [comment]
In the future, I would prefer the back button navigate back through the history until closing the app though.

**Comment by kornelijepetak** [comment]
Do you also want the back button to retrace the exact history even in this situation:

User scenario:
`app starts on timer - reports - settings - reports - settings`

Multiple presses of system back button result in one of the following screens flows:
* `reports - settings - reports - timer - close`
* `reports - timer - close` (meaning that it never returns to the screen from which back button was started being pressed).

**Comment by pe0ny** [comment]
@kornelijepetak let's do with the second one. it makes more sense to me.

**Comment by kornelijepetak** [comment]
This issue is put on hold after the beta is out.

**Comment by kornelijepetak** [comment]
In the end, it was decided that we do it this way: 

[ ] Remove timer icon from Timer screen (only reports and settings should be visible)
[ ] Remove all toolbar icons from Settings view
[ ] Remove all toolbar icons from Reports view
[ ] Make sure that system back button from Settings and Reports views leads to Timer view.
