### ISSUE TITLE
Edit view metrics

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1916]
I'd like to record the following actions:

- user taps description
- user taps project/task
- user taps tags
- user taps start
- user taps end
- user taps duration
- user taps start date
- user taps billable

I'm not sure right now if these should all be different events or maybe they should be a single `EditViewAction` event with an `Action` property that has one of the above. The latter is probably a bit more future proof and easier to handle on app center/whatever

Alternatively, we could have an event for when the edit view is closed with similar properties as for the time view event: #1915

**Comment by kornelijepetak** [comment]
@amulware regarding the above mentioned overlap, did you want to remove anything?
Because while there is some intersection, I don't think the events are the same, mostly because one has different parameters...
Can we unify this somehow and decide on what the final set of events (and their parameters) should be?

**Comment by amulware** [comment]
Sure, please feel free to do so, just write down what changes you make for documentation :)
