### ISSUE TITLE
Start view metrics

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1918]
Things I care about:

- user tapped project button
- user tapped tag button
- user tapped billable button
- user tapped calendar button
- user tapped time view button
- user tapped duration field

- user opened project selection by typing @
- user opened tag selection by typing #
- user tapped the project button in the empty state
- user tapped the tag button in the project state

- user auto completed from a suggestion

There is some overlap in #1777

Similar to #1916 I'm not sure what the best form for this event/these events is.

**Comment by kornelijepetak** [comment]
@amulware can you please explain what this means:
* [ ] user tapped the project button in the empty state
* [ ] user tapped the tag button in the project state

In addition, since these are currently rather difficult to separate the way we are doing the query and also in light of upcoming changes to the TextFieldInfo, I will move these to another issue that should be fixed when that is done:
* [ ] user opened project selection by typing @
* [ ] user opened tag selection by typing #

**Comment by amulware** [comment]
The two points in question are referring to these buttons:

![4bb5ae97-9b43-4959-aa94-50df8513d0e1](https://user-images.githubusercontent.com/3987892/41335978-b07ffe0e-6ee2-11e8-967a-fe92788544ab.JPG)

**Comment by amulware** [comment]
I believe that we are already tracking the three different ways to open project/tag selection though? I remember @Odrakir working on that 🤔

**Comment by kornelijepetak** [comment]
This was done by #2448 and the rest is in #2447.

Clean up is required in the form of #2486
