### ISSUE TITLE
Investigate Facebook SDK

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1923]
Marketing would like to integrate with the Facebook SDK which should allow them to see some direct data on how many new users came to the app from facebook ads.

I figure the way that works would be using some IP matching by facebook or something.

I'm worried though that by integrating with Facebook we don't only increase the app size, but cause it to call home about all sorts of other things we don't want them to know about.

Someone needs to investigate what exactly we can expect from using the Facebook SDK:

- How difficult is it to use in Xamarin?
- Will it indeed be able to tell us how many users came to the app from our Ads? (Specifics?)
- What more will it do whether we want it to or not?
- Estimate in increase in app size? Compile time?

Please post results below.

**Comment by pe0ny** [comment]
The main reason why we need this is to find out how many people who clicked on the Ad, actually ended up installing the app. That's the main thing the SDK should provide us with. Moreover, I'm interested in if it is possible to get the number of how many people signed up or logged in out of those who installed the app after clicking the Ad?

**Comment by amulware** [comment]
Clarification: There is no way to measure installs. Only users who open the app can be tracked.

Otherwise, carry one.

**Comment by djalex15** [comment]
"it's an edge case and we can say that open equals install" <- I think we can, but honestly, the main thing I'd like to test out with SDK is the **ad optimization** that FB does (and any spikes in number of impressions or it being shown to some target groups that we are currently maybe locked out of), since currently, we can't run those App Install ads (only regular "Traffic increase" ads), and ofc, any data they can provide through that ad.

**Comment by amulware** [comment]
Thank you for the thorough writeup. Follow up issue will be opened soon.
