### ISSUE TITLE
Step 2 and Step 4 displaying simultaneously

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2029]
Fresh install, new signup.
Proceeded through onboarding to step 2, didn’t click on entry to edit and just created more entries.
Step 2 remained on screen and step 4 was also displayed. 
Not sure if this is functioning as intended.
![41cf54b1-44ed-4f54-bacc-1fa11bff6ce6](https://user-images.githubusercontent.com/18132080/39614103-32baea60-4fac-11e8-95f0-1b86fcb6857d.png)
![351c9a4c-19dc-4591-8a25-ef79db9c5300](https://user-images.githubusercontent.com/18132080/39614104-32f6c29c-4fac-11e8-8c6e-766a0744e0be.png)

**Comment by simonrozsival** [comment]
Technically, you are right. I don't think that it is a real problem - most people will just tap on those tooltips to dismiss them IMO - we would have to track it somehow to have real world numbers.

Or we can change the condition of the Phase 4 steps:
a) we can add a condition "user tapped on the time entry" which will implicitly mean that these two won't be displayed simultaneously
b) we can explicitly add a "previous step is hidden" condition and pass the editing step as the previous step

Would that be better?

**Comment by amulware** [comment]
It's not ideal, but it's also not terribly important to fix.

What we could maybe do is make it so that only one onboarding thing can be active at any one time? Unless that again might have unintended consequences (like different onboarding popups on different screens blocking each other, while the shouldn't).
