### ISSUE TITLE
Investigate Firebase A/B testing framework

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2056]
#1923 provided us with a lot of information about the Facebook API.

Let's do this again, but this time about Firebase A/B testing.

We could develop our own solution, but that takes time and is complicated, so let's see what Firebase provides us with first.

For reference as to what we want to use this for, see: #1972

Our idea is to test the different scenarios we have on maybe 20% of total users, and once we know which works best, release that for the rest (and then in a future update we just hardcode that path).

- Can Firebase do all that?
- How much effort does this require from us?
- Anything else we need to consider?

**Comment by sofokli1** [comment]
# A/B Testing with firebase

## On firebase web

### Setup an experiment
1. Set name, description, percentage of users that will be part of the experiment (more options a re available per country etc.)
2. Set variants and parameters that are needed
Ex: in the case of #1972 (which in my opinion it is not clear what we want to test, but that is an other story) we can have 4 variants + 1 (the control group) and for each variant give 2 parameters (sequence of days and number of entries)
3. Set the way we are going to measure the our goal. For this we can use normal custom analytics events that we log in fire base.

## In out code
(If we want to test different copy for push notifications we should use CouldMessaging, but for everything else (like what we will want to do) there is Remote Config)

With remote config we will get the parameters that we set in the step 2 above. From a code prospective we can have an interactor that takes these 2 parameters and replies with a bool to show or not the UI.

1. Add Firebase to our app (if not already there)
2. Configure Remote Config in our app
3. Set in-app default parameter values
4. Fetch and activate values from the server

Detailed technical instruction for the above points can be found https://components.xamarin.com/gettingstarted/firebaseiosremoteconfig

## Data from firebase

Firebase sends data as json so in the end we just get dictionaries with string keys.

## Debugging

Easy to test and debug during development. The experiment can be enabled with a specific variant for a specific app install and can be changed from variant to variant easily on the web interface.

## After the experiment

Depending on how conclusive the results are, we can easily stop the experiment and select which variant we want to use for all users.

## Interpreting the results

First the experiment should run for at least 2 weeks to get enough data so that we know it is not just chance. What events we use to decide and what we want to test is very important and tricky. It is ok and normal for results to be inconclusive (depending on what we are testing, like changing a color). More info about this there is this 15 min video from firebase https://www.youtube.com/watch?v=UMz9dSPGzoo

**Comment by amulware** [comment]
👌
