### ISSUE TITLE
Decide what to do with premium attributes

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#207]
Some properties are accessible only to pro users (`Project.Billable`) and must not be sent over to api, but our current serialisation model does not support that.

One possible solution would be a `IgnoreIfNotPremiumAttribute` similarly as `IgnoreWhenPostingAttribute`.

Any other solutions?

**Comment by amulware** [comment]
Much more concerning than just 'premium' to me is that we have a number of different features that may be on or off per workspace, and we might have to serialise based on the current permutation of features, so we need to find some way of opt-in or opt-out of serialisation on a per-property base.

Something like:

`[RequiresFeature(42)]`

maybe?

**Comment by willsb** [comment]
```csharp
using static SomeFlagsEnum;

[RequiresFeature(Option1 | .Option3)]
```

I think that might be enough :)

**Comment by amulware** [comment]
I don't want to use flags for this, since I'd rather map feature ids straight to an enum (I agree to use an enum though), not to mention there might be way more than 32 or even 64 features in the (far) future.

Also, I don't think there is any overlap between features, so that's not a case that we have to handle.

Otherwise, let's do it that way then.

We only have to see how to hand down the features, probably just as some sort of collection of enum values (I can see how flag would be nice here, but I really dont wanna have to worry about translating between values if we don't have to).

**Comment by amulware** [comment]
Ironically.. there is only a single feature that influences serialization right now, which is the pro/premium one... Not sure if it is worth it thinking too far ahead.

Still, the enum will still be nice to have, since it influences actually available features in the UI.
