### ISSUE TITLE
Investigate what happens with deleted projects and tags

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2073]
Similar to #1905, but for projects and tags.

Do time entries automatically update when a project and/or tag is deleted? Do they at least not return ids of deleted projects/tags?

**Comment by simonrozsival** [comment]
# Tags

- the entities fetched from the server contain the `server_deleted_at` attribute only when the `?since=` parameter is specified, otherwise the tags are just skipped
- the ID of a tag is removed from the time entries when it is deleted
- the `at` of the time entry **does not change**

# Projects
- the ID is removed from the time entries, when a project is deleted
- the `at` of the time entry **changes**

**Comment by simonrozsival** [comment]
Is it enough like this?

**Comment by amulware** [comment]
Looks good!
