### ISSUE TITLE
Bottom card freezes after deleting a time entry from the edit view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2097]
Steps to reproduce:
1) Start a new entry and tap "Save"
2) Open the edit view of the running entry
3) Tap "Delete this entry" and confirm

The card at the bottom of the screen remains there but is not responsive anymore. Other parts of the app work fine though. Restart helps.

**Comment by willsb** [comment]
The problem here is that the observable responsible for the currently running time entry only considers hard deletion (which happens during sync) and duration updates (which happens when you stop a TE); It doesn't consider soft deletes at all.

I'll put this issue on hold until #1993 is closed, for it'll making fix this issue much easier
