### ISSUE TITLE
Start time on running time entry and editing existing time entry is displayed as UTC

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2127]
When editing the Start time, by clicking on the Start time in the wheel menu, of a running or stopped time entry.

The time on the wheel is displayed as UTC.

![image](https://user-images.githubusercontent.com/18132080/39987900-26b2a0e0-57a5-11e8-8334-e385bd27e7a0.png)

**Comment by amulware** [comment]
Please double check all other times in this VM as well. Using time zones incorrectly is very bad since it makes the app potentially unusable for most of our users.

**Comment by simonrozsival** [comment]
Which version is this, 1.5?

**Comment by simonrozsival** [comment]
The time is always displayed in the timezone which matches the timezone of the device at the time when the app was launched.

If you launch the app in Europe and then travel to say Australia and you change the timezone (or it changes automatically), then the app will still think the time should be European until it is restarted. I suppose that is why you noticed it... or can you reproduce it with different steps?

I will look into how the app can notice that the timezone changed.

**Comment by simonrozsival** [comment]
I found several questions related to this problem, e.g.: https://stackoverflow.com/questions/30352089/xamarin-react-to-timezone-change, but I wasn't successful in fixing the problem using the suggested solutions.

**Comment by arturs105** [comment]
So i've done some investigations and experiments and i may have a possible (hackish) solution, which is based on these observations:
1. When the start time is pressed, the date picker shows the wrong time
2. **When the end time is pressed, the date picker shows the correct time**
3. When the start time is pressed **after pressing end time** it shows the correct time.

So then (based on 3) i tried initialising the date picker to the end time at the end of `ViewDidLoad()` and that indeed did work, but what about running time entries? In those cases we can do `DatePicker.Date = ViewModel.StartTime.Add(ViewModel.Duration).ToNSDate()`, which basically the same as end time and it works for running and stopped time entries 🎊.

I propose that we use this solution, because i've spent hours debugging this and i can't come up with a better solution - there are no apparent differences in the way that start time is set vs the way that end time is set - the code is more or less the same, but it works for end time and not start time 🤦‍♂️

**Comment by simonrozsival** [comment]
🤔 oh man, I tried a completely different bug than the original issue mentions. I will create a separate issue.

If your solution works and if it works well for running TEs, let's do it.

**Comment by arturs105** [comment]
Yeah, turns out that for running entries it works only sometimes 😞
