### ISSUE TITLE
Create workspace feature models

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#214]
This might not be as straight forward as other models to convert between API and database models, because of the strange (nested) json format. A good common representation has to be found.

For the endpoints, see: #29

**Comment by amulware** [comment]
Please feel free to post a proposal here for discussion before implementing it, or if you are sure about it, just go ahead.

**Comment by kornelijepetak** [comment]
I can see some possible solutions for this.

1) Restructure the model to enable direct serialization and use that in API throughout the rest of the app.

2) Use different, custom `IJsonSerializer` instance for `WorkspaceFeaturesApi`, and manually adapt the structure from the response to the model.  

3) Add additional temporary (DTO) classes in the serialization part of the process that would mimic the HTTP response and then adapt them in-memory to what we actually want to use in the app, thus hiding those DTO classes from the rest of the app.

Out of those three options, 1st seems bad because the response format is counterintuitive for almost all other operations. Between 2nd and the 3rd, I guess it's better to use a few new classes that are used only in a single part of the process and not visible from then on, than to implement custom parsing logic with JSON.NET. 

3rd option would look something like this (don't mind the class names):

```c#
internal class WorkspaceFeatureCollectionDefinitionDTO
{
    public int WorkspaceId { get; set; }
    public List<WorkspaceFeatureDefinitionDTO> Features { get; set; }
}

internal class WorkspaceFeatureDefinitionDTO
{
    public WorkspaceFeatureId FeatureID { get; set; }
    public string Name { get; set; }
    public bool Enabled { get; set; }
}

internal static class WorkspaceFeatureCollectionExtensions
{
    internal static List<WorkspaceFeature> ToWorkspaceFeatures(
        this List<WorkspaceFeatureCollectionDefinitionDTO> workspaceFeatureCollection)
        => workspaceFeatureCollection
        .SelectMany(wf => wf.Features.Select(f => f.ToWorkspaceFeature(wf.WorkspaceId)))
        .ToList();

    internal static WorkspaceFeature ToWorkspaceFeature(this WorkspaceFeatureDefinitionDTO feature, int workspaceId)
        => new WorkspaceFeature
        {
            WorkspaceId = workspaceId,
            Name = feature.Name,
            Enabled = feature.Enabled,
            FeatureId = feature.FeatureID
        };
}
```

Json response would be naturally deserialized in API into DTO classes and then converted into real entities (i.e. `WorkspaceFeature`) with those two ext. methods.

Any comments?

**Comment by amulware** [comment]
Random thoughts:

In case 2, no need to write a whole serialised, a custom converter would do (something like this: https://github.com/amulware/awgraphics/blob/master/src/amulware.Graphics/Serialization/JsonNet/Vector2Converter.cs - pretty straight forward).

Also, in either case, I don't think we need to store the name string in the database or use it anywhere else. Though we do want to deserialize them so we can test them against our enum names. I'm not sure how to do this right now though.

I agree about option 1. Between 2 and 3, considerations that I think are important: Which uses less/less complicated code? Which has the nicer interfaces between API/other things (I guess they actually have the same interface?)

What about the option of exposing the DTO objects from the API and converting in Foundation only?

**Comment by willsb** [comment]
I think 2 is the most consistent with what we are currently doing. 3 is also something to consider, since it might yield less code, but I'd go with 2 for consistency sake.

> What about the option of exposing the DTO objects from the API and converting in Foundation only?
I'd rather not, since this is something Ultrawave should do.

**Comment by amulware** [comment]
Aren't you given ultrawave too much responsibility with that? So far it exposes the API pretty much 1:1

Also, doing this would have the nice side effect of exposing the name strings for us to check in tests, but wouldn't have us keep them around everywhere else. But I don't think we should decide on the best solution based on this argument.

**Comment by kornelijepetak** [comment]
I thought serialization is ultrawave's responsibility. This is technically not serialization but adaptation, but I still think it should expose a clean interface to the rest of the app. I'd say it should be more similar to what you want to use in app and store in your local db than what was returned from the HTTP server. Just a thought, actually.

**Comment by amulware** [comment]
Maybe I'll have to accept that there is no perfect way of doing this. :D

**Comment by kornelijepetak** [comment]
Regarding 2. It's not a whole serializer, but it's still a manually parsed code. I haven't seen anything like it in the rest of the codebase, so I am not sure that's what the most consistent thing is.

**Comment by amulware** [comment]
Do you have a proposal for being able to check the string names against the integer ids without having to carry the strings around through the whole app?

We can all ways ignore them with an attribute in Realm of course, but I don't think that even foundation should know about them.

**Comment by kornelijepetak** [comment]
Let me get this straight. You don't want names in the model. Instead the rest of the code should use FeatureIDs. But you still want to compare IDs to the names so that you know if enum has changed? So basically, only in tests?

**Comment by amulware** [comment]
Pretty much. And thanks for putting it like that, it sounds pretty silly that way. :D

Still, I think it is good to test the names as a sanity check (might catch a bug in backend that otherwise would be a pain to debug).

**Comment by kornelijepetak** [comment]
I still think the option 3 is a better approach in this case. However, Will said he would go with 2. From the API point of view, it doesn't matter, and the tests will be the same, so, @amulware what do you say?

Also, regarding the testing enum proposal: here are my thoughts.
I can remove the names from the model (i.e. `IWorkspaceFeature`), but still read them into DTOs on serialization. However, here's the visibility problem. I can't hide names from Foundation and still make them visible for Ultrawave.Tests.Integration (unless we make names internal and allow Ultrawave's `InternalsVisibleTo` for tests).

**Comment by amulware** [comment]
We already use `InternalsVisibleTo`. So you would then have the interface not include it, but the implementation of it in the API includes it, so the test has to cast?
Ugly, but I'm not sure I see a better alternative.


I'm wondering right now though... In the app, are we going to pass around List<IWorkspaceFeature> with the feature being a tuple of id and bool (essentially), or will we have an IWorkspaceFeatureCollection?

If we use the latter, we could hide away implementations details entirely, and allow the api to serialise trivially into a list of feature-collections, and the database, to store it entirely differently.

The feature collection would then have a workspace id, and methods like 'give me a list of all features (id, bool)' and 'is feature with id enabled?'.

Am I overthinking it?

**Comment by kornelijepetak** [comment]
Regarding enum testing: alternatively, you can provide *internal-only* API method for testing. I think DTOs should be hidden from everything except serialization. This could be achieved if combined with your suggestion. So that one of the API methods (i.e. `GetPossibleFeatures`) returns a collection of distinct tuples `(featureId, name)` which Test could then compare to the enum.

**Comment by kornelijepetak** [comment]
Also, I think retaining `IWorkspaceFeature.WorkspaceId`, just as you do with for example `IProject.WorkspaceId` would make things easier in the long run (persisting in db, consistency with the rest of the model). So I'm not sure if tuple is the best solution for something as well defined as the Workspace feature.

**Comment by amulware** [comment]
@willsb What do you think about my point of usage, i.e. list<feature> vs a custom feature collection? (and the other points)

**Comment by kornelijepetak** [comment]
Did you mean something like extending the Workspace so that it provides list of enabled features on it?

```cs
public interface IWorkspace : IBaseModel
{
    // other props
    
    IList<WorkspaceFeature> EnabledFeatures { get; }
}
```

Did I get something wrong?

**Comment by amulware** [comment]
No, I don't think we should do that, though it is an interesting idea. I just meant using a custom workspace-feature-collection to hide the implementation more. (whether it is stored as `{wid, [(id, bool)]}` or `[(wid, id, bool)]` ).

**Comment by kornelijepetak** [comment]
I am used to doing things that way (with _'navigation properties'_, to borrow terminology from EntityFramework), so I think it would at least be easier to use from the rest of the app. I also checked, and it seems that Realm supports such scenarios. 

Because you know, you always NEED to fetch the enabled features with the workspace. So I can't find a reason why this is not included in the `me/workspaces HTTP` response in the first place.

But maybe I know too little about the whole process at the moment to be a good judge of that.
