### ISSUE TITLE
UI doesn't updated when new TE is started while wifi/data is turned off

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2232]
When wifi or mobile data is turned off, I have managed twice to get the app into the state when after starting a new TE and tapping "Save", UI doesn't update.
1) Start a new TE & tap "Save"
2) App directs you to the Timer page but the bottom card doesn't appear and Start button is visible. I can't start a new entry because actually TE is running but I can't see it and Start button is disabled (nothing happens when I tap it).

Restarting the app doesn't help. Only when I connect to the wifi, it syncs and I can see the running entry I started before.

It doesn't happen every time though.

**Comment by kornelijepetak** [comment]
What I find out (unless it was a random fluke) is that whenever the connection is not available, I see this in application output, right when the TE card should show (saving TE):

```
mvx:Diagnostic:771.60 Requesting presentation change
mvx:Warning:771.65 Hint ignored CardVisibilityHint
```

...which is exactly the thing that governs the visibility of the card. Why this does not happen and what kind of connection exists between having not internet access and ignoring hints, I have not been able to discern. 🤔 😕 

Since he's the best at all things MVX, I suggest @willsb take a look at this issue. (For now I will unassign myself.)
