### ISSUE TITLE
X in onboarding hint in start view animates from left to right when the start view opens

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2305]
Either the whole tooltip should grow in size as well, or the X should not move.

In general, several other elements animate from left to right as well (confirm button, time at the top).

I like the view being a bit more dynamic looking, and not totally static, but we should maybe have this looked over by @pe0ny to decide properly how it should all behave.

**Comment by pe0ny** [comment]
Yes, the whole tooltip should grow in size together with its content.

**Comment by dshr** [comment]
Looks like the "dynamic look" is not intended — `EditTimeEntryViewController` does not exhibit the same behaviour, and I couldn't find any explicit code that does the resizing. So far it seems to be some kind of Autolayout side-effect, which I'll be looking into further.

**Comment by dshr** [comment]
I'm completely at loss as to what's causing the strange constraint behaviour on this screen, at any point before and after the show transition everything looks fine. Trying to capture the UI state midway throws an error 😭. I'm leaving this for someone with better AutoLayout chops to solve.

@khoi I'm removing the `pending-review` label, since this issue is not being reviewed right now.

**Comment by amulware** [comment]
Closing this for now, since we might change a lot about our onboarding anyways and it's a minor glitch.
