### ISSUE TITLE
Assign default-workspace if not set

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2316]
When we pull the user object:

IF
- the default workspace id does not correspond to any workspace we have locally/is 0/is null(possible?)
- and we have any workspaces locally
THEN
- set (any) one of those workspaces as default workspace
- mark the user object as 'needs-sync'
- persist the user object
ELSE
- persist the user object like before

This will prevent the app from crashing in cases where the default workspace is not assigned correctly, which is a realistic case that can happen (and might be happening - for all we know this might be the cause of https://github.com/toggl/mobileapp/issues/2103 🤔 

I'm not sure where this should be implemented, but I think inside a special pull/persist sync state makes the most sense. We don't want to have logic like this in realm, and I wouldn't know where else to put it. But maybe there is a better way.

In either case, I never want it to persist the fetched user object before stepping through the above logic. I don't even want a small chance at getting crashes if we can fix it 'this easily' ourselves.

Note that (I suppose) it will still not persist anything if the local user object has pending changes? I'm not sure exactly how that will interact. Please post some details on that and the different edge cases below or in the PR.

**Comment by simonrozsival** [comment]
Currently the default workspace ID cannot be null - or at least if it was null, deserialization will fail
   - we should make it nullable, if backend sometimes gives us a `null` value in this field
   - this might even be one of the problems with "infinite syncing" - the deserialization exception will be caught and will lead to retry loop (similar to what we observed with tags recently)

I think that in this case we should implement a specific persisting state (should be very easy when #2313 is merged) where we would make sure the ID is valid so that we can persist it. Or we can "just" overload the datasource methods and make sure that the workspace ID is valid before updating the object - that might be even easier.

I would like to point out that we don't really have a direct relationship between the realm user entity and the realm workspace entity - in this case we store just the ID and use it to find the workspace in the `GetDefaultWorkspaceInteractor`. In this case if the workspace with the given ID doesn't exist in our DB, we can simply pick "any" other workspace and use it as if it was the default workspace - if we implement this deterministically (e.g., select the one with the smallest ID), we can always use the same one without changing the user's entity (that seems dangerous to me, I don't really like the idea that we pick user's default workspace for him..).

☝️ I think the last suggested way should be the way to go for now. It is the easiest to implement, it is the "safest" for the user (we don't modify his prefernces for him/her, even though the "default" workspace is not something which would be really important from the user's perspective IMO).

**Comment by amulware** [comment]
Let's go with the latter approach. We'll fake it all locally.
