### ISSUE TITLE
Date displaying as Day., 28 May seems incorrect

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2347]
![image](https://user-images.githubusercontent.com/18132080/40769648-b0126f46-64f7-11e8-9601-9dc60bc0ae9c.png)
 See image for Mon., 28 May both period and comma seem incorrect

**Comment by juanlaube** [comment]
I wasn't able to reproduce this issue, then I realized it was reported by our _mate_ Jordan, so I switched the device language to English/Australia and turns out the week name is localized.

@pe0ny @amulware should we use the same format regardless of the localization/cultureinfo/etc or show localized formats? If we go with localized, weekday and month names may be in a different language.

**Comment by pe0ny** [comment]
We should use the same format regardless of the localization.
This is the right format: "Mon, 28 May"
