### ISSUE TITLE
Polish inaccessible project display

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2366]
From https://github.com/toggl/mobileapp/pull/2351

- is it OK to show the "(inaccessible project)" until we fetch the project?
- I reused the "no project" color (dark gray) - is that OK?

More details later/upon request.

**Comment by pe0ny** [comment]
@amulware 

> is it OK to show the "(inaccessible project)" until we fetch the project?

Until we’re fetching, we display: `(inaccessible project)`
After a few sections when we can tell the difference, we'll display: `Project name (archived)`
Or if it’s not archived, we still display: `(inaccessible project)`

> I reused the "no project" color (dark gray) - is that OK?

Let's use the colour we use for "Other" section in Reports #CECECE (it's a bit lighter than No-project colour #B5BCC0)
For the archived project, we should use the proper project colour.

**Comment by amulware** [comment]
Changed title. The changes can be implemented.

We need to:
- add " (archived)" to archived project names in the log (don't add them in the actual db data!)
- change the colour of ghosty inaccessible projects

**Comment by amulware** [comment]
Note: I don't remember exactly how we're representing ghost projects right now, but let's make sure we don't accidentally end up with "(inaccessible project) (archived)" in the UI.

**Comment by pe0ny** [comment]
In addition to `(archived)` text, we want to show a little archived icon at the front of the project name instead of the dot.

<img width="377" alt="screen shot 2018-06-14 at 12 36 08" src="https://user-images.githubusercontent.com/5064445/41404311-8c789d34-6fcf-11e8-8414-9c29f51eb610.png">

You can find the icon from the styleguide: https://zpl.io/agGOglZ
Also, let me know if it's needed in black or something since it should have the project's colour (not purple every time).
