### ISSUE TITLE
Sort out APK size and AOT

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2617]
Recently we enabled AOT, to get Giskard to start up a bit faster. This had the side effect of almost tripling the size of our APK to 121mb. Apart from that just being too much in general, Google only allows uploading of APKs of at most 100mb. For now, I disabled AOT again, but that's not a permanent solution.

We want both AOT and small APKs.

What might work is building separate APKs for different architectures, but I wasn't able to get that to work today, so I'm leaving this issue here for someone else to take a look.

Whatever we do, we have to make sure it works well on Bitrise and hopefully involves as little custom scripting as possible.

**Comment by daividssilverio** [comment]
### What have I tried:
I tried some ideas to handle our situation.
1. Following @willsb's idea, I tried enabling
```
<AndroidCreatePackagePerAbi>true</AndroidCreatePackagePerAbi>
<AotAssemblies>true</AotAssemblies>
<EnableLLVM>true</EnableLLVM> 
```
on `Toggl.Giskard.csproj` to check if bitrise would already be able to handle our needs since it should be a common case 🤔 . Well... it didn't work.

2. I checked https://github.com/bitrise-tools/go-xamarin (xamarin-archive@1.5.0) and discovered that this step actually only exports the last apk modified in the archiving process (that is, the final apk with 100mb+). This is actually commented in the step source code.

I tried modifying the step to export multiple apks, and it kind of worked locally.
Replacing this piece of code:
https://github.com/bitrise-tools/go-xamarin/blob/master/builder/builder.go#L484-L492
by:
```
if apkPth, err := exportApks(projectConfig.OutputDir, packageName, startTime, endTime); err != nil {
	return ProjectOutputMap{}, err
} else if len(apkPth) > 0 {
	for i:= 0; i < len(apkPth); i++ {
		projectOutputs.Outputs = append(projectOutputs.Outputs, OutputModel{
			Pth:        apkPth[i],
			OutputType: constants.OutputTypeAPK,
		})
	}
}
```
and modifying the inner methods to return all generated apks, I was able to make this step output all generated apks including all ABIs. (I just created a list and added all apks instead of filtering them). 

We could fork and modify https://github.com/bitrise-tools/go-xamarin to generate the apks we need. It took me a while to understand and run the step, but it's something doable.

### What else I thought about, but did't try yet
1. We could run multiple `deploy-to-bitrise-io` steps specifying the paths of the generated apks and the do the same thing to deploy to the PlayStore *IF* the files generated in the `xamarin-archive@1.5.0` step stay in place after it's finished, we would just have to find and use the absolute paths to those apks.

**Comment by daividssilverio** [comment]
That could work too, I'll 
* submit the issue for the bitrise plugin guys;
* and test if we can do what you said.

**Comment by daividssilverio** [comment]
I added the issue on the step repo we are using on bitrise. https://github.com/bitrise-tools/go-xamarin/issues/44

**Comment by daividssilverio** [comment]
Hey!
It turns out we can have a simpler solution o/ that won't require any code changes.
The Xamarin Archive step generates all the files and they stay in place! All we had to do was to copy the signed apks to the deploy folder on bitrise!

The script to copy the apks looks as simple as:
```
find ./bin -type f -name 'com.toggl.giskard-*-Signed.apk' -print0 | xargs -0 -I % cp -a % $BITRISE_DEPLOY_DIR/apks
```

We still have to look on the step to publish to the play store though.

**Comment by amulware** [comment]
I'll setup a proper release flow with all the information above for 1.3 next week, and we'll test it live. :)

**Comment by amulware** [comment]
Everything is setup correctly (hopefully). The first release build with all this is running here: https://app.bitrise.io/build/7d37dd93a4fef165

**Comment by amulware** [comment]
Everything seems to be working now. APKs have made it to the play store and first devices successfully.
