### ISSUE TITLE
WS removal: Detect workspaces the user lost access to

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2628]
We need a sync-state that does the following:

- [x] compare the list of workspaces fetched on pull sync with the workspaces in the app that have been synced (ignore local workspaces that have not been synced)
- [x] those that we know locally but did not get pulled are workspaces the user got removed from
- [x] pass those states on to the state which will remove data from those workspaces

We have to think about how exactly the flow works here. E.g. does the state pass on the list of all workspaces we were removed from? Or do we handle them one by one?

Also, at what point during the follow-up process do we mark the workspace itself as ghost/remove it? We have to make sure that if the app gets killed/syncing stops at any point, the local data remains in a valid state and will continue properly on next sync.

**Comment by simonrozsival** [comment]
I would say that the result should be a list of workspaces. That will be much easier and is more straightforward as the HTTP response gives us a list of workspaces that the user has access to.

The follow-up process will contain
1. removing all synced data
2. setting the workspace's `IsGhost` property to true

If the app is terminated while we delete entities in 1., it is fine - next time sync will run we will finish it, because we hadn't marked the ws as ghost yet so it will be detected next time. Also we deleted only synced stuff, which we didn't need in the meantime.

It might look weird in some edge cases:
- we delete half of the stuff we want to delete, user kills the app, goes offline, goes back to the app, sees only half of the data
- we delete half of the stuff, user kills the app, user gains back access to the workspace, goes back to the app, sees only half of the data and he/she can't pull the missing ones (because of `since` dates)

**Comment by amulware** [comment]
What if we set IsGhost first to avoid the second edge case? We only have to make sure to include time entries in the cleanup loop then.

**Comment by simonrozsival** [comment]
Or we just set the workspace to `IsGhost` and in a separate `clean-up loop` we will look for all ghost workspaces and try to prune as much data as possible. That would be immune to any interruptions to the clean-up process.

**Comment by amulware** [comment]
Agreed. Though we should at least trigger time entry clean up as soon as possible to make sure we don't show those for any longer than needed.

**Comment by amulware** [comment]
Looks to me like this was closed by the PR above.
