### ISSUE TITLE
iOS App crashes on launch

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#2661]
Case: 730008

Initially, we got this from a user:

> After reinstalling the app, it works again. I mostly use the browser on my workstation, but after a couple of days inactivity, when I try to launch the iOS app again, it crashes immidiately. Since it happens on launch, Crashlytics or similar framework is unable to send the logs. I grabbed to crash log from my phone via Xcode and attached it to the email. You will need to symbolicate it.

Then we rolled out an update and this is what we got from the same user today:

> Latest updated mentions that the issue should be fixed, but its not. Same pattern as previously. When I delete the app and reinstall it, it works. But next time I try to use it, it does not open, crashes while launching.

The crash logs are not supported in GH so you will need to access the desk case to download them there. 

Let me know if there's anything else you need here.

**Comment by amulware** [comment]
@VeljkoTN We need to know what happens before the crashes start, or what state the user's data is in that it wouldn't work the second start.

Ideally, we need to know how to reproduce this.

Something to try perhaps is to force-sync. The second start will do that - force-sync, which might be the problem, because... of some weird state. Based on if force syncing works, then at least we can eliminate some options.

**Comment by amulware** [comment]
Unscheduling until there is more information. @VeljkoTN

**Comment by heytherewill** [comment]
🌵
