### ISSUE TITLE
Line Spacing/Text Size issue 

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#2668]
If you change the text size in your devices general settings you will get overlapping text in the Toggl Android app version 1.0 here's how you can reproduce the issue: 

1. Go to settings > Display > Text Size - Select Extra Large: 

![img_20180712_151143](https://user-images.githubusercontent.com/36152180/42635399-4401e09c-85e6-11e8-9adc-ad1172ee6e5e.jpg)

![img_20180712_151158](https://user-images.githubusercontent.com/36152180/42635410-4ad6fa60-85e6-11e8-826e-24a58f18b341.jpg)

![img_20180712_151219](https://user-images.githubusercontent.com/36152180/42635432-52c80afc-85e6-11e8-8a71-12498f275bc4.jpg)

And you get: 

![img_20180712_151533](https://user-images.githubusercontent.com/36152180/42635518-8d97f8ea-85e6-11e8-8234-20a517eb14f9.jpg)

**Comment by TheSoloJake** [comment]
Also Desk case/739443

**Comment by VeljkoTN** [comment]
Case: 739492 same issue on an Asus phone

**Comment by amulware** [comment]
The issue occurs with both suggestions and the log, and maybe in other places.

I see the following solutions:
- disable font resizing (bad UX in my opinion)
- adjust the height of TEs and suggestions
- anchor labels differently (to center of the container, or to their own center, depending on which works better)

I think I much prefer the latter. We should be able to test easily enough that smallest, medium and largest size all look ok.

If @pe0ny doesn't make a call, I will at least for an initial fix, since several users have brought this up, and it really looks a bit broken.

**Comment by pe0ny** [comment]
I agree we should come up with the initial fix at least. It looks also a bit off with "Large" not only "Extra large" size.

For now, let's try out the last option Paul suggested. But I would also like to know the font sizes (what is large and extra large) so we can fine-tune those and make sure to add correct line heights and padding for each size. Do we know that already?

**Comment by kornelijepetak** [comment]
Heidi, wouldn't it be better if we specified the top/bottom paddings and made the project label always below the description and then let the layout work out the height of the cell itself on the respective fext size?

I am against specifying different designs for different font sizes... it will soon get unmaintainable...
I am working on this issue right now, so I can come up with some screenshots of what I think would work... so you can maybe comment on that...

**Comment by amulware** [comment]
@kornelijepetak I'd say let's go with the solution you showed off internally, for now, just to fix the time entries and suggestions.
