### ISSUE TITLE
Reports: WS select UI

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2703]
Requires #2702
iOS version here: #2624

**Comment by lizaPlotnikova** [comment]
Hey guys! I'd like to hear some of your thoughts on this layout:

<img width="1189" alt="screen shot 2018-07-20 at 3 24 11 pm" src="https://user-images.githubusercontent.com/24964497/43021313-335b687a-8c31-11e8-8d81-ec33482dc255.png">

My thoughts on the designs: 
### v1 (leftmost screenshot)
This is parodying what is designed for iOS already – The WS select UI would be a custom fab that floats on top of the content. As in iOS because we don't want it to obscure any content permanently, extra padding would be added below the projects table to accommodate the height of the fab

I'm not a big fan of this design for a couple of reasons. 1) I don't think this is a very discoverable position for the element... you basically need to read the whole screen first before even seeing the button 2) I don't think it supports the hierarchy well because it's describing what the content of the whole screen is, but is positioned at the very bottom 3) its using a really modified version of a fab, yet a new custom component

So I propose the two alternatives: 
### v2
put a "single-cell" element (same one as in the "Edit" view) into a card at the top of the content
this might have better affordance (for it being clickable) than v3

### v3 (rightmost... sorry about the typo in the screenshot again)
put a "single-cell" element at the top of the content
this seems less cluttered to me, and more like a header (which I think is appropriate for the content)

**Comment by amulware** [comment]
@pe0ny @lizaPlotnikova Please confirm if the design above is final or not. Discuss internally if needed. Thanks!

**Comment by lizaPlotnikova** [comment]
Updated / Finalized designs:

- If a user belongs to multiple WSs, display the name of the selected WS at the top of the Reports page
- A user can change the selected WS by clicking the fab in the bottom-right which launches the Workspace picker dialog

![reports multiple workspaces](https://user-images.githubusercontent.com/24964497/44749975-297a1e80-aae2-11e8-9ef5-09d99d44dce9.png)
Zeplin: https://zpl.io/a3ljJG8

![reports ws selector](https://user-images.githubusercontent.com/24964497/44750238-d2c11480-aae2-11e8-9348-2f306017e90c.png)
Zeplin: https://zpl.io/aBNKn8A

**Comment by kornelijepetak** [comment]
@lizaPlotnikova @pe0ny 

1. Zeplin needs a briefcase white icon as an image resource, not a shape.
2. Is the title supposed to be scrollable with the report or always visible as a kind of header? (currently it's the latter)

**Comment by lizaPlotnikova** [comment]
@kornelijepetak, I've added the briefcase white icon as an image, but, I'm wondering if we should use the svg asset here to start the move to all svgs? The color of this icon should be white.

I intended for the title to be scrollable with the report. @pe0ny do you agree?
