### ISSUE TITLE
Investigate the local notification apis of both iOS and Android

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2756]
Please investigate and post your findings here for future reference.  Ideally we should get:

- A list of the APIs needed (with links to its docs),
- An idea of how easy it's to use it (is it easy to consume it in an async/reactive fashion? Lifecycles?)
- How similar both apis are, (what’s the iOS/Android counterpart of apis? if none is available, how could we make a non-leaky abstraction?)
- links to existing Xamarin library we can base our implementation on, if any Investigate the local notification apis of both iOS and Android

**Comment by juanlaube** [comment]
# iOS
[Local and Remote Notifications Programming Guide](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/)

### Things we can do
* Add sound and badge number to app icon
* Customize UI when using 3D touch on the banner
* Add quick actions to notifications (e.g: Stop timer) that appear when using 3D touch on the banner
* Schedule notifications (one time or repeating every )
* Trigger notifications based on location. This would be a great addition if we know the location of a calendar event
* Group by thread (new in iOS 12, we cannot use this yet)

### Things we can’t do
* Persistent notifications (as in Android)

## API
### Request authorization
```swift
let notificationCenter = UNUserNotificationCenter.current()
notificationCenter.requestAuthorization(options: [.alert, .sound, .badge], completionHandler: { authorized, error in
    print(authorized, error)
})
```

### Schedule a notification every 30 seconds
```swift
let content = UNMutableNotificationContent()
content.title = "Hello, I'm a notification"
content.body = "This is the body of such notification"
content.sound = UNNotificationSound.default

let date = Date(timeIntervalSinceNow: 30)
let triggerDate = Calendar.current.dateComponents([.year,.month,.day,.hour,.minute,.second,], from: date)
let trigger = UNCalendarNotificationTrigger(dateMatching: triggerDate, repeats: true)

let request = UNNotificationRequest(identifier: "local-notification", content: content, trigger: trigger)

notificationCenter.add(request, withCompletionHandler: { error in
    print(error)
})
```

### Handling notifications
```swift
// Somewhere in application(_:didFinishLaunchingWithOptions:)
UNUserNotificationCenter.current().delegate = userNotificationDelegate
```

## Important notes
* Feature availability and API is the same for all the iOS versions we support.
* Notifications callbacks are handled in AppDelegate.
* Scheduled notifications are not persisted after a device reboot.

# Android
[Notifications Overview](https://developer.android.com/guide/topics/ui/notifiers/notifications)

### Things we can do
* Add sound and badge number to app icon
* Add quick actions to notifications (e.g: Stop timer) 
* More templates to configure compared to iOS, e.g: a progress bar in the notification, useful if we know the duration of an event 😉 (Android Nougat)
* Have a custom notification UI
* Set notification channels, this gives more control to users about what notifications they want from apps (Android Oreo)
* Persistent notifications (is more complicated in Android Oreo due to background services restrictions)

## API
### Request permissions
Just add the permission to manifest.xml (I think?)

### Schedule a notification
```java
Intent intent = new Intent(this, DetailsActivity.class);
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, intent, 0);

NotificationCompat.Builder mBuilder = new NotificationCompat.Builder(this, CHANNEL_ID)
        .setSmallIcon(R.drawable.notification_icon)
        .setContentTitle("Hello, I'm a notification")
        .setContentText("This is the body of such notification")
        .setPriority(NotificationCompat.PRIORITY_DEFAULT)
        .setContentIntent(pendingIntent)
        .setAutoCancel(true);

NotificationManagerCompat notificationManager = NotificationManagerCompat.from(this);

notificationManager.notify(notificationId, mBuilder.build());
```

## Important notes
* Important note: Feature availability and API are not the same for all the Android versions we support, however, the basics are the same, and more features are added in newer versions.
* Notifications callbacks are handled by intents.

## Common interface
We can have a ILocalNotificationService that wraps the common interface. APIs are similar in how we create and schedule the notifications, but not in how we handle them, however, I don’t think this is a limitation to create some common interface.

## Existing Xamarin libraries
If there’s anything common for both platforms, I couldn’t find it 😕
