### ISSUE TITLE
Do not show ratings dialog by default

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2827]
## 🐛 Bug Report
The ratings dialog is set to show on one of the triggers by default.

## Expected behavior
It should never be shown to user unless we activate an appropriate experiment.

That's the only way we can gather meaningful data on small samples of users

## To reproduce
- Have 1.8 installed
- Wait five days
- Start/stop a time entry

## Suggestions
You could set the 5-day limit lower for testing purposes.

**Comment by sofokli1** [comment]
If a user has had the app installed for a long time most likely no matter the day count parameter in the remoteConfig of the experiment (like 5, 10 or 20 days) it will show the rating view only based on the button trigger (start, stop, continue) since the other parameter will be true in this situation.

**Comment by amulware** [comment]
Yes, that is an issue with testing the number-of-days in our experiment. But we can still experiment with the trigger parameter and see how it works out. Once we determined the best trigger, we can push the experiment to everyone, and once everyone has see the dialog, we can start testing the time parameter on new users.

**Comment by juanlaube** [comment]
Setting the criterion to `none` (or something different from `start|stop|continue`) in Firebase's remote config should solve this.
