### ISSUE TITLE
Add idle timer notification

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3056]
This is an optional feature that can be enabled in the settings. When it is enabled, as long as the user is logged in and has no running timer we should show a permanent notification that will inform the user that no timer is running.

It will also allow them to get to the app easily. Perhaps there will even be a shortcut button to start a timer and go straight to the start view?

If the user changes the appropriate setting, the notification should appear/disappear right away if needed.

**Comment by pe0ny** [comment]
<img width="369" alt="screen shot 2018-08-24 at 10 14 22" src="https://user-images.githubusercontent.com/5064445/44570432-809c8e00-a786-11e8-8926-abe68cdf6e1c.png">

### The header area is comprised of:

**1. The app icon:**
The app icon that appears in monochrome in the status bar.
Question: Is it possible to show a different icon there when the timer is not running? If not, show the same like in here #3055

**2. The app name:**
The name of the app automatically appears in the notification.

**3. Header text:**
We won't display anything here.

**4. Timestamp:**
What the title says.

### The content area:

**1. A content title:**
Since both a content title and text are needed, we'll display just "Toggl" here.

**2. Content text:**
And "What are you working on?" here.

Tapping the notification itself will open the app in the Timer page.

The expandable option will be added in the future but not in this phase.

**Comment by dshr** [comment]
Putting this on hold until we merge #3170

**Comment by dshr** [comment]
@pe0ny I'm a bit confused about the timestamp — do we show the time since the app was opened or the time since the last time entry has ended?

**Comment by daividssilverio** [comment]
🤔 It looks like it's the time since the last time entry has ended. But... this might be weird if the user don't use the app too often. The nice thing about it is that whomever doesn't need it, can disable it.

**Comment by kornelijepetak** [comment]
Closed by #3189
