### ISSUE TITLE
Implement stop entry intent

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3083]
This is here for discussion, I want @amulware to give his opinion on some points.

The entry should be stopped from the extension, this should be the logic:
- Check if there's an api token and last sync timestamp in the shared space, other wise redirect the user to the app.
- Check the last sync time, if it's been "too long", redirect to the app. (What's too long?)
- Get the latest entries from the API endpoint, if error redirect to app.
- Compare time of last sync with start time of latest entry:
  - If there's a server entry running
    - If the time of last sync >= last entry start time -> send stop request. Set a request for sync timestamp in the shared space.
    - If the time of last sync < last entry start time -> ... What should we do here? Error? Stop it anyway?
  - If there is not a server entry running.
    - If the time of last sync >= last entry start time -> Error: there's no time entry running.
    - If the time of last sync < last entry start time -> Error: there's no time entry running (And advice the user to open the app?)

If the intent is successful Siri should respond with: "Time entry stopped, you've been {TE_DESCRIPTION} for {TE_DURATION}" 

If there's an error Siri should respond with the appropriate error and opening the app if necessary.

When the user goes back to the app, it should check for the request for sync timestamp and see if it's newer than the last sync, if it is, it should try to sync.

**Comment by amulware** [comment]
> If the time of last sync >= last entry start time 
I think instead of comparing to the start time, we should compare to the last update time of the time entry. That's the `At` property.
Maybe, instead of storing the time of the last sync in the shared space, we should store the last time entry sync date for this comparison? (This is stored in the SinceParameters storage in Realm)

> If the time of last sync < last entry start time
(also adapted per the previous point I imagine)
This case means that the app likely does not know about the time entry. 
There are two cases now:
- if the app has no running time entry itself, we could just stop this one, all good
- if the app has a running time entry, but this one is different than the one online (maybe we can check this by id or something), we should stop the newer of the two entries (by start time? at time? oh dear...) this case is getting complicated :/

If there is no entry running on the server.... too bad I guess? Probably best what you suggest in that case (maybe again with the time check adapted to use the Since/At dates instead of the last sync date).

**Comment by Odrakir** [comment]
Agree about the `At` property.

About the "last time entry sync date"... won't it be the same as the last sync date? 

I'll think about the other cases...

**Comment by amulware** [comment]
The since-date will be actual last AT date of a time entry, so it's basically 100% sure. The sync time might be funny because of clocks being out of sync/time settings wrong... Probably not relevant in most cases, but I think it might be safer 🤔
