### ISSUE TITLE
Implement start empty entry intent

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3085]
The entry should be created from the extension, this should be the logic:
- Check if there's an api token and last sync timestamp in the shared space, other wise redirect the user to the app
- Check the last sync time, if it's been "too long", redirect to the app
- Get the latest entries from the API endpoint (if error redirect to app)

Open for discussion: What should happen if there's an entry running? Should it be stopped and then create the new one, or should we respond with an error? @amulware

**Comment by Odrakir** [comment]
@amulware The idea is this will go to the API to start an entry, it won't do anything with the app, other than setting a flag for the app to sync.

**Comment by amulware** [comment]
Only one time entry may be running at the same time. In principle, it is enough to push a new running entry to backend, and backend will stop a previously running one at that point.

We could download entries, find the running one, and stop it, push that and then push the new running one, but that's all a ton of work, that may not be necessary. Not to mention it won't be any good if the app didn't sync whatever the user started running in it last time for example.

In that sense, **we could think of the extension as a separate app**, which is 'always online' and if it can't make connection (no/bad internet, or any other error response from the api really), maybe it should also direct the user to the app, instead of trying to do something very fancy?

Something else to consider btw: a time entry always needs to have a workspace, so you'll have to give the workspace id to the extension as well.

Regarding the 'too long' since last sync thing, what do you image that time frame to be? (and why)

**Comment by Odrakir** [comment]
I was asking more about the UX part of things, so if there's an entry running, we just start a new one, ok.

About the workspace... I'm not sure if we should use the shared space for this or let it be part of the information in the intent it self, like "the user started an entry in workspace x". The problem I see is then the same thing for workspace y will be a different intent and needs a different shortcut.

But then again if it's on the shared space we will have to deal with changes in the default workspace as well, won't we.

About the "too long" time frame... I have no idea, I think it will be more a trial and error thing. Maybe we can start with 24 hours?
