### ISSUE TITLE
Handle cases when background of calendar entries has light color.

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3167]
Currently time entries in the calendar can be barely readable if the project color is too light (see screenshot).

We should use varying text colors based on the background color.

![screen shot 2018-09-05 at 17 40 32](https://user-images.githubusercontent.com/15633003/45101507-4d69df80-b134-11e8-80bc-f8431f8a01e3.png)

**Comment by pe0ny** [comment]
Can we check the contrast ratio and make a decision based on that? For example, if the contrast ratio is below 3, we use varying text colours based on the background colour?
Here's the example: https://webaim.org/resources/contrastchecker/ and here's the example of the formula: https://www.w3.org/TR/WCAG20-TECHS/G17.html

**Comment by amulware** [comment]
Since the font colour is fixed, that math can be simplified significantly. Also I'm not convinced that the gamma correction performed there is really necessary. A simple luminance calculation and check against a constant might be more than adequate to decide whether to make the text white or black. Don't overcomplicate.

**Comment by willsb** [comment]
Closed by #3180
