### ISSUE TITLE
Siri: Review UI and response copies

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3382]
We should list all texts used as Siri' responses and in the UI extension, including buttons and intent types (the `Do` may not be the best option) and then someone should review those texts and see if they can be improved or are correct.

The thing is I wrote them my self as temporal texts while development, so we should probably read them again.

**Comment by khoi** [comment]
Currently we support 4 Siri intents. Here is the list of all the text used in them:

## Start Timer

Title: `Start timer for ${entryDescription}` or `Start Timer` (when entry desc is empty)
Description: `in ${workspace}`
Suggested Invocation Phrase: `${entryDescription}` or `Start Timer` (when desc is empty)

### Responses:

1. Success: `Time tracking started.`
2. Failure no API token: `You need to log in to continue.`

## Stop Timer

Title: `Stop Timer`
Description: `Stop current running time entry`
Suggested Invocation Phrase: `Stop Timer`

### Responses:

1. Success: `Stopped. You've been doing ${entryDescription} for ${entryDurationString}.` 

Values for `entryDurationString` can be:

- `xx seconds` when minute and hour are 0.
- `xx minutes and xx seconds` when hour = 0
- `xx hours, yy minutes and zz seconds` otherwise

2. When no entry running: `There's no entry currently running.`

3. API token not found: `You need to log in to continue.`

## Show Report with no specified period

Title: `Show Report`
Description: `Show report`
Suggested Invocation Phrase: `Show Report`

### Responses:

1. Success `Here is the report.` (not really visible to the users since the app is opened right away)

## Show Report 

Title: `Show report`
Description: `for ${period}` where period can be `Yesterday`, `Today`, `This Week`, `Last Week`, `This Month`, `Last Month`, `This Year`
Suggested Invocation Phrase: **MISSING**

### Responses

1. Success `Here is the report for ${period}.` (also not visible to the users)

**Comment by lizaPlotnikova** [comment]
Hey guys, here are my suggestions for copy updates. Anything that I don't think needs updating, I marked with a ✅The ones I think do need updating I marked with a ❗️ 
  
Start Timer
Title: Start timer for ${entryDescription} or Start timer(when entry desc is empty)✅
Description: in ${workspace}✅
Suggested Invocation Phrase: Track ${entryDescription} or Track time(when desc is empty)❗️
Confirmation Button Label: Start ❗️ 
Confirmation Label: "Start tracking ${entryDescription}?" or if desc is empty "Start tracking time?" ❗️ 

Responses:
Success: Time-tracking started. ❗️ 
Failure no API token: Log in to use this shortcut.❗️ 

Stop Timer
Title: Stop a running timer ❗️ 
Description: none ❗️ 
Suggested Invocation Phrase: Stop tracking❗️ 
Confirmation Button Label: Do ✅
Confirmation Label: "Stop tracking ${entryDescription}?" or if no description "Stop tracking time?" ❗️ 

Responses:
Success: Stopped. You've tracked ${entryDescription} for ${entryDurationString}. or "You've tracked time for ${entryDurationString}."❗️
Values for entryDurationString can be:

xx seconds when minute and hour are 0.
xx minutes and xx seconds when hour = 0
xx hours, yy minutes and zz seconds otherwise

When no entry running: There's no timer running. ❗️

API token not found: Log in to use this shortcut. ❗️

Show Report with no specified period
Title: Show report ✅
Description: none ❗️
Suggested Invocation Phrase: Show my time❗️

Responses:
Success Here is the report. (not really visible to the users since the app is opened right away)

Show Report
Title: Show report ✅
Description: for ${period} ✅
where period can be Yesterday, Today, This Week, Last Week, This Month, Last Month, This Year 
Suggested Invocation Phrase: Show ${period}'s time ❗️

Responses
Success Here is the report for ${period}. (also not visible to the users)✅

**Comment by khoi** [comment]
the response for Stop Timer

Confirmation Label: "Stop tracking ${entryDescription}?" or if no description "Stop tracking time?" ❗️

will be done in another issue #4588

**Comment by Odrakir** [comment]
When starting, Siri responds with: "Ok. Starting. Time-tracking started". 

The first part is generated by the system because we are using a "Start" type of intent, but all together sounds a little repetitive. What do you think @lizaPlotnikova ?

**Comment by lizaPlotnikova** [comment]
Agreed. Maybe just the first part is enough and we don't need a custom success message.

**Comment by lizaPlotnikova** [comment]
What's the automatic success response for "Do"? @Odrakir? Is the "Stopped. You've tracked ${entryDescription} for ${entryDurationString}." running into redundancy problems too?
