### ISSUE TITLE
Duration edit view animates twice

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3389]
## 🐛 Bug Report
When trying to edit duration of a time entry, the wheel view animates twice (see gif below). It looks like it is presented twice, but when you close it, you can see that there was only one.

Build/Branch: `develop`
Phone OS: iOS 12 and iOS 10.3.1
Phone model: iPhone 8 and 7 simulators

## Expected behavior
It should only animate once.

## To reproduce
1. Tap on a time entry in the log to open edit view
2. Tap on duration row in the edit view
3. Duration edit view is presented
4. The duration edit view animation is repeated

**Comment by simonrozsival** [comment]
I can't reproduce this. 

Just to be sure: when you tap on duration row in the edit view, it opens the duration editing view and as soon as it is presented it focuses the duration input which should open the keyboard - this triggers another animation, which moves the whole view up to make space for the keyboard. This second animation is intentional - isn't this what you meant?

**Comment by arturs105** [comment]
😅 Ahh, yes, i forgot about the keyboard. This issue happens when the simulator does not run the software keyboard. Enabling the keyboard makes everything behave as it should.
