### ISSUE TITLE
Fix Nightly UI Test

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#3437]
## 🐛 Bug Report
Nightly UI Test is currently broken due to the problem with provisioning profiles again 🤦‍♀️

## Context
Check https://app.bitrise.io/build/d72a36992143bb1d

**Comment by khoi** [comment]
Uploaded missing provisioning profiles and certificates to Bitrise, now it's failing with 
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2879,2): error MSB6006: "java" exited with code 2. [/Users/vagrant/git/Toggl.Giskard/Toggl.Giskard.csproj]
```

**Comment by daividssilverio** [comment]
This could be fixed by changing the build where the tests are run to a Debug build.
In `build.cake`:

```
Task("Build.Tests.UI")
    .IsDependentOn("Nuget")
    .Does(BuildSolution("UITests"))
    .Does(GenerateApk("Release"));
```
Should be enough to change "Release" to "Debug"; and

Toggl.Giskard.Tests.UI.Configuration.cs:
```
using Xamarin.UITest;
using Xamarin.UITest.Android;

namespace Toggl.Tests.UI
{
    public static class Configuration
    {
        public static AndroidApp GetApp()
            => ConfigureApp
                .Android
                .ApkFile("../../bin/Release/com.toggl.giskard.apk")
                .EnableLocalScreenshots()
                .StartApp();
    }
}
```

Change the `ApkFile` from `../../bin/Release/com.toggl.giskard.apk` the path the debug apk is generated (which might not be the same directory). Maybe `../../bin/Debug/com.toggl.giskard.debug.apk`
