### ISSUE TITLE
Android user cannot change AM to PM when manually creating a time entry

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#3500]
## ⛑️ User Support
It is AM in place x, user is trying to add a new time entry to yesterday and set the start time to PM. Upon saving the time entry, PM gets reverted to AM. Screencast for one user available in conversations/18984477026

## About the user

App version: Giskard 1.5.2
Phone OS: n/a for the user that shared the screencast, 6.0.1 LOLLIPOP_MR1 for the one that provided steps to reproduce below
Phone model: OnePlus ONE E1005 for the user that provided steps to reproduce below

## Expected behaviour
When changing time entry start/stop time from am to pm or vice versa and saving the time entry, the selected option should get saved. 

## To Reproduce
Minimal case repro steps (provided in conversations/19020832796):
It is currently 12:45am
Using manual mode, click green + to add a new time entry
Pull up the Duration selector
Select STOP tab
Select PM (Expected behavior: End time should now be 12.5 hours past Start time)
Verify PM is selected -- click sound is produced, "PM" entry is highlighted
Verify PM is remembered -- select START tab, then back to STOP tab. "PM" remains highlighted.
Unexpected behavior: when in START tab, the STOP time shown does not preserve "PM"
Select OK
Unexpected behavior: DURATION value has not changed to reflect "PM" selection. Default 30minutes is still displayed.
Unexpected behavior: End time summary has not changed to reflect "PM" selection.
Select Save.
Unexpected behavior: End time remains at default "AM" selection; Duration remains at default 30minutes.
This behavior is identical if you make changes to hour or minute before attempted to change AM/PM,

## Suggestions
Workaround is having the user switch to 24h mode, but that doesn't fly for users that are used to using am/pm.
Another workaround: selecting AM/PM, then choosing an hour (even if it is the same hour currently displayed) does result in the correct AM/PM being preserved.

**Comment by maritoggl** [comment]
I am leaving this open for the time being as we have received way too many reports like that and I am thinking that this issue could be phone or OS specific. I could not reproduce myself.

**Comment by epagnini** [comment]
conversations/19221876843

**Comment by epagnini** [comment]
conversations/19167047177

**Comment by kornelijepetak** [comment]
After multiple attempts to reproduce on different android versions, I am afraid this is a bug that only happens on Android Lollipop. This is also consistent with all the reporting user's OS versions.

The real cause is basically that time picker does **not** emit `onTimeChanged` event when it should - on AM/PM tap. It simply doesn't. I've tried using tapping as an event to fetch the time manually, but that's just gross and it does not work when tapping on the numbers or AM/PM because apparently some UI views are not propagating the tap.

I have spent too much time on solving that and I don't think it's that much worth the time. So, we have 3 possible options.

1. Ignore the problem and politely ask the users to either use a workaround (tap on hours/minutes after selecting the AM/PM button) or upgrade their phones. 😄 
2. Implementing our own timepicker which would be very time consuming and questionably useful
3. Falling back to spinner time pick chooser for that version of OS
![image](https://user-images.githubusercontent.com/7033216/48267404-8ecb8380-e432-11e8-9cc3-652a206f4103.png)

Current user stats say that 2.7% of users use 🍭 .

@amulware take your pick.
