### ISSUE TITLE
Gather all available info on failing Google Login

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3595]
This has been a recurring problem for too many of our users. I'd like to see what information we have on this so we can maybe pass it on to backend for further investigation.

Please post any information (and their source) we have below! (Unless the information is sensitive, in which case, post it somewhere privately and link it here)

**Comment by juanlaube** [comment]
Here is all the info I was able to gather regarding to Google login issues:

## Credentials
**iOS**
* client id: `<redacted>`
* secret key: `<redacted>`

**Android**
* client id: `<redacted>`
* secret key: `<redacted>`
* signing cert hash: `<redacted>`


## Authentication flow

### Get access token

**iOS**
* User taps login with google
* In-app web browser loads OAuth flow
* We get the access token

**Android**
* User taps login with google
* App starts intent, it’s handled by google play services
* We get the access token

### Login
* We have an access token
* `GET /me?app_name=toggl_mobile`, auth header is base64 encode of `{access_token}:google_access_token`

### Sign up
* We have an access token
* `POST /signup?app_name=toggl_mobile`,  body:

```
{
  "google_access_token" : <googleAccessToken>,
  "workspace" : {
    "initial_pricing_plan : 0
  },
  "tos_accepted" : true,
  "country_id : <countryId>
}
```

 
## Current issues
The request to `/me?app_name=toggl_mobile` fails sometimes for unknown reasons.
I couldn’t log the status code/error message in production or reproduce this in staging. 
We always get the google access token though, I confirmed this using Charles Proxy.

:speak_no_evil: :see_no_evil: :hear_no_evil:
We’re not sending `tos_accepted` and `country_id` in the `/signup?app_name=toggl_mobile` request (but we do in the sign up with email flow).


## Previous issues
When the new Android app launched, login/sign up with Google was broken to all users because we were using an incorrect client id. On Android, the client id depends on the app signing certificate hash, because we use App Signing by Google Play, instead of using the certificate hash for distribution, we were using the hash for the uploading certificate.

**Comment by juanlaube** [comment]
We're tracking all unknown login and sign up errors now, nut so far there's nothing related to google login/sign up in appcenter. We will keep monitoring this:

https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/analytics/events/UnknownLoginFailure
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/analytics/events/UnknownSignUpFailure

**Comment by amulware** [comment]
There are a handful of google login/signup exceptions tracked above, but it pales in comparison to other sources of error, so I'm closing this for the time being.
