### ISSUE TITLE
Clicking on Today or Yesterday in the Android app go to 2017

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3702]
## 🐛 Bug Report
In reports on the Android app, if you click on Today, Yesterday, This week, This Month, for some reason it magically transports you back to that date in yesteryear and shows you the results from 2017.

## Context
Current public build of 1.6

Build/Branch: 1.6
Phone OS: Android 8.0
Phone model: HTC U Ultra

## Expected behavior
It should show me the time entries from today, yesterday, this week and this month. Not the time entries from this day last year.
## To reproduce
Click on Today, Yesterday, This week or this month

**Comment by VeljkoTN** [comment]
another [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/19690988913)

**Comment by VeljkoTN** [comment]
another [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/19758951232)

Posting case links here because we have a GH plugin in Intercom that links the issue and updates the case automatically, but only if the intercom case is linked here, let me know if that bothers you, I can live without it 😄

**Comment by VeljkoTN** [comment]
another [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/19737938588)
