### ISSUE TITLE
Too Many Requests syncing failure UX needs changing

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3917]
We have a problem that our app sometimes makes too many requests to the server in a short time span (e.g., user uses pull-sync several times in a row) and our app receives a 429 response. In this case we are supposed to wait for 60 seconds and only then continue.

With the new leaky bucket implementation (#3876) we should "hardly ever" run into this problem, but it might happen anyway (e.g., the user uses the app and the web app at the same time, which might happen when user is trying to resolve some syncing issues between the apps he thinks he/she has). There will always a possibility that this happens. The question is what to do in that case.

Right now we keep showing a grey bar with a `Syncing...` text. The app internally doesn't do anything for 60 seconds and then it tries to do whatever failed before and hopefully this time we don't get any 429. It might seem to the user that syncing got stuck. Also if the user closes the app at this moment, syncing most likely won't finish.

With a "fail fast" approach (#3879) we show a grey bar with a `Failed` text. User can then use pull-to-refresh immediately which would most likely cause yet another 429. In this case syncing does not appear to be stuck, but it might scare the user because of the copy and the most likely also failing next attempt to force sync.

Because we will be able to limit the number of cases when we run into this problem I suggest we use the "fail fast" approach and change the copy to something like a grey `Try again in a minute.` (there is very little space for a long message). We might also disable pull-to-refresh for the next 60 seconds.

Ideas and suggestions are welcome!

**Comment by juanlaube** [comment]
Another approach could be "lie" to the users while we need to wait because of 429s and show some fake progress for a few seconds and then fail fast. This gives some idea of progress even if there's not, and prevents users from forcing another sync immediately, however a few users may see through this and get annoyed.

**Comment by syko** [comment]
Iirc the bucket size was 10 so it allows 10 "burst" requests before giving 429. On the FE side we attempted to leverage this and implement a retry mechanism with a backoff in such a way that we can fake the syncing fully.
`sync at 60req/min -> 429 -> wait a few seconds and try again from where we left off because the bucket should have some room now (assuming the previous requests have returned)`

So the user never has to manually reinitiate sync due to 429.

Whether this is the correct way or desired should of course be reconfirmed by BE.
