### ISSUE TITLE
BindAction extension isn't working as you'd expect

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#3963]
## 🐛 Bug Report
In someplaces where the `BindAction` extension is being used, events are being forwarded to subscribers only once. This is causing the UI to become irresponsive after the first interaction with the user.

## Context
It seems to be affecting both android and iOS.

## Expected behavior
The events should be sent to the subscribers whenever they happen.

## To reproduce
Find a place where `BindAction` is being used, specially where the user ins't navigated to other screen after interaction.
Examples from where it was happening: 
Sign up screen -> Select Country; Sign up button
Settings screen -> Select default workspace

## Workaround & Related issues
Replacing the `BindAction` with a simple subscription does make it work.
Examples of the workaround here: #3952 #3953

**Comment by Odrakir** [comment]
It is critical.

What I found so far: This happens when creating a `RxAction` from an `async Task`, but only when the async Task has certain complexity. I think it's something related to leaving a scope and then things get deallocated, or something. I'm not sure yet.

The thing is the Observables in the Action get deallocated (Enabled, Executing, Inputs).

This doesn't happen at all if you use `FromObservable` instead of `FromAsync`. So for [this action](https://github.com/toggl/mobileapp/blob/cfc4dd151d405b03c6c6a2217e2e5f89662d38dc/Toggl.Foundation.MvvmCross/ViewModels/Reports/ReportsViewModel.cs#L474) if instead of retuning a `async Task` you return an `IObservable<Unit>` it works as expected. 

I think it's the way it should have been written to begin with, because you are going from observables to async and back to observables, which makes no sense. But it should work nevertheless.

**Comment by kornelijepetak** [comment]
> I think it's the way it should have been written to begin with

I disagree. 

Many functions are just pure garbage for readability when written in RX and flow easily when async/awaited. So, in this sense, I am ok to use `FromObservable` whenever the observable is actually simple and readable.

For other cases, with conditional awaits and other sorts of stuff, I think we should use `FromAsync` **which is why** we should definitely find out why it's glitching with `FromAsync` (if that is the problem at all, and not maybe something in the action itself).

Also, from what I've read, @Odrakir, please note that `.ToObservable` (that we are using differs in our `FromAsync` extension method) differs a bit in behavior from `Observable.FromAsync` (not ours, the one in the RX lib). One of them is doing `Defer` under the hood, cha. You are much smarter with RX to actually deduce if that could have anything to do with this, so please do.

https://stackoverflow.com/questions/34931053/observable-fromasync-vs-task-toobservable

**Comment by khoi** [comment]
> This doesn't happen at all if you use FromObservable instead of FromAsync

I'm having the problem even when using `FromObservable`? 

- Checkout `cae70d0a` 
- Go to Login screen
- Hit Forgot Password (the button is binded to a UIAction constructed using `FromObservable`)
- Hit Back to go back to the Login screen
- The Forgot Password button is now unresponsive.

**Comment by kornelijepetak** [comment]
So it is either a problem in the RxAction itself, or in the BindAction, or in both... 🤦‍♂️ 
Now we know even less. 🤷‍♂️

**Comment by Odrakir** [comment]
@kornelijepetak I don't have time to discuss this right now, if you want we can do it some other time. But I'm talking about that specific method, not generally observables vs async. In that method we come from an observable and then we send values to subjects. It all could be simplified by using only observables.

**Comment by kornelijepetak** [comment]
I somehow missed the link and thought that you're talking only about that action. (even though I'm sure it applies to some others as well). If that's the case, I agree with your statement. This one would indeed be better with observables.

Thanks for the clarification.
