### ISSUE TITLE
Investigate: iPad Support

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3981]
Specifically, I'd like a cost-benefit analysis.

Please gather information on:

benefits
- how many users are requesting this
- what kind of influence this may have on our rating
- any other benefits?

costs
- how much of the UI needs adaptation at this point (maybe make a list?)
- do we need any designs? (which?)
- how many develop weeks will the necessary changes take?
- how much effort/time will it take to test these changes?

side effects
- are there any downsides? (landscape on iPhone?)
- how can we ensure that iPad compatibility gets maintained as we make changes to the app in the future?
- how much effort/time will it take to continue maintaining it?
- how much effort/time will it take to test this? (for every release?)

Lastly, weigh the collected information, and make a recommendation.

**Comment by Odrakir** [comment]
# Benefits

## How many users are requesting this?

Intercom throws 189 results (searching "iPad" or "tablet"). Users are complaining about the app not working properly on iPad and being only in portrait mode.

According to guys in support this is probably the third most requested feature after widgets and being able to control the app from the notification tray. But given those requests are also including (or even exclusive to) Android I'd say iPad support is probably the most requested feature for iOS users.

## What kind of influence this may have on our rating?

20 out of 690 reviews mention the word "iPad". Some users consider this is reason enough to give us 1 star. That's without counting the ones not leaving any text (just a bad rating) or the ones not even using a non-iPad app. I think rating can only improve if we add an iPad version. How much? Is really hard to say, but we are doing pretty good in terms of rating, so I wouldn't expect a great change.

## Any other benefits?

The paths or Apple are inescrutable, but the more we integrate into their system the more likely they are to feature us. If not that, at least the app will appear in a better position for App Store searches from the iPad, which will probably lead to more downloads.

Split mode in iPad comes almost for free once we add iPad support, and that's a completely new feature that would improve a lot the user experience.

# Costs

At first this only requires a couple of changes to the Info.plist. Then there is the design changes I'll describe next.

It's also worth noting that once we add support for iPad it's not possible to remove it without completely deleting the app from the store and creating a new bundle id.

### How much of the UI needs adaptation at this point. Do we need any designs?

In my opinion most screens, if not all will need some small touches to the design. Most of them do work as they are, but I think a designer would like to make some changes to margins and sizes of some elements. Specially when showing action sheet like controllers (the ones that come from the bottom but don't cover the whole screen),those look pretty weird when going from side to side in iPad in landscape mode, they could be easily fix just by making them not take the whole width. The same happens with login/signup. These changes are obvious and easy to make.

The screens that are not working properly right now are (I'm attaching some screenshots):
- Onboarding. The proportions of the dummy device on screen are weird (unless that's what we are going for) and the text gets missaligned when changing orientation.
- The wheel view. The proportions make it so it doesn't fit the screen
- Everytime we try to show an Alert controller the app crashes. This is because they require a location on the screen in iPad. Should be easy to fix. It happens when exiting the edit view or changing workspaces from reports.
- Reports: The pie chart won't fit in the screen when in landscape.
- Calendar: Apparently there's some kind of problem with the layout both on landscape and portrait.

## How many develop weeks will the necessary changes take?

Just adding the necessary entries in `Info.plist` and making the minimum changes so this doesn't crash and it looks "okeish" in every screen would take 1 dev aprox 1 week.

To do it right, as mentioned before, we would need a designer + at least one dev to go over every screen. I'd say 3 weeks aprox., given the designer and the developer can overlap.

## How much effort/time will it take to test these changes?

The whole app would have to be tested in both orientations, with and without split view and it also should be tested again in iPhone, as some bugs can be introduced.

But this is only visual, we won't be changing any logic, so I'd say it'll be easy to test. Maybe a couple of days is enough?

# Side effects

## Are there any downsides? How can we ensure that iPad compatibility gets maintained as we make changes to the app in the future?

Orientations are independent for each device, we'll allow every orientation in iPad while only allowing portraint for iPhone, there's no problem there.

As mentioned before, some bugs can be introduced in iPhone's layout after these changes. But once those are fixed everything should work fine from then on. Apple provides some nice ways of creating universal layouts without much hassle.

## How much effort/time will it take to continue maintaining it?

We will develop the interface using what they call size classes, which makes it easy to adapt the interface to different devices or different window sizes within iPad. So we won't have iPhone and iPad specific layouts but one single layout that adapts to every size and orientation.

The effort of this, while bigger than doing it only for iPhone, is not much. Device sizes and screen resolutions are still very constrained and Apple tools make this pretty simple.

## How much effort/time will it take to test this for every release?

UI Tests should help with this. Still, some more testing will have to be done, of course. Although, as I said, the idea is writing the layout not for each device, but universally, so if we follow some rules testing for one device should mean that it also works in others.

# Conclusion

In my opinion given the interest users show for this and the fact that the app will be a better Apple ecosystem citizen (App Store and on device), the benefits are much greater than the costs, so we should definitely go for it. Wether we do it now or after tackling some other user requests (widgets) that's a whole other question and I guess the whole year planning has to be taken into account for it.

But we should also consider that every new piece of UI we add before making the app support iPad is one piece of UI we'll have to adapt later. Where as if we do it after adding support for iPad, we'll just have to follow the layout conventions to make it work.

# References:
[Adaptative layout](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/)
[Designing a Universal App](https://medium.com/capitalonedesign/designing-a-universal-app-657ff67b2095)

# Screen shots
![simulator screen shot - ipad pro 10 5-inch - 2018-12-24 at 16 25 41](https://user-images.githubusercontent.com/724743/50403248-5642f780-079d-11e9-93f4-66624bdd02bc.png)
![simulator screen shot - ipad pro 10 5-inch - 2018-12-24 at 16 24 09](https://user-images.githubusercontent.com/724743/50403249-5642f780-079d-11e9-8308-38f6dc519a60.png)
![simulator screen shot - ipad pro 10 5-inch - 2018-12-24 at 16 23 45](https://user-images.githubusercontent.com/724743/50403250-5642f780-079d-11e9-9998-d5776bbbe73e.png)
![simulator screen shot - ipad pro 10 5-inch - 2018-12-24 at 16 23 10](https://user-images.githubusercontent.com/724743/50403251-5642f780-079d-11e9-96ee-93be5d187feb.png)

**Comment by amulware** [comment]
Requesting review of the above by @dshr (and anyone else's comments are welcome too obviously).

**Comment by dshr** [comment]
This pretty much sums up my findings after go-loco week, it's not too hard to implement and maintain, while earning us plenty of bonus points. 

@Odrakir did you get a chance to look over `shingeki-no-ipad`? All my initial changes are there.

**Comment by Odrakir** [comment]
@dshr I did not. Anything you want to point out about it? Should I go over it before we begin implementing this?

**Comment by amulware** [comment]
It would be good to know how much of that work we can use and whether this influences the estimated time to finish the conversion.

**Comment by Odrakir** [comment]
Sure, I was asking for what specific changes were made just so I didn't have to compare both versions. But I just took a look at the commit history and I see it more or less touches the areas I mentioned up there ☝️. So yeah, the code in that branch should at least be looked at before we do anything.

But in any case I think design should come first and then we'll be able to tell how much we can reuse.

**Comment by amulware** [comment]
I'm closing this. We decided to go forward with iPad support!
