### ISSUE TITLE
RxFactor the SelectProjectViewModel

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#4012]
Check #3352 for details

**Comment by simonrozsival** [comment]
This issue is quite complex. The problem is that it's not enough to just refactor the VM and the VC but it is necessary to also refactor the table view source and the autocomplete suggestion cells and this is a problem. There is overlap with the start time entry view and it gets really messy.

I think that either an experienced person in rxfactoring must do this (not me) or we need to discuss this in more detail and split into smaller issues.

I'm unassigning myself now, because I don't think I'm able to finish this in time for 1.17 on my own.

**Comment by dshr** [comment]
I've been having similar troubles with #4013. Following @khoi's approach with #3600 helps, but yeah, there's plenty of rxfactoring to go around.

**Comment by simonrozsival** [comment]
I must admit that I have very little knowledge of how the table view sources work and I am always confused by how complex they are. It should be just a collection or a wrapper around a collection with a specification how to render each of the items based on its type (mapping of the items to cells).

We have so much non-xplat logic in there.. we trigger commands from the view sources and we have non-trivial layered bindings there and whatnot. Maybe it would be better to try to create new abstractions next to the old ones and see if we can learn from the current codebase and create something simpler and more straightforward.

**Comment by dshr** [comment]
Idk about Android, but with iOS and Xamarin the datasource doesn't just handle the cell rendering, but also has all the methods a `UITableViewDelegate` normally has, so the situation might be limited by Xamarin itself.

**Comment by arturs105** [comment]
Work for this PR should be done (or based on) `des/rx-select-project` branch, since it contains the RxFactored view model, iOS bits and tests.
