### ISSUE TITLE
Start TE: Add an existing tag

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4175]
Sign in
Start time entry
Assign tag
Save entry
Stop entry
Successful sync status displayed?

**Comment by heytherewill** [comment]
In order to assign an existing tag, I'd need to create it first, and the only ways of doing so would be:

1 - Open the start view, create the tag, remove the tag and then add it again
2 - Open the start view, create the tag, close the start view, open it again, add the tag

Which one would you rather have in the test?

**Comment by ApocalypticFish** [comment]
I'd rather have you go through the whole process of creating an entry and tag. Stopping the entry. Then create a second entry with that existing tag or project. Is that feasible?

**Comment by heytherewill** [comment]
Sure thing!
