### ISSUE TITLE
App crashed after adding tags and entering edit tag view again

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4201]
App crashed after adding tags and entering edit tag view again

## 🐛 Bug Report
Added 2 tags in edit view
Pressed done
Entered tag edit view again and app crashed

## Context
First time opening the app in 10 hours

Build/Branch: 1.10
Phone OS: Android 8.0.0
Phone model:HTC U Ultra

## Expected behavior
Should have been able to enter the edit view again

## To reproduce
open app
app is signed in
edit time entry
edit tags
created 2 new tags "mandarin" "laptop"
press done
then enter tags again
app then crashed
attempted to reproduce and it didn't occur again.

**Comment by kornelijepetak** [comment]
I can confirm that this happens every once in a while, but I have not found the exact steps that would reproduce this consistently.

**Comment by kornelijepetak** [comment]
I've been checking this thing. 

It is quite possible that this bug will disappear when GTE is introduced as I have changed quite a lot in Edit TE and the way tags are displayed.

Verdict: I don't think it's wise to hold onto this issue for too long since
• it is possibly solved by GTE
• it can't be consistently reproduced.

For now, I will close the issue and let's either create a new one with consistent repro steps or open this one again if we see that this bug persists even after GTE is merged.
