### ISSUE TITLE
Allow for same-name Projects to be created if assigned to a different Client

### ISSUE THREAD

**Issue by zdericnina** [toggl/mobileapp#4237]
## ⛑️ User Support

User is attempting to create Projects with a same name but different Clients in the mobile app. The app doesn't currently allow this so it throws an error. They are usually using the desktop app which allows for this behavior so they wished they can do the same on the go.

## Expected behaviour

Creating Projects with the same name but a different Client should be allowed

## To Reproduce

1. Create a Project that already exists in the Workspace but add it to a different Client
2. It will show an error “Sorry, this name is already taken”.

**Comment by khoi** [comment]
This issue is fixed in #4380. However, it's not very intuitive for the users because they have to:

- type in a non-existing project name, so the suggestion creation cell is at the top.
- In the create TE view, rename it to the correct name.

we might need to update the behavior in the create TE view as follow. 

![](https://cl.ly/6a51d469c112/Image%202019-02-12%20at%2014.32.43.png)

pinging @amulware and @zdericnina

**Comment by amulware** [comment]
Yes, we need to update that - to always show the create button, as long as the user has at least one workspace that they can create projects in.

Please create the issue yourself or do it as part of this one. ;)

**Comment by maritoggl** [comment]
Go ahead, @khoi, the proposal makes sense and will likely resolve the issue users have ahd.
