### ISSUE TITLE
Refactor table view sources and table recyclers

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4319]
We need to refactor tables because we want to get rid of Mvx and make tables reactive. We also want to add more features like the grouped time entries. Currently our code isn't very flexible and it is quite hard to make any changes to it (especially for complicated tables).

We identified that we have 2 different types of tables:
- ones which are reloaded whenever data changes
    - simple tables, where data never changes (e.g., date format, workspaces)
    - tables, where you can filter the data (e.g., countries, clients, tags)
    - additionally these tables can be nested (when they are grouped by workspaces or by projects)
- ones where changes are animated
    - right now that is just the main view
    - potentially this could be other views as well

In both cases foundation should provide whole list of items (which could be nested) and it is the table views responsibility to either just reload the table, or diff it with the previous version and display the changes somehow. Foundation should not emit the changes too often (for example when we process data while syncing) but it should always show only the last version so we can animate everything at once.

In the end we should have just 4 (abstract) generic classes:
- for reloading tables
    - for flat lists
    - for nested lists
- for animating tables
    - for flat lists
    - for nested lists

 There might be some other classes for use cases like an extra prepended cell for creating entities or for supporting multiple cell types or something like that.

 Ricardo will be working on the reloading tables (some Android guy might help him with the Android part). Kornelije and Simon will work on the animating tables as part of the grouped TEs project.

**Comment by Odrakir** [comment]
Some comments:
- I think from Foundation's point of view there are only two types of collections: Flat lists and nested lists. Both will be Observables that emit the whole list every time there's a change. Then it's in each platform where we decide if that change needs to be animated and do the diffing.
- We could even have just one type of collection: Nested (as a flat list is a nested one with only one section and one level)
- I think for Nested lists we should stop at 2 levels to keep things simple. If more levels are needed those should be part of the item view model properties, but we don't necessarily need a structure to hold any number of levels (things will get complicated fast otherwise)
- Giskard already has diffing, so all we need to do there is send Observable collections and they'll do the flatting and update the view accordingly.
- Daneel needs diffing for the animated table views to update properly.

**Comment by kornelijepetak** [comment]
> I think for Nested lists we should stop at 2 levels to keep things simple 
I think it's keeping it complicated.

I believe an abstraction of _node_ would make more sense. 
However, since I can find only one single case of 3-level nesting (few weeks ago I thought we're never gonna go more than 2 levels 🤦‍♂️), I can go with this. The issue I see with this is that the flattening algorithm always has to be tailored to each specific use case. With generic _node_ system, only one flattening algo would work for all use cases.

Not pushing anything, just saying.

**Comment by kornelijepetak** [comment]
> Main timeline view with sections for each day and grouped time entries is 3 levels, right? Although I still think we don't need a generic nested structure with n levels for that.

Yes, it's 3 levels. Like I said, it's the only foreseeable structure so I am ok with keeping things less generic if it will make things easier 😄

**Comment by kornelijepetak** [comment]
Since this whole thing will be flattened on platform, I want the flattening to be generic and independent of the specific use cases and it should take care of all the index manipulation. My desire is to have the setup where there would be 

```
ANY DATA       ->    Flattening    ->    RecyclerAdapter
-----------          ----------          -----------------
[ViewModel]          Platform*           one for all cases
```

The index calculation for `GetCell` and such things should be a generic algorithm derived from the tree flattening so that no specific math is needed for any new kind of table view.

If the flattening is done in platform code, then I don't care if it's a tree structure on the Foundation level as long as it's easily (and generically) flattened.

The goal in the end is that only the foundation level would have to be different for each platform. The genericness of the remaining of the pipeline would in ideal case be as generic as possible.

**Comment by simonrozsival** [comment]
Just to make sure we don't forget about it - we have another 3-level structure which is already in the app: `workspaces > projects > tasks`

**Comment by sofokli1** [comment]
We could drop the iOS sections, headers etc. and go for an approach like android where everything is a cells. (one for sectionHeader, one for TE, one for groupTE) This should in theory increase the shared code that would otherwise be split per platform. So the flattening could be shared. The only thing missing will be the diffing on iOS (but this is needed regardless of this approach).

**Comment by Odrakir** [comment]
I don't think that's a great idea for iOS. If you drop sections you loose sticky section headers. And also, iOS table views are designed to work with sections, there's no problem there. I think the current planned approach where Giskard flattens the collection is better.

**Comment by kornelijepetak** [comment]
I agree with @Odrakir. Let's not kill features platforms give us. The solution @simonrozsival proposed, containing the idea of sections and items (while items can also be sections with items) works both for iOS (with native sections) and Android where we'll just flatten things out.

**Comment by sofokli1** [comment]
forgot about the sticky headers 🤦‍♂️

**Comment by amulware** [comment]
This doesn't seem relevant anymore.
