### ISSUE TITLE
Track no-default-workspace case

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4344]
I'd like to track how often it occurs that users have workspaces, but do not have a default workspace set.

Please check that this event won't accidentally be triggered in the no-workspace case (which should set the default, but I'm not sure if it does or relies on the no-default-handling to do so).

Also please include a property that tells us how many workspaces the user has. If it is 1, we know that the default is assigned automatically, otherwise, they see a dialogue to choose it.

**Comment by amulware** [comment]
Actually, it turns out we track this. Can we please still make sure that all the comments above are taken into account?

**Comment by amulware** [comment]
I said above that we track this, but I can't actually find where. Can someone help?

**Comment by heytherewill** [comment]
The tracking code is as follows:

```csharp
public IObservable<ITransition> Start()
    => dataSource.User.Get()
        .Select(user => user.DefaultWorkspaceId.HasValue)
        .Do(trackNoDefaultWorkspaceIfNeeded)
```

This will only trigger during sync (After the `refetchInaccessibleProjects` step) and when the user has no default workspace set. Not sure if it can trigger when the user has no workspaces (ping @simonrozsival) but I think that's the case, since there's a `DetectNoWorkspace` step that run earlier and throws if there are no workspaces.

Also pinging @amulware for confirmation on what to do next. I think this issue can be closed :)

**Comment by amulware** [comment]
> Also please include a property that tells us how many workspaces the user has. If it is 1, we know that the default is assigned automatically, otherwise, they see a dialogue to choose it.
