### ISSUE TITLE
Option to hide archived projects while choosing a project in a task

### ISSUE THREAD

**Issue by cperezabo** [toggl/mobileapp#4412]
## ⛑️ User Support
When you create a new task and select a project, archived projects a still being displayed! so you have to dig into old projects to find the desired one.

## About the user
Just a user trying to get a nice app for 10 USD/month

App version: 1.17 (2477)
Phone OS: 12.1.4
Phone model: iPhone 8 Plus

## Expected behaviour
To have a "toggl" button to switch between displaying or not displaying archived projects in the list while choosing a project for a new task

## To Reproduce
Archive a project, create a new task, tap to choose a project and type the archived project name or its client and the project will be listed.

## Suggestions
Give the change to show or hide archive projects (hidden by default).
Nice solution: in the projects list view.
Simple solution: a global setting (show archived projects: on/off)

No Workaround, just swimming among tons of old projects

**Comment by amulware** [comment]
Thanks for taking the time to create such a detailed issue, @cperezabo!

I agree that how things are at present is not ideal.

We intend to not show archived projects in that list at all (since 'archived' means that the project is no longer relevant). Unfortunately, our API has some limitations that make this difficult to easily do at the moment.

The current workaround I can offer you is to logout and back in. That will clear the local database (make sure you don't have any unsynced data), and not pull archived projects from our servers again.

I fully understand that this is not an ideal solution, and I hope we will be able to fix this so the workaround won't be necessary in the future.

I'm closing the issue, not because it's not important, but because we're tracking this problem already internally. Thanks again!

**Comment by cperezabo** [comment]
I am paying for the service. You cannot tell me just "sorry, wait for some point in the future when we will get it fixed"
