### ISSUE TITLE
Choose duration when creating time entry

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#450]
Requires: #446

Note that the duration dialog has to work slightly different compared to the one in the edit dialog.

Obviously (I hope) choosing a different duration modifies the start-time of the entry to be created.

**Comment by willsb** [comment]
If we choose duration during creation, it means we're creating a TE rather than starting it. Is this correct? We will only have a single button for adding Time Entries and depending on whether or not the Stop date is set (via the duration) we will either create or start a time entry?

No objections on this regard, just questioning because right now every other app has a manual mode instead of using the same insertion mode for both things

**Comment by amulware** [comment]
Choosing duration when starting simple means that the entry is running with a start date in the past.

We won't have a manual mode or anything like it for now.

**Comment by willsb** [comment]
Just to confirm and making this explicit: This is only different from #451 because of the way we select the Start Date, right?

**Comment by amulware** [comment]
They are two different dialogs, that work in slightly different ways, though the effect is very similar, yeah.

**Comment by pe0ny** [comment]
Duration icon: 
<img width="40" alt="screen shot 2017-09-13 at 08 47 43" src="https://user-images.githubusercontent.com/5064445/30361541-3da6c182-9860-11e7-86f2-19baad39d6d9.png">

Also, updated zeplin file (the icon was hidden for some reason..): https://zpl.io/VDz0Ggb
