### ISSUE TITLE
iPad version: Start TE

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#4506]
- Max height on larger screens
- KB behaviour
- Confirm button on larger screens
- Closing action sheet to appear from the close button centre on larger screens

**Comment by sofokli1** [comment]
@dshr  I am trying to do the popover for the confirmation to delete a TE. The issue i am facing is related to the position and arrow of the popover. in the designs we want it like this:
<img width="378" alt="Screenshot 2019-03-13 at 12 58 51" src="https://user-images.githubusercontent.com/885122/54274044-d0f70400-458f-11e9-95f8-d94ff3c4c2a6.png">

but the issue is that the popover is called from the VM and the VM and we need that (x) button instance and a frame (we can use the button bounds). We need to import UIKit to foundation for that. An easy alternative would be to have it centred. like so:
![Simulator Screen Shot - iPad Pro (11-inch) - 2019-03-13 at 13 02 33](https://user-images.githubusercontent.com/885122/54274256-49f65b80-4590-11e9-8b2e-2174db8ed73f.png)

Also would like to add that the designed popover confirmation is not intuitive to show in the corner at the x button when taping outside the VC to dismiss it. The proposed solution feel better from a UX point of view in my opinion.

To conclude, based on our time constrains it would make sense to settle for the simpler solution and have the design solution as a future feature since it would end up requiring changes in an otherwise shared between platform abstraction that is `IDialogService`.

What do you think?

**Comment by dshr** [comment]
Yeah, I guess trying to attach it to the close button is indeed not worth the effort. The lone "Discard" button looks a bit off though, is there a chance we can add a message to the action sheet? Like, by checking the SizeClass in `DialogServiceIos` using the `topViewControllerProvider` and then changing the `selectTextByType` function to return more than just the buttons?

**Comment by sofokli1** [comment]
Sure we can, but what should it say?

**Comment by dshr** [comment]
Something like "Would you like to discard this time entry?" should work. Ideally we should ask @maritoggl about this though (ping).

**Comment by sofokli1** [comment]
at the moment in the PR it looks like this
<img width="461" alt="Screenshot 2019-03-13 at 18 15 36" src="https://user-images.githubusercontent.com/885122/54295626-17625800-45bc-11e9-9164-f22049f0e15b.png">

**Comment by lizaPlotnikova** [comment]
☝️ Copy seems fine to me. Solution also good
