### ISSUE TITLE
iPad version: Settings

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#4511]
- Make this screen fullscreen again
- Change back button to "back" again
- Enforce max width on wider screens

**Comment by sofokli1** [comment]
How about having the settings like a popover? ![pop-over_2x](https://user-images.githubusercontent.com/885122/53886149-06e43780-4028-11e9-8037-2ac95c830023.png)

**Comment by dshr** [comment]
It messes with navigation a lot, since we're presenting fullscreen views from settings. Re-arranging that navigation stack every trait collection change would be a bit of a nightmare.

**Comment by sofokli1** [comment]
My idea is to have the settings view wrapped in a navigation controller. The rest of the views that are opened from the settings do not need any changes since it will be in a navigation controller already. The only change will be on how we show the settings VC itself. If phone keep as is, if pad wrap in navController and show in popover. What do you think?
