### ISSUE TITLE
Siri: Fix message and UI for entries with empty description

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#4538]
The message says "You've been doing for { TIME }", so it's missing what I've been doing.

The UI shows just the time with nothing to the side, we should probably put some kind of placeholder?

![img_44e6c6b3432b-1](https://user-images.githubusercontent.com/724743/53896630-ad363a00-4034-11e9-9618-bd854d7c99cd.jpeg)

**Comment by khoi** [comment]
we probably should define another response in the intent definition for this.

**Comment by lizaPlotnikova** [comment]
Heya – I spec'ed a different response when there's no description available in the copy review issue https://github.com/toggl/mobileapp/issues/3382;

>Success: "Stopped. You've tracked time for ${entryDurationString}."

IF possible add functionality to open Edit TE view for the TE on click. Then, let's put the placeholder text "Add description" in the UI (it should be the placeholder grey, #CECECE).

Otherwise, if it isn't possible to open Edit view. The placeholder text should say "Without description".
