### ISSUE TITLE
Consider replacing `LogItemViewModel.Identity` with a function

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4578]
Our IDs use hash codes and there could potentially be collisions which would lead to crashes or undefined behavior (depending on platform).

The idea is to remove the `long Identity { get; }` from the `IDiffable` and replace it with `bool RepresentsSameItem(IDiffable other)` which would do whatever is necessary to determine whether it is the same item or not (even if the contents is different/updated).

There is a potential problem with the custom diffing algorithm which internally uses dictionaries indexed by the `long Identity`, but it should be easy (and still performant) to replace the key with anything implementing `IEquatable<T>`.

**Comment by simonrozsival** [comment]
Internal discussion: https://toggl.slack.com/archives/C02APMYTM/p1552031731759000

**Comment by Odrakir** [comment]
As I said in Slack using `bool RepresentsSameItem(IDiffable other)` would imply many changes in the Diffing algorithm because of dictionaries. I'm not even sure if it can be done.

An easier an equally valid solution is to replace
`long Identity { get; }`
with
`string Identity { get; }`

Or any other type that is IEquatable, but `string` works and we don't need to complicate it any further.

**Comment by kornelijepetak** [comment]
> As I said in Slack using bool RepresentsSameItem(IDiffable other) would imply many changes in the Diffing algorithm because of dictionaries. I'm not even sure if it can be done.

If that is the case, I'd rather purge `Identity` from Foundation then, as it slowly becomes the iOS thing (because of the diffing). Android can work with any kind of comparison and while comparing IDs for entities with IDs makes perfect sense, I wouldn't like surrogate identity with strings for those that can't. I'd rather use IEquatable on droid side.

But this is definitely something that needs to be tackled on a app-wise level, not for grouped time entries specifically.

I don't even think this issues should be related to Grouped Time Entries at all.

**Comment by Odrakir** [comment]
I'm not sure if this is clear or not, because I said it may times: The diffing (in both iOS and Android) needs two types of comparisons:
- Check if an item is the same as another item (even if some of its components have changed)
- Check if an item has changed and needs updating (being the same item)

For the first one we have Identity, `IEquatable` makes sense for the second one.

According to @daividssilverio , in Android you'll have:
`bool areItemsTheSame(int oldItemPosition, int newItemPosition)`
`bool areContentsTheSame(int oldItemPosition, int newItemPosition)`

While we could add a custom implementation to those methods to check for Identity (first method) and Equality (second method). Isn't it just easier to have `Identity` in Foundation and make it the same for both platforms? That way we just check the Identity property for the first method and Equality for the second one.

I think it's the easiest solution, and it'll be the same for both platforms so the behaviour will be very similar too.

**Comment by kornelijepetak** [comment]
There is no confusion about the two whatsoever. So no need to reiterate on this anymore.

But! I have said it many times as well: 😄 

Identity may not be trivial (or even simple) and often times can't be conflated to a single primitive. Unless that primitive is a surrogate string identity in which all elements of an identity are concatenated or otherwise combined into a string. And unless it is absolutely necessary, I will always fight against surrogate string identities.

There are two problems with strings. One is that all strings are interned, taking more memory. And if you want to calculate them instead of cache them, they are slow to generate. And regardless of the first choice, case string comparisons are much slower than comparing multiple primitive values in a composite identity. Comparisons used in the diffing algo have to be as fast as possible.

The only thing I will not be against (if iOS really can't work without primitive identities) is that there are all three elements:

`bool AreItemsTheSame`
`bool AreContentsTheSame`
`string Identity`

So, in this case would not use Identity, but instead the two methods because of memory/speed.

**Comment by Odrakir** [comment]
In my opinion it makes no sense to calculate Identity in the UI for iOS, mainly because the Diffing algorithm should be independent. I think that is fine where it is right now: In Foundation when the collection is being created.

Then you can choose to ignore it from Android if you'd like. Your call, but I don't think it's worth it: Performance and memory shouldn't be concerns with this amount of data, and if they ever are we should worry about them then (something about premature optimisation).

I also don't think we'll any have problem encoding the data with have into strings. But if that is bordering you we could always use a custom type as Identity as well. Any type can do. But I strongly encourage to do the same for both platforms.

**Comment by kornelijepetak** [comment]
> But I strongly encourage to do the same for both platforms.

Me too.

And if it's about being able to put a key into a dictionary, I'd be fine with something like:

```cs
interface IDiffable<TElement, TKey> where TKey : struct
{
    TKey Identity { get; }
	bool HasSameContentsAs(TElement other);
}
```
so that both platforms use the same thing.

But like I said, I think we need to take more things into consideration for this. This is not a 🔟 issue.

**Comment by Odrakir** [comment]
Why not use `IEquatable` as it is (instead of  `HasSameContentsAs`) and `IDiffable` just for the `Identity` (I would call it `IIdentifiable`, but that's already taken)?

Also, 🔟 has some potential problems with diffing as it is right now, doesn't it?

**Comment by kornelijepetak** [comment]
> Why not use IEquatable as it is (instead of HasSameContentsAs) and IDiffable just for the Identity (I would call it IIdentifiable, but that's already taken)?
🤦‍♂️ yes, that is true.

> Also, 🔟 has some potential problems with diffing as it is right now, doesn't it?
With my solution (which is also dirty) we will not run into issues as long as the IDs generated by our backend are auto-incremented. It is dirty, however, because it's using the `long` to store three different things. So, it's ugly, but has to be refactored in the future.

But I don't want to postpone release of 🔟 as it will be some time while we reach a conclusion on this. For now, this solution will work.

**Comment by simonrozsival** [comment]
I think that what we need is this:
```csharp
interface IDiffable<TElement, TKey> : IEquatable<IDiffable<TElement, TKey>>
    where TKey : IEquatable<TKey>
{
    TKey Identity { get; }
}
```

We can safely use this `Identity` as a key of a dictionary and therefore we will work well for both platforms. We can create a struct which will be used for matching entities. Is there something I am missing?

**Comment by kornelijepetak** [comment]
I think that's alright 😄

**Comment by Odrakir** [comment]
Can't `IEquatable` just be `IEquatable<TElement>`?

**Comment by simonrozsival** [comment]
You are probably right, Ricardo.

**Comment by kornelijepetak** [comment]
He is not probably right. He is right.

**Comment by simonrozsival** [comment]
I think I found a way to reproduce a problem with diffing which is most likely caused by the way we identify cells:
![image](https://user-images.githubusercontent.com/374616/54121194-1c77a980-43fa-11e9-9edc-dd943fb3d834.png)

- create a group of time entries
- delete them one by one, don't delete the first time entry
- once there is just 1 time entry left, sometimes it will be shown correctly (without the group number), but sometimes the old (2) will be kept in the row (the header will be matched with the row, because we use the ID of the first time entry to identify the group).

**Comment by simonrozsival** [comment]
Fix was merged into the project branch.
