### ISSUE TITLE
Edit time entry: the wheel view is shown instead of "select date" view

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4645]
This was lost in the rxfactoring - when the user taps on the start date, he/she should be able to open the small modal for changing dates, but instead we show the wheel view. Now the wheel view is shown for everything - start, end, duration, and start date 😄 apparently this is a bug.

**Comment by kornelijepetak** [comment]
Before you go beserk on this issue, you should know that (unfortunatelly) there are differences between Android and iOS here and those should be taken into account.

In some way, I think the _right_ design is Androids because it allows easy solution to time entries that are longer than 24 hours (which may or may not be rare). That's why on Android both Start and Stop times are actually combinations of `date + time`. 

Hence the reason why it eluded me that iOS was behaving differently. Also, the old ViewModel had code for both iOS Wheel and Android start/stop/duration selection screen which was messy because each used their own commands. When I was replacing those with the wheel, I obviously missed this thing when I was merging and firing the commands (now Actions).

In any case, make sure not to *CHANGE* behavior, but add what you need for `iOS`. Android is supposed to work like this (i.e. all taps should lead to the wheel). This is because Android does not have a picker that can choose date AND time on the same screen.

### IOS

![image](https://user-images.githubusercontent.com/7033216/54332815-3c88b200-4620-11e9-9977-c4ef5c31141f.png)

### Android

![image](https://user-images.githubusercontent.com/7033216/54332869-6d68e700-4620-11e9-93b8-1a16624ab5a2.png)

**Comment by simonrozsival** [comment]
I closed the issue by accident.

There is nothing easier than fixing the binding on iOS and leaving Android as it is :-)

**Comment by simonrozsival** [comment]
A fix was merged into the project branch.
