### ISSUE TITLE
Main log lost basic support for the screen reader

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4653]
## ⛑️ User Support
User reported that since Daneel 1.17 the Time entries collection on the home screen is no longer accessible to the voiceover screen reader for the blind. He said it was working great before 1.17. 

When I was replicating it, the voiceover would just repeat *the Time entries collection* but wouldn’t actually “register” the time entries. 

## About the user

App version: `1.17`
Phone OS: `iOS`
Phone model: not important

## Expected behaviour
The screen reader can read out individual rows in the log.

## To Reproduce
Use screen reader.

## Suggestions
This might be because of https://github.com/toggl/mobileapp/commit/4845cafdee8f7beb6ceb4b398a903a7f5b7cfa05, but I'm not 100% sure about that.

**Comment by amulware** [comment]
We can do this soon if it's not too much work. If this requires some significant changes, it's not worth it right now.

**Comment by amulware** [comment]
If it's more complicated, let me know and I'll unschedule it.

**Comment by arturs105** [comment]
Unfortunately i didn't manage to make a PR for this issue, but i did (hopefully) solve this.

The problem was that the main table view had an accessibility label and accessibility was enabled for it. That's why the screen reader wasn't registering the cells as separate items, but the whole view as one. To fix that i set accessibility as disabled for the table, so the screen reader wouldn't register it. 

As a bonus for people who use the screen reader i made it so that it can read each time entry row with the description and the project. I did that by overriding `AccessibilityLabel` property in `TimeEntriesLogViewCell`.

But we use accessibility labels for UI tests, what about `TimeEntryRow` label? No worries, i switched to using accessibility ids and the tests work fine.

Doesn't accessibility have to be enabled for UI tests to work? No, i ran a UI test with accessibility disabled on a view and everything worked fine.

Unfortunately lot UI tests then failed for unrelated reasons (#4670 and #4680). Once those PRs are merged, the tests should pass fine and the screen reader fix should be good to go.

My work can be found on branch `arturs/fix-screen-reader`
