### ISSUE TITLE
Investigate iOS and Android Widget infrastructure

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4743]
We need answers to questions such as:

- What are the general possibilities of widgets on the two platforms? How much/long can we run code? HTTP requests? Access the apps data?
- Can we share code between the widgets? Can the widgets share code with the apps?
- Anything else you can think of that may be relevant.

This will help us scope the upcoming widget project realistically, and help us know whether we can implement the same solution for both platforms, or should split this into two entirely different projects.

Deadline: April 19. Happy to get answers earlier though. 😊

**Comment by juanlaube** [comment]
Both platforms are completely different from a technical and UX perspective so I will break down things for each one. That being said, the features should be very similar for both apps.


## iOS

#### How widgets work?

Widgets are called today extensions in iOS. Those are app extensions, pretty much like Siri or share extensions, and therefore are their own independent process.
An app can host multiple widgets that can be added to the Today view (i.e: swipe left on the iPhone home screen) and only one of them can be shown when doing a 3D touch press on the app icon (when supported).


#### Updating the view

The system will take snapshots to cache the content frequently, this snapshot is visible when the widget is visible again before updating the contents in `widgetPerformUpdateWithCompletionHandler:`.
The widget, as any other app extension, does not share data with the container app unless we put it in the same app group. We will need the already existing ExtensionKit (with some small changes probably) to share data between the host app and the widgets.


#### Design considerations

The layout can have two display modes, compact or expanded.
The layout size in compact mode is fixed and is the size used when the widget launches from the 3D touch action or it's just added to the Today view.
We need to specify the height we're gonna use when switching to the expanded mode, but there are no other limitations.

The widget is contained in a vertical scroll view, so scrolling should be avoided.
Text input is not supported.


#### Other technical constraints and considerations

Only one instance of a widget is allowed at the same time.
As most app extensions, memory usage is limited to 16 mb (this could have changed in recent iOS versions).
Some APIs are not available (like camera, microphone, etc) but I don't see this being a problem.
It's possible to make HTTP requests from the widget.
We can share code through a class library if needed.


#### Useful links

https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Today.html



## Android

#### How widgets work?

Widgets provide customization to the phone home screen. Unlike iOS, where widgets are contained in the Today view, it's possible to add Widgets in Android to any panel in the home screen.
Widgets have two parts in Android, a provider (any app that provides a widget) and a host (basically the launcher). We will do the provider part only, but it's important to be aware of the host part because the implementation changes between different manufacturers.

Unlike iOS, widgets are not independent processes, they are part of the app, but the system caches a remote view in the home screen, even if the app is not running.


#### Updating the view

Widgets are BroadcastReceivers, this means they can be updated any time by sending intents from the app.
The widget will also force an update of it's content when created, on a configurable time interval or when the device is booted.


#### Design considerations

Widgets are placed in grid in the home screen and offer more customization options than iOS:
- It's possible to have multiple instances of the same widget at the same time
- Widgets can be resized in both directions (if we allow it), the layout can change depending on the size
- There's a special kind of widget that can be configured in an activity before adding it to the home screen

The UI elements on the widgets are limited though, while the things we can use is probably enough, we cannot subclass those UI elements, or provide our own.
Because widgets live in the home screen, interactions are limited only to taps and vertical swipes, any other kind of gesture is forbidden.


#### Other technical constraints and considerations

Because the widget lives as part of the app, we can do anything we want, from reading and writing data, sending http requests, etc.
As with iOS, we can share code through a class library if needed.


#### Useful links

[Widgets overview](https://developer.android.com/guide/topics/appwidgets/overview)
[Building Widgets](https://developer.android.com/guide/topics/appwidgets/index.html)
[Designing Widgets](https://developer.android.com/guide/practices/ui_guidelines/widget_design.html)


## MVP and other ideas

I think the MVP should be a widget to start/stop time entries, and show all the running time entry info we can if there's any (i.e: project name and color, client, tags, duration, etc). In the future we can add more widgets like reports, the calendar view or some sort of daily summary.

**Comment by juanlaube** [comment]
cc @maritoggl
