### ISSUE TITLE
Project Creation Cell behaves weirdly on Android

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#4822]
when user has many projects, the creation cell is shown at the very top, out of the scroll view's bound, which requires the users to manually scroll up to see it.

See the video and pay attention to the right scroll bar
https://khoi-screenshots.sgp1.digitaloceanspaces.com/Untitled.mov

## Context
Giskard latest `develop`

**Comment by arturs105** [comment]
I think you've posted the wrong screen recording.

**Comment by khoi** [comment]
oops, link updated

**Comment by kornelijepetak** [comment]
I've played with this a lot and I can't reproduce on current `develop` this behaviour on the real device. I believe this might be a simulator issue because of the weird way the Android handles soft input. But I can see consistent behavior:

* When the filter text is not empty, it hides `No project` and shows `Create project XY`
* When the filter is empty `No project` is shown and `Create project XY` row is no longer visible.

**Comment by juanlaube** [comment]
I can't reproduce either, tested on the emulator and a real device.

**Comment by khoi** [comment]
I've just reproduced it again, and noticed, the creation cell is there at the very top, but I have to manually scroll to top to see it.

**Comment by kornelijepetak** [comment]
Here's what's the problem.
The `Create Project` label is just a regular row in our table and is always shown at the beginning of the list.
The current behavior is actually totally correct from the RecyclerView scrolling perspective, although not desired.

Here's what happens:
• Open project selection with lots of projects.
• Scroll down to half of the list
• Type in something in the filter and this adds `Create project` label to the beginning of the list.
• However, since the list is already scrolled down, the table *shows the previously visible element at the top*, which is expected behavior.
• So the behavior is correct.

In the case of this reported issue, the steps were like this:
• Lots of projects
• 1st item is the topmost visible item
• Typing into filter adds a `Create project` label
• 1st items is still the topmost visible item (because the suggestion was added before it)

So the behavior is actually in line with how recycler view works. 
⚠️ Although, iOS's tableview has a different philosophy (which makes sense) - if the first item is the topmost visible element, and you add items to the beginning of the list, it will show them (since they are now becoming first items in the list). For some reason, Android does not do that.

So we have two solutions.

1. Stick with my solution proposed in the #4979. In that solution, whenever the filter updates, the view is scrolled to the top so that `Create Project XYZ` is visible. However this resets the scroll.

2. Extract that row and promote it to special view, but this requires _a lot_ of work both in shared code, and in both platforms. This is proposed as #4986 .

From internal conversations, we have decided that it will probably be good that we implement 2 at some point, but not at this particular moment because it requires changing both platforms and the shared code. However, since this will be done in the future, it is proposed to stick with 1 for now. (which is not the best possible scenario). In this scenario, we can live with scroll reset for a few weeks until we change this into consistent (and better) behavior.
