### ISSUE TITLE
Clocked Hour Chart doesn't reload first day of week settings

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#4873]
## 🐛 Bug Report
When the first day of the week setting updated, the bar chart doesn't get updated. It's only updated when users relaunch the app.

## Context

Build/Branch: `develop`
Phone OS: 12.2
Phone model: iOS

## Expected behavior
The bar chart should reflect the new setting change.

## Suggestions
This could be happening on Android as well, I haven't checked.

**Comment by amulware** [comment]
Does it not update even if you re-confirm the time interval by selecting the shortcut from the reports calendar popup?

**Comment by arturs105** [comment]
After a bit of investigation, i'm starting to think, that this isn't really a bug and here's why:
1. You open the reports and select some 7 day period, so 7 bars with day of week initials appear in the bar chart
2. You go to settings and change the first day of the week setting
3. You go back to the reports
4. The bar charts still start with the same day of week label as previously, **which is not wrong, because the same date range is still selected**

However, there is 1 thing that we should fix:
#### "This week" label in the toolbar only works, when Monday is the beginning of the week
1. Have beginning of week set to ~the correct value~ Monday
2. Go to reports and select "This Week" quick shortcut
3. The navigation bar shows "This Week" as it should
4. Now go the settings and change the beginning of the week setting to something else
5. Go back to reports and select '"This Week" shortcut again
6. The correct dates according to start of the week are selected, however the navigation bar does not display "This Week", instead it shows a date range (it should show "This Week")
7. Now manually select the date range of the current week as if it was starting on Monday. The navigation bar now shows "This Week" again

It's like it is hardcoded to only handle Monday as the beginning of week. That is something we should fix.

Now what about the case, when user selects "This Week" quick shortcut and then goes and changes the beginning of week setting? I think we should not change the selected date range. Instead, we should update the navigation bar label from "This week" to a date range representing the selected period, since the definition of "this week" changed.
