### ISSUE TITLE
Update empty state for suggestion view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#513]
See zeplin for details.

**Comment by pe0ny** [comment]
**Welcome screen: for new users**
- [ ] New users should see this welcome screen after they sign up: https://zpl.io/aX136Kb
- [ ] Show it until user has created his/her first time entry

![toggl - ios - timer welcome screen 1x](https://user-images.githubusercontent.com/5064445/30327088-791c7e38-97d3-11e7-83b8-5ea64389739f.png)

**Empty state: for existing users**
- [ ] Show this screen to existing users who haven't tracked their time for 6 weeks: https://zpl.io/anQG7kV (We decided to fetch 6 weeks old data because it's decent history for auto completion and suggestions)
- [ ] Show this until user creates another time entry

![toggl - ios - timer empty state 1x](https://user-images.githubusercontent.com/5064445/30327141-ad87caf6-97d3-11e7-9aa2-2ca7ccb3a5ba.png)
