### ISSUE TITLE
App freezes after resuming from background

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5221]
## 🐛 Bug Report
Reported by @amulware. When resuming from background after a few minutes (> 10 minutes) and pressing the stop button, sometimes the app freezes and nothing responds after.

## Context

Build/Branch: `develop`
Phone OS: iOS
Phone model: Any

## Expected behavior
The app shouldn't freeze

## To reproduce
1. Open `AutomaticSyncingService.cs`
1. Edit `MinimumTimeInBackgroundForFullSync` to `TimeSpan.FromSeconds(5)`
1. Start a time entry 
1. Go to background
1. Resume after 10 seconds
1. Press the stop button
1. :bug: Sometimes the app completely freezes

**Comment by heytherewill** [comment]
I can reproduce this bug on develop. This was not introduced by `mvexit`. I edited the bug description to reflect this.

**Comment by juanlaube** [comment]
I don't know the cause yet, but I noticed that in `ObservableDataSource.cs`
```
public override IObservable<TThreadsafe> Update(TThreadsafe entity)
            => base.Update(entity)
                .Do(updatedEntity => UpdatedSubject.OnNext(new EntityUpdate<TThreadsafe>(updatedEntity.Id, updatedEntity)));
```
if I comment the `.Do` line, then the problem is gone. Something is subscribing to `DataSource.TimeEntries.Updated` and somehow blocking the app.

**Comment by juanlaube** [comment]
I'm gonna remove myself to focus on actual mvexit issues, anyone can work on this.

**Comment by juanlaube** [comment]
I ran out of ideas trying to find the source of this bug. I will remove myself from this and let someone else work on it.

**Comment by amulware** [comment]
Just for reference:
- I'm getting this specifically on 2.0 (mvexit testflight build), several times a day, and did not get it before upgrading to this
- I just got the same, except instead of stopping I started from a suggestion, after force quit and restarting, that time entry is there, just like the time entry is stopped, so the app is definitely responding to the tap, and freezes after persisting new data
- from how often this happens to me (several times a day), this seems like a major issue and needs addressing asap

**Comment by juanlaube** [comment]
Moving this to Daneel 1.22 since it happens in `develop`.
