### ISSUE TITLE
Fix activities leakage

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#5272]
## What's going on?
While checking the fragment's lifecycle for our custom made framework.
I've enabled Android's Strict mode and stepped upon some problems.

One of them is that it seems that we are leaking activities references. I tried but could not find exactly how, just that it's happening, it wasn't introduced by #4999, the problem being present in develop before that.

## How to replicate
To verify this, please enable droid's strict mode using:
```
StrictMode.SetVmPolicy(
                new StrictMode.VmPolicy.Builder()
                    .DetectActivityLeaks()
                    .PenaltyDeath() <-- if you want the app to crash when a leak happens
                    .PenaltyLog() <-- if you just want to see a log when it happens
                    .Build());
```

before `OnCreate` in the `TogglApplication`.

## Why would we care?
Leaking activities impact the app's overall performance, making the use more memory than it should; It also makes the app a bad neighbour, being possible to impact the system overall, since we are holding resources the system might use otherwise.

## Hints
Fixing this involves some investigation. I suggest profiling the application while the leaks happen, taking a heap dump of the app's memory allocation to check where references might be being held. It wasn't fruitful to me, but hope we can use it to some extent. Otherwise, we can go by trial and error to stop the problem... :c

Tools recommended to help profiling: AndroidStudio's Profiler and VisualStudio Xamarin Profiler (only available on Enterprise Edition+, @heytherewill might wanna take a look).

**Comment by pdrj** [comment]
I need to park this task for now, so here are my findings so far.

As you can see in the attached heap dump analysis, we don't seem to hold these leaked activity references in any of the classes we own - for instance `ReactiveActivity` doesn't appear in the dumps. To further prove that our reactive stuff doesn't cause leaks, I first commented out everything having to do with it from the activity I've been testing with. The leak was still there. I then even made the activity inherit just from `AppCompatActivity` rather than `ReactiveActivity` and the leak didn't disappear either.

This makes me think that it is maybe some sort of framework bug which is causing this. To investigate this further, I removed all the code setting up the menus from the activity (`OnOptionsItemSelected`, `OnPrepareOptionsMenu`, `OnCreateOptionsMenu`) and actually for two test runs I've not seen leaks, but then they started appearing again (with that code still commented out)... Not sure what caused the fix in those two cases then, as it's not reproducible.

If someone wants to do testing, the easiest way to profile the memory I've found is through Android Studio, as described [here](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/profiling). Most recent versions of AS don't have the 'Analyzer tasks' tab anymore, so if you like some help with automating the search for leaked activities, you can either download an older AS version and open an exported heap dump there, or use [Shark](https://square.github.io/leakcanary/shark/) - this is the tool I used to generate the attached txt reports.

![Screenshot 2019-08-02 at 11 48 58](https://user-images.githubusercontent.com/53510080/62363925-8ff09380-b520-11e9-8b80-09b9ffbedbdd.png)
![Screenshot 2019-08-01 at 13 09 16](https://user-images.githubusercontent.com/53510080/62363958-a696ea80-b520-11e9-8aa5-0681a0f029e6.png)
[analyze3.txt](https://github.com/toggl/mobileapp/files/3460786/analyze3.txt)
[analyze2.txt](https://github.com/toggl/mobileapp/files/3460787/analyze2.txt)

**Comment by daividssilverio** [comment]
That's similar to the result I came with when trying to find the source of the problem.
I'm starting to think it could be something `Xamarin` related.
Thanks for the findings and reports @pdrj, we'll have to keep on investigating this.

**Comment by heytherewill** [comment]
Turns out I was able to reproduce the behavior with a very small application, so I'm putting this `on-hold` for the time being and we will come back to it once we hear back from Xamarin
