### ISSUE TITLE
Retry syncing of time entry after user edits them

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#532]
This might already happen if the edit view overrides the sync-status to 'needs syncing'. Still, make sure this works as intended please.

**Comment by simonrozsival** [comment]
When a time entry is marked as "unsyncable", its `SyncStatus` is set to `SyncFailed`. Therefore it will not be pushed to the server, as only the time entries with `SyncNeeded` status are chosen.

After the entity is edited, the status is set to `SyncNeeded` no matter what it was before. Therefore the entity will be chosen for a push when sync is triggered.

Nevertheless I will make a functional test once the UI shows which time entries are marked as unsyncable and which are not.

**Comment by simonrozsival** [comment]
I tried this and it works as I described in the previous comment (tested on branch `sync-icons`). I am not sure what the flow of closing this issue will be - it doesn't make sense to create a PR, because there is no need to write any code. Should I now unassign this from myself and you will review it and close, @amulware? Or is my report enough for closing the issue?

**Comment by amulware** [comment]
If it works, we can just close this.
