### ISSUE TITLE
Suggestions: Have a small delay when suggestions are triggered

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5381]
Add a small delay (2sec) when suggestion are triggered so that the suggestions do not change constantly during sync.

**Comment by kornelijepetak** [comment]
The reason this is happening is the fact that we are not subscribing to the sync process, but to the data changes, particularly the `ObserveWorkspaceOrTimeEntriesChanges` interactor.

Here's a more detailed take on the problem.

At the moment, whenever time entries get created/changed, and the data gets stored to DB via data sources, the `ObserveWorkspaceOrTimeEntriesChanges` _emits_. That way, the suggestions recalculation is tied to the local data, and not to the sync process itself. This is fine if we want the suggestions to work in local-state mode (i.e. networking issues, airplane mode or otherwise no internet). It will also work even if syncing process fails at whatever point, not able to update all data that needs to be updated.

However, we have recently [decided to not include unsynced time entries](https://github.com/toggl/mobileapp/issues/5339) int the suggestions process at all, so we would not even use that data for suggestions. That makes the tie to the data changes invalid/useless, except maybe in the case where some items get correctly synced and some not.

However, if we went with tying the suggestions recalc on the event of transitioning the sync to `sleep`, then partial syncs would be fine and at least include into suggestions recalculation those TEs that actually got synced. This would require ditching this interactor (this is the only place where it's used) and make another one that taps into sync process.

So, some decisioning seems to be in order.

> IMO The small delay, as proposed by the issue is trivial to implement, but may not be a correct solution. Tapping into sync directly could be better, but am I seeing things clearly?

**Comment by sofokli1** [comment]
If we tap into the sync only, would we get a trigger after starting a TE (either start button, continue button or suggestion tap)?

My thinking was that changes to the data incapsulates sync as well as local changes into one way of observing. The machine learning approach uses the previous 2 TEs when calculating the project. So having the info from the latests data change (creation, edit or delete) should trigger recalculation since the data has changed and the correlations between that data and other unchanged data has also changed. Does this make sense

**Comment by kornelijepetak** [comment]
But if you look at current code, you will see that not even ML algo takes into account data that hasn't been synced. So it will not take those until sync is done with them.
If we wanted both local changes and sync state changes, we need to remove that no-sync filter. (#5339)

**Comment by sofokli1** [comment]
completely forgot about those. since we removed those, it makes sense to decouple from the data WS and TE changes and connect to the sync directly. That should take care of the fast changing suggestions.

**Comment by kornelijepetak** [comment]
Just a mention that the PR introduce a throttle of `500ms` instead of `2s` as proposed in the issue.

**Comment by sofokli1** [comment]
2 sec seemed too long since most frequent fire situation happen in very fast succession, it look slow on UI due to ML recalculation, so I reduced it to 0.5sec. Felt like a good mix of thresholding and not much delay for the end user.
