### ISSUE TITLE
[Discussion] Provider name/copy on suggestions

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5503]
As #5426 suggests, we could decide locally which suggestions providers to favor based on the user's usage across time.

However, if we ever enable turning some suggestion providers on/off it'd be useful for users to have a very thematic and reasonable labels about it in settings so as not to refer to those as providers (being too techy-techy term), but instead give options like:

* App will suggest tasks based on your history (ML provider)
* App will suggest imminent or recent calendar tasks (Calendar provider)
* App will suggest tasks you do the most (most-used provider)

Another thing that is currently in place is that in DEBUG and ADHOC builds, the description is prefixed by the first 4 letters of the provider, for us just to see what provider is the source of those suggestions. Truth be told, calendar one is easy to spot, as it has no projects or other annotations, only description. But we are sometimes unsure about the two remaining ones so we introduced these debug strings.

However, my question is whether it makes sense to add something onto the suggestion items as well, in production (that will serve the same purpose), so we can discard some debug code from our codebase.

An icon or a single-word label defining where the suggestion is coming from. It might be an UI/UX nightmare (as we already have issues with space), but it's something I'd like considered for future reference.

**Comment by heytherewill** [comment]
I really like being transparent about where the suggestion came from. It will help users figure out things by themselves. I'm a huge fan of this sort of customization and we've already seen users saying they don't want any suggestions at all, so allowing them to customize the number of suggestions and which providers to use is an idea I dig quite a lot and marking which suggestion came from which provider is a nice touch.

I think adding a dot (similar to the dot we used to indicate project color) at the top right of the suggestion card is a pretty clear way of indicating the provider that originated it. OFC it doesn't have to be a dot (since this could be mistaken for a project), it could be a different icon and if the user long presses the icon we could show a toast that says what that icon means.
