### ISSUE TITLE
Pie chart text is upside down on the right

### ISSUE THREAD

**Issue by lise-toggl** [toggl/mobileapp#5511]
## 🐛 Bug Report
_This is not really a bug_ - the current design of the pie chart means text labels on the right side appears upside down.
![image](https://user-images.githubusercontent.com/50156618/60413008-bc11af80-9c16-11e9-96c6-2ded087d2245.png)

## Context
iOS 2.0.1, Android 2.0.1 - reports page

## Expected behavior
It would be nice if the text always appeared right side up :)

## To reproduce
Create a report with four equal project durations in the app. The top right slice's text will be upside down.

## Suggestions
[Slack](https://toggl.slack.com/archives/C029WU7AY/p1561444620161300)

**Comment by amulware** [comment]
I think I concur with this, each slice should compare the two angles of its sides and select the one that points 'more up' to show the text on.

**Comment by pdrj** [comment]
I'm mostly done with this issue. There's one scenario that I'm not sure about:

![better](https://user-images.githubusercontent.com/53510080/65049066-733fdc00-d965-11e9-885d-8f562669e16e.png)
![better2](https://user-images.githubusercontent.com/53510080/65049067-73d87280-d965-11e9-8f1a-9b0e4d31cc79.png)

Don't mind the extra padding for the items on the right - it's been already removed.

How do you think the 'bhh' entry from the screenshots be displayed? I'd say it should look like on the second screenshot. @amulware, since you participated in the slack thread, or @maritoggl, would you like to weigh in?

**Comment by amulware** [comment]
The first one to be point symmetrical with where the text is at the top - that being said, it's virtually impossible to get this case unless people enter their time entirely manually and in multiples of 15, 30, 60 minutes, or similar. So I'd really be happy with either.

**Comment by maritoggl** [comment]
As @amulware said ☝️

**Comment by pdrj** [comment]
Ok, the first one it is then :) Thanks.

**Comment by amulware** [comment]
Wait! Actually, shouldn't we put the text on the other side of the slice? for those on the right? (That's what I suggested above.

Like this:

<img width="545" alt="Screenshot 2019-09-17 at 16 16 17" src="https://user-images.githubusercontent.com/3987892/65055177-9fa82800-d966-11e9-8347-810c89d52298.png">

Or maybe even try and get names pointing left/right as much as possible? Like that:

<img width="547" alt="Screenshot 2019-09-17 at 16 17 45" src="https://user-images.githubusercontent.com/3987892/65055279-c4040480-d966-11e9-8879-eb1f547f0dc0.png">

**Comment by pdrj** [comment]
Yep I read your suggestion, but I didn't like that then you have these labels right next to each other, rather than spaced evenly. With more slices that might not look good I think (you'll have some labels next to each other and some not). This also applies to the second suggestion.

With six slices for instance, my solution is pretty symmetrical (screenshot below).

Please let me know if what I propose is OK with you, or would you rather stick to one of yours.

![6](https://user-images.githubusercontent.com/53510080/65055890-447b3300-d970-11e9-9789-9766365c0259.png)

**Comment by amulware** [comment]
I'm ok with yours if @maritoggl is.

**Comment by maritoggl** [comment]
Your arguments are valid, do proceed :)
