### ISSUE TITLE
Remove ripple effect from non-interactive UI elements

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5558]
### Problem

Ripple effect has been added by (#5534) to username/email fields even though those UI elements are not interactive. 

This issue is deemed resolved by removing the effect from those fields.

### Reasoning

The [material design](https://material.io/design/interaction/states.html#pressed) states that: 
> _Pressed states are initiated by user keyboard or voice input on an interactive element._

 And also:
> _This state applies to all interactive components._

If an element does nothing when tapped, it is not an interactive element at all.

**Comment by heytherewill** [comment]
I don't have any strong opinions about this, but Google does the ripple in the Android settings app even in lines that have are not interactive. Google doesn't follow their own guidelines in many a place, so I'm not sure if that counts 😄 

If a test-weeker is to work on this issue, feel free to speak up about whether or not you think this issue is correct and why

**Comment by kpv1993** [comment]
As Will said, Google doesn't follow their own material design in the settings which is true as I checked. But when someone clicks and a ripple comes then the user expects something to happen. So I believe it is better to remove the ripple animation.

**Comment by heytherewill** [comment]
Closes by #5728
