### ISSUE TITLE
Make sure we are compliant with Android policies prior to August 1st

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5565]
The email I've received from Google.
We need to research and adjust what we can.

> Hello Google Play Developer,
> 
> By **August 1, 2019**, all apps that use native code **must provide a 64-bit version** in order to publish an update. As of the sending of this email, at least one of your apps does not yet meet the requirement: **Toggl: Time Tracker and Timesheet for Work Hours**
>  
> *Action required!* Please review all of your apps for 64-bit compliance and submit your updated apps by August 1, 2019. The [Android developers guide](https://developer.android.com/distribute/best-practices/develop/64-bit) provides step-by-step instructions for assessing the use of native code and becoming 64-bit compliant, including identifying native libraries, building with 64-bit libraries, testing and publishing.
> 
> Please note that we are not making changes to our policy on 32-bit support. Google Play will continue to deliver apps with 32-bit native code to 32-bit devices. The requirement means that those apps will need to have a 64-bit version as well.
> 
> If you have any questions or concerns, please contact Google Play developer support.
> 
> *Note: This list of apps reflects Google’s best estimate as of the sending of this email. Only the top apps in your account are listed. This list should not be considered exhaustive. We encourage you to review ALL of your apps for native code and make sure 64-bit variants are offered where necessary. A full list of exemptions to the August 1st deadline [can be found in our blog post](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html).

**Comment by juanlaube** [comment]
### Action required
We don't have to do anything. Based on the information provided [here](https://devblogs.microsoft.com/xamarin/64-bit-requirements-xamarin-android-apps/) and [here](https://developer.android.com/distribute/best-practices/develop/64-bit), we are already 64-bit compliant because we support all the available ABIs.

### Why did we get this e-mail?
I don't know exactly, but I guess it could be because we support all those ABIs using multiple APKs, and some are 32-bit only.
