### ISSUE TITLE
Get rid of Firebase Performance

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5637]
## 🚧 Refactor Proposal
Xamarin has just admited that [they will not support this library properly](https://github.com/xamarin/GooglePlayServicesComponents/issues/151#issuecomment-514289605). It took them almost a year, but at least we can now part our ways with it.

Also, as @amulware found out in Buenos Aires, there are some issues with the code that measures a couple of things, so it'll be a win-win.

## Dependencies
Supersedes #3542 if we decide to go through with this

## Technical aspects
Literally just get :fire: the whole `Toggl.Core.Diagnostics` folder and then make the app compile again :sogood:

**Comment by amulware** [comment]
A win-win by removing all performance measurements, even those that actually work?

I'm missing the part explaining why we don't need performance measurement, or what we will do to replace this.

**Comment by Redth** [comment]
Since you linked to our repo's issue I figured it's worth commenting here as well.  It's since been discovered that _some_ parts of Performance are working in the basic binding (there's some configuration issues we are planning on working around regarding the way AndroidManifest.xml's from the .aar's in the bindings get merged incorrectly).  

My comment about dropping the nuget was perhaps a bit premature, and we aren't going to actually do that now that we know there are some useful parts of it without having to totally reverse engineer and reimplement whatever the firebase perf gradle plugin is doing on the java side.  We have no plans to invest in _that_ work but we'll keep maintaining the API surface of the binding as it's updated, so feel free to use whatever functionality that provides (looks like it can still track network calls, app events, etc).
