### ISSUE TITLE
Fix missing iOS translatable items

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#5770]
I found some strings views that still have their text fixed in the xibs, storyboards, cells, etc:

Let's fix them:

- Fix CalendarSettingsTableViewHeader: "Toggl needs access to your calendar in order to display events."
- Reports Calendar Month/Year
- Settings Siri "Shortcuts"/"Workflows"
- Login/SignUp Email/Password hints
- Navigation "Back" on settings
- Calendar settings user calendars sections
- Calendar ui labels when editing a time entry, it shows PM/AM only. Maybe this isn't fixable :thinking:

**Comment by dshr** [comment]
### Fix CalendarSettingsTableViewHeader: "Toggl needs access to your calendar in order to display events."

This is generated by iOS, and we have no control over it 😩

### Reports Calendar Month/Year

Currently waiting for https://github.com/toggl/mobileapp/pull/5784 to be merged and then we'll do a similar thing. Problem is that on iOS we're using attributed strings for this, so the conversion might be a tad problematic.

### Settings Siri "Shortcuts"/"Workflows"

These are loaded via .json. We'll have a set of .json files, one for each language. Currently WIP.

### Login/SignUp Email/Password hints

The code is correct, but the placeholders don't update. It's a mystery that is still WIP..

### Navigation "Back" on settings

Done, part of `des/ios-i18-fixes`.

### Calendar settings user calendars sections

These are also done via iOS, so we have no control over them.

### Calendar ui labels when editing a time entry, it shows PM/AM only. Maybe this isn't fixable 🤔

Done, part of `des/ios-i18-fixes`. A lot of other time labels were incorrect as well, which were fixed in the same commit.

**Comment by dshr** [comment]
Closed by #5787
