### ISSUE TITLE
Investigate Sign In with Apple

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5786]
I'd like us to investigate [Sign In with Apple](https://developer.apple.com/sign-in-with-apple/).

Please gather as much information as we can below. Specific questions I'd like answered are:

- [x] When will this feature be available?
- [x] When will this feature be mandatory if at all?
- [x] What do we expect we'll have to do to support it? From our side, and from the backend side.
- [x] How will this affect other clients? Can we support it on the web? Desktop? Non-Apple platforms?
- [ ] Could this be implemented in some bigger 'oauth support' initiative or would this be a totally separate feature?

I want enough information for us to make decisions on when we want/need to implement this, and what scope might make sense in terms of support from our other apps, etc.

**Comment by Odrakir** [comment]
## What gives?

- Built-in two-factor authentication support
- Anti-fraud detection
- One-touch, frictionless means of entry into the app -> More signups?
- Give the user the guarantee that the app isn't sharing any user information
- Users can also choose whether or not to share their email with the app developer (Apple will generate a random and redirect emails, the user can choose to disable it anytime)
- The developer only receives the user’s name associated with their Apple ID, the user’s verified email address — or the random email address that routes email to their inbox, while protecting their privacy — and a unique stable identifier that allows them to set up the user’s account in their system.
- Works on all Apple devices
- There's a JavaScript based SDK for Android, Windows or web

## When will this feature be available?

It's supposed to be available in mid September with iOS 13

## When will this feature be mandatory if at all?

Theoretically it'll be mandatory for all apps offering any third party sign in option at launch. We are offering Google, so it would be mandatory for us. 

In reality it seems a little drastic to me, I'm not sure if people is going to be able to adapt so fast, so who knows, they might give us more time. 

In any case this might be problematic "only" when updating the app, which could lead to a rejection. That's my guess.

## What do we expect we'll have to do to support it? From our side, and from the backend side.

While they don’t explicitly call out OAuth or OIDC in their documentation, they use all the same terminology and API calls. 

From the app it's pretty easy, we would just need to add the capability and include some code to show the button and handle the callbacks (and do the necessary changes to the current flow). Apple will return an email, name, id and token we can use to create the account. Well, that and cross our fingers Xamarin implements this correctly. It's very well documented.

Then we'll need a backend endpoint to convert that info into a session.

## How will this affect other clients? Can we support it on the web? Desktop? Non-Apple platforms?

We will probably need to add this to all clients eventually. What happens if one user signs in with Apple from his phone and then wants to login on the web, desktop or Android phone? There's a JavaScript library for that. I included a tutorial for a web application integration in the references.

# References:

Good overview: https://techcrunch.com/2019/06/07/answers-to-your-burning-questions-about-how-sign-in-with-apple-works/
WWDC video: https://developer.apple.com/videos/play/wwdc2019/706
App side: https://www.spaceotechnologies.com/sign-in-with-apple-ios-tutorial/
Web integration: https://developer.okta.com/blog/2019/06/04/what-the-heck-is-sign-in-with-apple

**Comment by Odrakir** [comment]
Not sure about the oauth initiative...  I guess it could, in terms of what we would need from backend. In the clients themselves, I'm afraid this will probably need to be specific to Apple.

**Comment by amulware** [comment]
Very nice! Pinging @maritoggl so she's aware of these details. My plan was to handle this later this year, but we'll definitely need support from backend, and ideally web/desktop, and product needs to be involved and make decisions as well. (NOT supporting this is a valid decision, but we may then have to remove Google Login in our apps, which would be unfortunate and confuse a bunch of users.)

I'll ping people from all those other teams internally as well. I'll close this issue, we probably want to have the actual discussion about how/when to implement this somewhere else.

**Comment by amulware** [comment]
Internal discussion which also clarifies that this is JWT, not OAuth based: https://toggl.slack.com/archives/CDRNW2N1F/p1566400948058000
