### ISSUE TITLE
The 'Select calendars' screen has no way of choosing no calendars

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5844]
📅 When we open the calendar screen, the following screen appears (albeit with somebody's else's calendars). However, the `Done` button is disabled until at least a single calendar is selected.

⚠ There seems to be no way to cancel this screen besides selecting at least one calendar. They can be turned off in the settings later on, but a cancellation should be possible.

![image](https://user-images.githubusercontent.com/7033216/64521119-b3fd7c80-d2f7-11e9-9e2f-b21e8bc3eb07.png)

**Comment by amulware** [comment]
I believe Android lets you cancel - what does that look like? Generally, adding a label.

**Comment by lise-toggl** [comment]
![image](https://user-images.githubusercontent.com/50156618/64521360-33f90600-d33b-11e9-8ce9-4150d8fee717.png)

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/23578870313)

**Comment by heytherewill** [comment]
This is by design; During the implementation we forced the user to select at least one calendar so they could see how the calendar works. After all, since the calendar is an opt-in feature, it makes sense to force the selection of at least one calendar when onboarding the user.

Nevertheless, if this is to be changed, we should update the notion docs that describe this feature :)

**Comment by amulware** [comment]
Let's see if this is still relevant after the calendar improv projects and what we want to do about it.
