### ISSUE TITLE
Differentiate Project and Tag creation.

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#5933]
Project and Tag creation work differently but look the same. When I tap `+ Create project "popo"` it takes me to a new screen, and I still can cancel the project creation. But when I tap `+ Create tag "popo"` it directly creates the tag (plus I can't edit or delete it, but that's another story)

Maybe it's enough to add `...` after to project creation and show: `+ Create project "popo" ...`, but @maritoggl should have the final word on this.

**Comment by Odrakir** [comment]
By the way, Clients work the same way as Tags.

**Comment by simonrozsival** [comment]
I am not sure how to approach this issue. I can see the argument for unifying the UX, but I don't feel comfortable proposing a solution myself. Maybe this issue shouldn't be included among development issues (I know that if we leave unscheduled or if we just throw it at product, it will probably never get done).

So in order to move this issue forward, an opinion of an amateur UX designer:
- We could in theory create projects with random colors the same way as tags, but then we would have to (finally?) implement editing of projects. It might be even more confusing for the users.
- Adding a confirmation view for the tags and clients doesn't make too much sense, that seems unnecessary.
- We could distinguish these two actions with different wording and with different action icons:
    - For tags and clients, we could use `+ Add client (tag) "XYZ"` - the + and "add" suggests that there won't be any follow up screen
    - For projects, we could use `-> Create project "XYZ"` - the wording stays as it is, but an `->` icon would suggest that the user would be forwarded to another view

Another option would be to try to unify the interface with what the webapp does:
- For tags, it says `Press Cmd+Enter to create tag "XYZ"`
![image](https://user-images.githubusercontent.com/374616/69228708-5782cd00-0b84-11ea-95b2-f3cd24fdb846.png)
- For projects, it says just `+ Create new project` and `Press Cmd+Enter to create a new project` without the name shown and it opens a modal with the searched word pre-filled in the project name
![image](https://user-images.githubusercontent.com/374616/69228797-8600a800-0b84-11ea-998a-f7767397f5a4.png)
![image](https://user-images.githubusercontent.com/374616/69228841-9ca6ff00-0b84-11ea-8335-8162f609c93a.png)
I actually quite like this. It is very simple and we would bring those two apps a bit closer together 😄 

What do you think?

**Comment by simonrozsival** [comment]
There is one more option I should mention:
- leave it as it is right now.

I actually think that unless our users complain about confusion, we shouldn't fix what's not broken and leave it as it is.

**Comment by Odrakir** [comment]
I'm a user complaining! 😛

I think doing the "+" vs ">" would be enough, to be honest.

**Comment by simonrozsival** [comment]
@Odrakir @amulware @maritoggl So what should be the outcome of this issue? Do we want to try changing the icons? Should we talk to our designers and ask them for a new icon?

**Comment by maritoggl** [comment]
Voting for the simple "+" and ">" approach.

**Comment by simonrozsival** [comment]
@amulware said he won't have any input  in this decision, so I think we can close the discussion. We'll ask designers to create a green arrow which we'll use instead of the green "+" icon.

![image](https://user-images.githubusercontent.com/374616/69648653-071bdb80-106c-11ea-93c8-c19162b8dcfa.png)

One last thing: for feature parity, we should do the same on Android. Do you agree, @maritoggl?

**Comment by maritoggl** [comment]
Yes, that makes sense.

**Comment by simonrozsival** [comment]
Great! Tomorrow I will create a follow-up issue with the specs, I'll talk to the designers, and I'll close this issue.

**Comment by simonrozsival** [comment]
I'm closing this in favor of the follow-up issue.
