### ISSUE TITLE
Prevent configuration changes creating a phantom play button

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5938]
Repro steps:

1. Open the app
2. Start a TE
3. Open android settings and change the font size
4. Switch back to our app
5. 🔍 The animation happens for running TE card (it shouldn't)
6. Stop the TE
7. 🔍 The running TE card collapses into a FAB, but one is already visible.

![phantom fab](https://user-images.githubusercontent.com/7033216/65326966-fd30b480-dbb2-11e9-836d-11045744fab2.gif)

**Comment by semanticer** [comment]
Also linking connected bug #5657

**Comment by pdrj** [comment]
I think it's time I post my findings on this and move on.

In short, I can fix it, but not without breaking something else :). I can make it so that there is no extra animation from point 5, and there is no extra fab from point 7. Unfortunately, with this fix, the fab disappears completely to the bottom right corner when you press stop. I could go on with this solution (and probably will in the future), but it has potential of taking many more hours and I don't think it's a good time investment at this point.

There are also several sucky 'fixes' that I found for just the phantom fab:
- surround `SetExpanded` call with a `Post`
- apply throttle for `ViewModel.IsTimeEntryRunning` subscription.

We can also just not care about the config change ;).

Because the sucky solutions from above work, it seems like this might be something related to threading.


Another issue that I noticed during debugging this is that we create the fragment's view twice on config change, which I don't think should be happening:
```
09-25 11:55:09.001 22087-22087/com.toggl.giskard.debug E/xxaa: OnCreateMotionSpec
09-25 11:55:10.521 22087-22087/com.toggl.giskard.debug E/xxaa: saving expanded True 254130018
09-25 11:55:35.926 22087-22087/com.toggl.giskard.debug E/xxaa: restoreFragmentsViewModels mainfrag 410436777
09-25 11:55:35.933 22087-22087/com.toggl.giskard.debug E/xxaa: getCachedFragment mainfrag 66762384
09-25 11:55:35.934 22087-22087/com.toggl.giskard.debug E/xxaa: showInitialFragment initialTabItemId 2131559006 hash 66762384
09-25 11:55:35.969 22087-22087/com.toggl.giskard.debug E/xxaa: on create view 410436777
09-25 11:55:35.969 22087-22087/com.toggl.giskard.debug E/xxaa: InitializeViews 410436777
09-25 11:55:35.978 22087-22087/com.toggl.giskard.debug E/xxaa: got true from saved instance 410436777
09-25 11:55:35.979 22087-22087/com.toggl.giskard.debug E/xxaa: on view created 410436777
09-25 11:55:36.113 22087-22087/com.toggl.giskard.debug E/xxaa: on create view 66762384
09-25 11:55:36.114 22087-22087/com.toggl.giskard.debug E/xxaa: InitializeViews 66762384
09-25 11:55:36.120 22087-22087/com.toggl.giskard.debug E/xxaa: on view created 66762384
09-25 11:55:36.331 22087-22087/com.toggl.giskard.debug E/xxaa: OnCreateMotionSpec
09-25 11:59:46.240 22087-22087/com.toggl.giskard.debug E/xxaa: saving expanded True 66762384
```

the numbers are hashcodes of the main fragment. As you can see, we do all the init for 410436777, but then don't even show it and that is pretty bad.

I also created a pure Android kotlin project to validate that there's no bug in the framework (very unlikely in this case, because googling for our problem yields no results). There is not.

**Comment by amulware** [comment]
Let's give this one more shot, and if we can't fix it, close this issue.

**Comment by heytherewill** [comment]
While the button appears on any configuration changes, the most common ones would be switching to dark theme and changing the orientation. The former does trigger the bug while we ignore the later. That being said, the phantom FAB only appears on the first stop. Subsequent animations of the running TE card don't have the glitch.

With all that in mind, I think it's simply not worth the hassle to use the hacky solutions mentioned here just to fix such a minimal issue (that can likely go away on its own when we refactor some parts of the main view). I'm closing it as will not fix.
