### ISSUE TITLE
Measure what's wrong with our startup

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5953]
Our startup times aren't the best. We've been working on improving things, but we need to do more.

This issue is Android specific, and in it we should list all things that can be improved (be they .NET specific or Android specific) to make our startup as close to instantaneous as possible

To consider this issue closed we should have a writeup on what can be improved and a list of followup issues to fix those things

**Comment by semanticer** [comment]
Are we talking about cold or hor startup or both?

**Comment by heytherewill** [comment]
Both. A writeup on what's making the app slow on both types is what we need :)

**Comment by daividssilverio** [comment]
Roughly, a good deal of the slowness in the startup comes from the time it takes to load and initialize the `MainTabBarViewModel` in the `SplashScreen`. The splash screen taking about 1.6 seconds to load.

On my tests in debug mode, the slowest part in the `SplashScreen` is this snippet, which takes from 800ms to 1.2 seconds:
```
private void clearAllViewModelsAndSetupRootViewModel(ViewModelCache viewModelCache, ViewModelLoader viewModelLoader)
        {
            viewModelCache.ClearAll();
            var viewModel = viewModelLoader.Load<MainTabBarViewModel>();
            viewModelCache.Cache(viewModel);

            viewModel.Initialize();
        }
```
Interesting enough, when removing the initialization of that view model, the splash screen still took at least 800 ms to finish its work in general.

The time spent in the `TogglApplication` isn't too bad, roughly 400 ms in my debug tests.

I'll be running another set of tests using an adhoc build.

**Comment by daividssilverio** [comment]
I'm not happy to have spent a lot time doing these measurements because it looks like the runs's times were all very similar... maybe a single run would've been enough...
But the tables bellow summary the situation:

TogglApplication Times

| Trace | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 |
| --- | --- | --- | --- | --- | --- |
| EnsureInitialized | 93 ms | 93 ms | 97 ms | 93 ms | 93 ms |
| AppStart | 319 ms |  266 ms | 262 ms | 260 ms | 259 ms |
| OnCreate | 483 ms | 431 ms | 430 ms | 424 ms | 425 ms |

| Trace | Avg | % |
| --- | --- | --- |
| EnsureInitialized | 93.8 ms | ~21% |
| AppStart | 273.2 ms | ~62% | 
| OnCreate | 438.6 ms | 100% |


SplashScreen Times

| Trace | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 |
| --- |  --- | --- | --- | --- | --- |
| ClearViewModels | 1351.7 ms | 1364.2 ms | 1365.3 ms | 1362.9 ms | 1363.2 ms |
| OnCreate | 1672.6 ms | 1665.9 ms | 1682.2 ms | 1667.4 ms | 1668.9 ms |

| Trace | Avg | % |
| --- | --- | --- |
| ClearViewModels | 1361.5 ms | ~81% |
| OnCreate | 1671.4 ms | 100% |

MainFrag Times

| Trace | Avg | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 |
| --- | --- | --- | --- | --- | --- | --- |
| OnCreateView | 220.8 ms | 223.3 ms | 213.3 ms | 225.2 ms | 222.2 ms | 220.0 ms |
| OnViewCreated | 641.8 ms | 630.5 ms | 649.0 ms | 640.7 ms | 645.2 ms | 644.0 ms |

| Trace | Avg | % |
| --- | --- | --- |
| OnCreateView | 220.8 ms | ~25% |
| OnViewCreated | 641.8 ms | ~75% |
| Total | 862.6 | 100% |

**Comment by daividssilverio** [comment]
So, In conclusion:

### TogglApplication
The time to startup the application itself isn't taking too long, roughly **438** ms. If we are to target improvement in this area, I suggest we take a look further into this block: https://github.com/toggl/mobileapp/blob/b563c40bc539ae2a65eb8552e478cc8656435bf0/Toggl.Droid/Startup/TogglApplication.cs#L40-L57

Not sure if we can improve much `EnsureInitialized` method. But that's something we can look at later.

<hr/>

### SplashScreen
You can see that the `MainTabBarViewModel` is taking a long time to load and initialize in the `clearAllViewModelsAndSetupRootViewModel` method.
https://github.com/toggl/mobileapp/blob/b563c40bc539ae2a65eb8552e478cc8656435bf0/Toggl.Droid/Startup/SplashScreen.cs#L80-L87

It takes about 81% of the time spent in our `SplashScreen`. Please not that there are more variables in play here and simply reducing that time won't make our splash screen load in 300 ms. I've tried removing the `MainTabBarViewModel` load and initialization completely and simply loading the layout of the `MainTabBarActivity` and the `SplashScreen` still took around 800ms to load for some reason.

<hr/>

### MainFragment
As you can see, the main fragment takes about 860 ms to appear. The inflation and initial view binding (as in `FindViewByIds`) seems to be alright, taking about 220 ms to finish.

Now, the code run `OnViewCreated` takes a whopping **641.8 ms** to finish... which doesn't make much sense unless something is being triggered immediately after being bound and blocking the UI thread.

We can certainly improve that by lazy binding those views (as in binding `ViewModels` to views).

<hr/> 

_PS: Tests run on a Galaxy S8._

**Comment by daividssilverio** [comment]
Finally, I just want to say that a lot of our problems can be solved by lazily loading and initializing our view models. 
Showing placeholders while we locate and initialize the view models will make our activities and fragments load times be composed mostly by their layouts inflation times.

So #5946 and #4423 are the way to go!

**Comment by semanticer** [comment]
Is this sufficient @heytherewill ? Should we close this issue or save the output somewhere else or..  ?

**Comment by heytherewill** [comment]
Since the dependency to #5946 and #4423 has been stated, I'm closing this
