### ISSUE TITLE
Merge suggestions, time entries and rating in a single list 

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#6083]
As of right now, the main log on Android is composed by:

- The recycler view to display the time entries
- A header that is also a recycler view, creating nesting
  - This made sense when suggestions were horizontal
- Some logic to inject a new item when we want to show the rating view

This leads to all sorts of rendering weirdness, because:

- Nested RecyclerViews simply don't play well
- The main recycler view gets weird update everything messages when it wants to show the rating view
- It's tricky to reason about whether the logic is right or not
- Everything looks very flashy during startup

We should refactor this whole infra to be a single list where all components inherit from a base type, this way we can simply treat everything as a single list (which it is) and make items easier to update.

@Odrakir says that iOS doesn't need it that much but that he is not opposed to implementing it, so given how much benefit android will get this should be done properly, in the shared layer

**Comment by juanlaube** [comment]
I tried to do this refactor with the idea of not breaking a lot of things in mind, and failed.

In Core.UI I introduced a base `MainLogItemViewModel` and a `MainLogSectionViewModel`, added a subclass for the suggestions, `SuggestionItemViewModel` and made `TimeEntryLogItemViewModel` conform to it too. Also the `MainViewModel` has a new property, `MainLogItems` that combines both time entries and suggestions into a single collection (needs tests!).

The problems come on the platform side, `MainRecyclerAdapter` in Android is not prepared to work with an heterogeneous collection of sections and items, and this is were I failed, but fortunately it's the only subclass of the `ReactiveSectionedRecyclerAdapter`, so I would just discard all that and start over.
Instead of having sections and items in this new adapter, I would just have a wrapper for flattened list item (similar to the existing `FlatItemInfo`) that knows if the wrapped element is a section or an item, and it's view type (suggestion header, suggestion item, day summary header, time entry item, etc).

I didn't have much time to check the iOS side, but things seem to be easier there because the table view is prepared to work with multiple sections already, the problem is making sure the diffing continues to work with the heterogeneous collection of items.

My progress is in a branch named `main-log-refactor` if you want to continue from there.

**Comment by semanticer** [comment]
This took longer than I expected but my attempt is almost finished now in `wip-main-log-refactor` it's a continuation of @juanlaube 's `main-log-refactor`.  
I still need to:
- Fix the design a bit 
- Fix rating view
- Fix not working TapSubjects
- Cleanup
- Tests?

**Comment by semanticer** [comment]
iOS label remove and separate iOS UI issue created https://github.com/toggl/mobileapp/issues/6639
