### ISSUE TITLE
Fix AppStore/PlayStore Bitrise builds

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6150]
### The Problem
Since https://github.com/toggl/mobileapp/pull/6091 we are now generating version numbers for `Release.iOS.AppStore` and  `Build.Release.Android.PlayStore` based on `ios-*`/`android-*` release tags. The works well when bitrise is triggered by tag but it fails when you just trigger build based on some branch. Bitrise is not pulling tags in that case and therefore can't find any for version number generation. More about this issue here https://github.com/bitrise-steplib/steps-git-clone/issues/78

### The Solution
As suggested in https://github.com/bitrise-steplib/steps-git-clone/issues/78#issuecomment-375337498 we could simply add bitrise step for pulling all (or only `ios-*`/`android-*`) tags and everything should work the same way it does with the tag-triggered builds.

**Comment by semanticer** [comment]
@amulware also voiced some concerns around some kinds of builds that are probably not solved by this?

**Comment by amulware** [comment]
There is two kinds of builds that will be problematic right now:

1. Builds to see if it's building at all. We build these nightly and sometimes manually, but we don't actually run the builds so the version numbers really don't matter.

2. Builds for testing something in production (Testflight/Internal test track). We use these semi-regular for technical things like google login, push notifications where proper production configuration matters. For these **build numbers matter a lot** since **they have to be unique** to not conflict with other builds (unless I'm mistaken and just having different version numbers is enough? I think on iOS it is, but not on Android, right?).

Unless I misunderstand how build numbers have to be unique on Android, we MUST use SEPARATE tags with unique version/revision numbers to not conflict with other builds.

If that's so, then we can't just pull all tags, but must trigger such builds with temporary tags we'll delete again later. Overall that's not a terrible solution since pushing a tag to the right commit is pretty simple and doesn't require interacting with Bitrise manually at all.

**Comment by pdrj** [comment]
Yeah @amulware you're right about Android. It's even more complicated than that:
> You cannot upload an APK to the Play Store with a versionCode you have already used for a previous version.

Also, people will be unable to install the test version (without first uninstalling) if its `versionCode` is lower than they currently have on device.

So something like creating an adhoc tag based on the last 'real' one and then deleting it, might not work.

**Comment by amulware** [comment]
Generally, if we install versions manually, there should be no problem uninstalling it to get back into the regular release cycle.

**Comment by pdrj** [comment]
I'm doing actual tests with uploads to the stores (using my apps). Play Store is pretty permissive, we can upload a lower version code as long as it's unique. Hence, something like a formatted timestamp for the code would work fine for the test builds.

I'm testing AppStore now, but it's taking a lot longer of course ;).

**Comment by pdrj** [comment]
For iOS, the pair `(CFBundleShortVersionString, CFBundleVersion)` has to be unique. You can reuse the same `CFBundleVersion` in different `CFBundleShortVersionString`s. You can also upload a lower `CFBundleVersion` for a given `CFBundleShortVersionString` (as long as that bundle version has not been used before).

Once a given app version is approved (identified by `CFBundleShortVersionString`), you can no longer upload new builds to the approved `CFBundleShortVersionString`. That means that we can't automatically produce test builds, unless we bump the `CFBundleShortVersionString` by making a commit.

Now, if we want to automatically (ie. without creating artificial tags) submit test builds when there's an open release going on in AppStore for a given `CFBundleShortVersionString`, we can do that in a similar fashion to Android - just using a timestamp. This will not clash with our regular tag-triggered builds, as per all the info above.

**Comment by amulware** [comment]
Ok.
