### ISSUE TITLE
Track of how many users sign up or log in

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#616]
We want to know of how many users who download the app sign up or log in (or don't do anything at all).

**Comment by amulware** [comment]
I don't know if there is a way to track 'not doing anything', but we can certainly add a signup and a login event (ideally also distinguish password vs google auth, and whether the password manager was used).

If there is some specific way in which you want us to track 'not doing anything', let us know @pe0ny but otherwise I suggest we extract that data by checking our analytics for users who open the app but don't have signup/login events.

**Comment by pe0ny** [comment]
I think that makes sense to use the number of users who open the app but don't sign up or log in. 👍

**Comment by simonrozsival** [comment]
Should we track also other related events - resetting the password, logging in after the API token is reset?

**Comment by amulware** [comment]
Sure, that would be cool to have. I really think we need a different solution than having one method for each of these events though if we go this granular (especially once we might start tracking platform-specific events).

**Comment by simonrozsival** [comment]
What does it exactly mean "password manager was used"? That the button was tapped? Or that it was tapped and PW manager was available? Or that there was a record in the password manager that was used for login?

**Comment by amulware** [comment]
Let's record all three, but use a property to tell them apart?

**Comment by simonrozsival** [comment]
Then there is also an option that the button was tapped but the service was not available. I can add events for all of them.

**Comment by amulware** [comment]
Please do so if it doesn't make the code too complicated. Otherwise, I'm fine if we track just how often there actually was a record and people tried logging in with that.
