### ISSUE TITLE
It is possible to stop unsynced running TE before initial syncing finishes

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6220]
User report:

> The app has come a long way, but there are still things that drive me crazy. For example, if I had a timer running, that I checked on my phone at, say 12 pm, then I stopped that an hour later on my PC. Then I start a new one at 2 pm and want to end that on my phone at 4 pm so I open the app, see a running timer, immediately click the stop icon and then realize it was the timer from this morning because the app hadn’t synced that I just stopped and now I have a time period that goes from morning to 4 pm and no way to see the actual time I stopped that one because it’s overwritten. This is so aggregating. I know I should wait till the app syncs upon startup but the previously stopped timer should in no case be overwritten. When does this make sense? At least the app should ask. Seriously. How am I going to pay for a product that works like this? (I’m not right now)

I agree with the user. We already discussed this some time ago. Stopping a TE twice is a pain, because the first (correct) stop time is lost and you have to manually adjust the correct stop time, which you might not be sure about... Maybe the stop button should not be shown (or be disabled) before initial sync finishes.

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/17820593383)

**Comment by amulware** [comment]
I agree this is a problem, but blocking the UI is not the correct solution. Syncing can take a long time, even under good conditions, and blocking the UI under those circumstances because there MIGHT be an update to the running time entry is not acceptable, it'll inconvenience a lot more users than it helps.

Syncing should realise that the TE was stopped twice and use the first stop time.
