### ISSUE TITLE
Review which views we present as root views and which as modal views

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6292]
This is a follow-up of PR #6259 

We might want to consider if the `OutdatedAppViewController` or the `TokenResetViewController` should be presented by `RootPresenter` or the `ModalDialogPresenter`.

Check the PR and this internal discussion for more the details: https://toggl.slack.com/archives/C02APMYTM/p1571750983374100

**Comment by Odrakir** [comment]
Those views are designed to show up over the app's interface. Which I think makes a lot of sense. The problem is, with the code we have right now, those checks are done before the root view is presented, so there's no app interface to show these views over. 

In my opinion we should delay those checks and the presentation of these views until the root view is there.

**Comment by amulware** [comment]
@Odrakir I'll leave this issue to you to include when we work on your general navigation improvement proposal.

**Comment by heytherewill** [comment]
We definitely don't wanna mess with the presenter right now
