### ISSUE TITLE
Start + Stop siri shortcuts don't work

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6309]
When I try to run the `Start timer` or `Stop timer` Siri shortcuts, I get an unknown error:

![image](https://user-images.githubusercontent.com/374616/67380312-67f65680-f58a-11e9-98f1-f21a091802c1.png)

I observed this bug when I deployed the app to my phone in debug mode and also in the TestFlight 2.5 #2 app.

So far I haven't been able to figure out where the bug originates.

**Comment by Odrakir** [comment]
TestFlight version works for me fine on device. Current development 2.5 version doesn't work on Simulator (not sure if it's because of the simulator or prov profiles or what).

Can you try deleting every version of the Toggl app, removing every Toggl shortcut and try installing the TestFlight version again?

**Comment by simonrozsival** [comment]
I'll try that.

**Comment by simonrozsival** [comment]
It works in the Testflight version after I re-installed the app and the shortcuts. I suggest closing this now and waiting for a Testflight build and re-open it if the bug is in the new build.
