### ISSUE TITLE
Make the calendar settings permission's flow more similar in both platforms

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6361]
Please refer to https://toggl.slack.com/archives/C02APMYTM/p1572254416278900 for more details.

The idea is to replace the "Link calendars" switch in the calendar settings on droid to behave similar to iOS.

- Change the text to something similar to iOS.
- The initial permissions' flow should be the same, the user can give permissions directly from the app until the permissions are granted or permanently denied.
- After the permissions were given/permanently denied, a message stating the state of the permissions should appear as a helper text. And clicking (somewhere) should lead to the system settings so that the user can grant/revoke permissions manually.

**Comment by maritoggl** [comment]
This Slack reference is not great - the discussion there is way too long and unorganized for anyone that wasn't part of it at the time to grasp. Also, I believe the goal is not to make the flows similar, but to fix the issues we currently have with one or the other flow - let's make the issue to reflect that :) This particular issue, if I understand correctly, is about Android. What do we want to achieve there, specifically?

**Comment by daividssilverio** [comment]
Alright, let me try to clarify the situation and what I meant when creating this issue:
The android flow is as follows:
![calendar (1)](https://user-images.githubusercontent.com/2173493/68128634-77609280-feee-11e9-932e-3cd6520f93a5.png)

The iOS flow is as follows:
![calendar (3)](https://user-images.githubusercontent.com/2173493/68128697-9828e800-feee-11e9-986b-f50239603f45.png)

The problem I see on Android is that "Step 4" from the first image is misleading/confusing.
We are not actually revoking the given calendar permissions when that switch is turned off. We are just hiding the calendar integration.

I'd like to suggest that the Android version should follow the iOS behaviour.
The idea is to replace the switch on android with something else just informing that the calendar permissions situation (granted/not granted).

After permissions are granted, we just show the user calendars when the calendar settings screen is opened. We provide a shortcut to the system settings so that the user can manually revoke permissions if that's his/hers intention, like iOS.

**Comment by maritoggl** [comment]
Thanks for that, Daivid, this is great! 
For that, we don't really need any new designs though, do we? We just need to change the copy for the current "Link calendars" section and change its behavior? Or am I missing anything?
I propose using the same copy we have in iOS.
> **Allow Calendar access**
> Toggl needs access to your calendar in order to display events. Events are visible to you only and won't appear in reports.
That way we can reuse translations as well!

**Comment by daividssilverio** [comment]
> For that, we don't really need any new designs though, do we? We just need to change the copy for the current "Link calendars" section and change its behavior? Or am I missing anything?
I propose using the same copy we have in iOS.

Well, designs would be nice to replace that switch with something more meaningful (relating to navigation, like iOS). We could keep it and make it immutable (just making it navigate to the settings screen), but that's not ideal imho.
To get things moving we can go with that and change it later if we think it's needed. Or maybe just add an arrow `>` next to the switch like iOS as well.

**Comment by daividssilverio** [comment]
Do you agree @maritoggl ? If you say it's ok, I'll prioritize this issue without the designs anyway and whomever does it can take on a best effort approach to make it look nice.

**Comment by AlicjaSuska** [comment]
Thank you for raising this issue @daividssilverio I would say that our approach to giving/revoking rights could be simplified in both cases:

- when user links calendar to Toggl - display popup asking for permission. Rights given in the settings [no changes here]

- when user wants to unlink the calendar - in settings on both platforms we can display 'link calendars' - when user turns it off we keep the current Android behaviour. It makes more sense for us to not show user how to revoke rights for two reasons:
1. we keep user in the app and do not confuse them with changing the flow
2. when they want to link calendar back - we already have the rights

- when user went to settings and manually revoked rights and wants to link calendar back - then we transfer them to settings as they have to manually give use access rights to the calendar. In this case after switching the toggle on, we move them to phone settings. This is how apps do it. I would say we don't need any arrows as indication of navigating. In general, only advanced users revoke rights manually so they shouldn't be surprised that we take them to settings.

@maritoggl @daividssilverio What do you think about this approach?

**Comment by daividssilverio** [comment]
What you say makes sense. I asked @heytherewill and he thinks the same.
If that's the case, we don't have to do anything for android and just have to update iOS, right?
If that's the case, I'll remove the `android` tag and coordinate with the 2.7 or 2.8 release manager to get this done on iOS.

**Comment by daividssilverio** [comment]
What you say makes sense. I asked @heytherewill and he thinks the same.
If that's the case, we don't have to do anything for android and just have to update iOS, right?
If that's the case, I'll remove the `android` tag and coordinate with the 2.7 or 2.8 release manager to get this done on iOS.

**Comment by AlicjaSuska** [comment]
@amulware please, let me know if you need to follow up on this flow or any design help here. Thank you!

**Comment by amulware** [comment]
I don't have an overview here, but please follow up with Alicja if necessary, developers. :)

**Comment by maritoggl** [comment]
After thinking about it, I propose a slight change in the flow. Instead of asking the user for calendar permission when they accidentally discover the calendar settings, let's ask the calendar permission right when the user first opens the calendar feature.

So..
-  when user opens the calendar feature the first time, ask for permission to access calendar
- - if permission granted, display the settings view where they can select the calendars to be linked
- - if permission denied, display the no worries, you can do that later popup that we already have
from there onwards we proceed with the flow @AlicjaSuska proposed
- when user wants to unlink the calendar - in settings on both platforms we can display 'link calendars' - when user turns it off we keep the current Android behaviour. It makes more sense for us to not show user how to revoke rights for two reasons:
1. we keep user in the app and do not confuse them with changing the flow
2. when they want to link calendar back - we already have the rights
- when user went to settings and manually revoked rights and wants to link calendar back - then we transfer them to settings as they have to manually give use access rights to the calendar. In this case after switching the toggle on, we move them to phone settings. 

@daividssilverio @AlicjaSuska do you see any downsides to such change in our approach? My reasoning is mainly that currently the calendar settings are difficult to discover, which may result in users not linking any calendars at all.

**Comment by maritoggl** [comment]
Also, note that currently in iOS the "No worries, you can enable permissions later" popup is displayed to users every time they go to calendar settings in the app while they have denied the permissions. This is invalid behavior. The popup should be displayed only the first time the user denies the permission to access the calendar, it should not pop up repeatedly.

**Comment by arturs105** [comment]
> * when user opens the calendar feature the first time, ask for permission to access calendar
>   * if they choose to grant the permission, they are taken to app settings where they can confirm the permission. Then they can go back to in-app calendar settings and are displayed the list of calendars they can link.

The new flow is a bit unclear to me. By "they are taken to app settings", do you mean system settings (`Settings.app -> Toggl`) or the in-app settings? Because it is not necessary to take them to the system settings when the permission is asked for the first time.

I propose we could do something like this:
1. User opens the calendar tab for the first time
2. We ask them "Do you want to see your calendar events here?"
2.1. If yes: we take them to the in-app calendar settings, where the permission is immediately requested and after granting it they can then enable whichever calendars they want. If they then choose to deny the permission, they remain in the settings and can then tap on "link calendars" switch to be taken to system settings.
2.1. If no: do nothing.

**Comment by maritoggl** [comment]
I meant system settings since I thought that was required. Thanks for bringing it up. 

I wouldn't introduce a separate "Do you want to see your calendar events here?" step. The permission request popup itself already includes some text that indicates what the permission is required for. So we can have the flow as:

- when the user opens the calendar feature the first time, ask for permission to access calendar
  - if they choose to grant permission, they are directed to in-app calendar settings and are displayed the list of calendars they can link
  - if permission denied, display the no worries, you can do that later popup that we already have

**Comment by AlicjaSuska** [comment]
It is a common technique to first ask in our custom popup and then display system popup for following reasons:
1. System popup only
- if user says 'don't allow' in the system popup, they will have to go to system settings to grand Toggl access to their calendar later. Very complicated flow
2. Two popups - ours, then system
- if user clicks 'no', we still can come back to it and turning access on will be easy (in the system poup)
- if user says yes, they don't mind clicking twice to agree

@maritoggl please, let me know if it sounds reasonable. @arturs105 please, cofirm if my info about impact of clicking 'don't allow' is correct. Thank you!

**Comment by maritoggl** [comment]
Valid points. It does sound reasonable. With that said, is it really that complicated to turn on permission from system settings if user can access the system settings directly from our app settings? I agree it would be a mess if the user would need to find the system permissions independently without being able to reach those via the in-app settings directly. But we sort of can come back to requesting permission regardless of how the initial permission has been asked, no?

**Comment by arturs105** [comment]
What @AlicjaSuska  says is correct - if the user denies the permission in the system dialog, we can't show that dialog again, we have to take the user to the system settings for Toggl.
@maritoggl is also correct - it is not that difficult to grant permission from the system settings if we take the user there (which we can do).

**Comment by maritoggl** [comment]
I would rather take the approach where we provide a smooth experience for the positive scenarios (user grants permission) and a logical, albeit a tiny bit more complex experience for users that decide to change their mind at a later step. The decision would probably be different in case it would be crucial for us to get the permission, but in this case, it is not - the calendar feature is still functional and potentially valuable to users even without us having permission to access their calendars.
