### ISSUE TITLE
The "tap to edit" onboarding tooltip misbehaves when the initial sync fails during login

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6567]
After logging out and logging in again with my account the sync initially failed causing the spider to appear.

After pulling to refresh, the time entries loaded alright, but the "Tap to edit" onboarding tooltip appeared in a very weird position, covering the running time entry card in the main log.

How to replicate:
- Log in into your account that has a bunch of time entries (it should cover a least one screen)
- Log out
- Log in again
- Pray for the initial sync to fail (or set it up in debug mode so that it always happens)
- Checkout the spidey bro
- Pull to refresh
- Wait a bit and the popup will appear in the bottom of the screen

SS for reference:
![broken-onboarding](https://user-images.githubusercontent.com/2173493/68813668-e788ba00-064c-11ea-863f-5686cc7dfa0c.jpeg)

**Comment by semanticer** [comment]
@daividssilverio Not 100% sure I got the same issue as you did: 
![device-2020-01-06-162353](https://user-images.githubusercontent.com/535613/71831236-c1a9ef80-30a8-11ea-9e84-d8e984fc106c.png)
![device-2020-01-06-162849](https://user-images.githubusercontent.com/535613/71831248-c66ea380-30a8-11ea-8ac6-4892d5e57c04.png)

The problem seems to be in MainFragment.findOldestTimeEntryView() where we are always trying to get the oldest visible view and it looks like view under running TE (first screenshot) is considered visible in the context of RecyclerView and scrolled TE row (second screenshot) is still considered partially visible. I'm not sure what should be the correct behaviour. I guess we want to get the oldest view that's completely visible and not under running TE, or maybe we don't want to display the hint when TE is running at all?

**Comment by daividssilverio** [comment]
Hey @semanticer ... Our onboarding is currently a bit messy... The original ideas/issues came from [here](https://github.com/toggl/mobileapp/issues/1519) and were modified along the way to become more generic and not depend on the whole "new user flow".

By the way, IMHO, I don't think we should show the "tap to edit" tooltip when the time entry is running for simplicity sake.

I think we should take another look at the whole onboarding tbh (maybe we are already planning this and I'm not aware about it). @maritoggl @amulware ➿

**Comment by daividssilverio** [comment]
Btw, the problem described in this issue is more about the onboarding step appearing when it shouldn't. 
The conditions are:
```
signedUpUsingTheApp
                && !navigatedAwayFromMainViewAfterTappingStopButton
                && !hasTimeEntryBeenContinued
                && !hasTappedTimeEntry
                && !isEmpty
```

It seems like `signedUpUsingTheApp` was mistakenly initialized with `true` even though I was logging in and not signing up using the app.

**Comment by daividssilverio** [comment]
After #6930 #6598, I cannot replicate this issue anymore. @semanticer feel free to close it if you can't replicate it as well.

**Comment by semanticer** [comment]
Same here, closing this
