### ISSUE TITLE
Fix integration tests timing out

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#658]
They have been timing out on bitrise for over a week. No good. Fix pls.

**Comment by simonrozsival** [comment]
I was able to track that this has something to do with Tasks - GetAllSince tests (when I run everything but the Tasks tests, everything goes well. This also makes sense because Tasks were the last integration tests which were added.), but I cannot identify a single test which would cause the tests to freeze - if I run only a few tests, then the process finishes (even though some tests fail for weird reasons, that might be a clue as well). If I then enable more tests, which I tested run without any issues, it freezes.

I am now waiting for a reply from the Bitrise support team.
