### ISSUE TITLE
The sync manager should expose failures of the sync process

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#661]
Right now there is no way of showing the user that the sync failed (for any reason). Every sync process ends with showing the user a green tick and a "Synced" message even if there was an error.

There are several distinct scenarios of failure and they should be presented in different ways:
- There is no Internet connection
- The client or the API is outdated (HTTP 410, 418)
- There was some other error

When the sync is triggered automatically (automatic push after user changed some time entry), we shouldn't show any errors so we don't confuse the user.

The reason I created this issue was me thinking about the way to implement #579 - namely whether to even initiate the push sync when there is no Internet connection. We discussed this with @willsb and we figured out that it would be best to expose the errors with the same observable we use today, but add more sync states besides `Pull`, `Push`, `Sleep` - something like `NoInternetConnection`, `ClientOutdated`, `ApiOutdated`, `Error`, but only when the full sync was initiated by the user.

**Comment by amulware** [comment]
Ref #751

**Comment by amulware** [comment]
I'm no longer sure if we should use the sync manager's observable. It significantly complicates the class and makes it has to handle a lot of different things, while it's really only meant to handle the thread safety and correct order of operations.

Instead, I'm leaning towards custom observables (maybe use a container with several of them for different events? unless we thing a single one is enough), injected into the states, and have the states push these events out as side effects.

Comments and other ideas are very welcome.

This may have to be solved together with #751, or separately for the issues not covered there.

In both cases, I'd like to have a design proposed here first and only fully implemented if we have a consensus.

**Comment by simonrozsival** [comment]
I agree that we should have a different observable for the UI which would be easier to consume - it could emit events like `Syncing`, `Synced`, `Offline`, `Failed`. I think that for simplicity we should treat both of these issues separately.

**Comment by simonrozsival** [comment]
So my suggestion is:

- add new observable `SyncProgressObservable` to `StateMachineOrchestrator`
- in the the `startSync` method emit `Syncing`
- in the `onStateEvent` handler look for relevant state machine events (`StateMachineError`, StateMachineDeadEnd`) and emit corresponding events (error => `Offline` or `Failed`, deadend => `Synced`)
- the observable will be accessible through the `SyncManager` in the same way the `StateObservable` is accessible currently
- UI can subscribe to this new observable instead of the `StateObservable` and have more detailed status information (now we show "Synced" even when the whole process failed)
- when the phone is in offline mode, we detect the `HttpRequestException` and I believe right now this leads to a transition into the retry loop - this exception shouldn't be caught and processed by any state, but should lead to a failure which will be reported by the `StateMachine`

What do you think about this, @amulware?

**Comment by amulware** [comment]
As you point out, your solution does not work with the current implementation of the retry loop. How can we implement that loop otherwise?

I can't see an easy solution to that right now.

And given that I'm not convinced we can stick this stuff in the orchestrator, or that we should (again, complicating it).

**Comment by simonrozsival** [comment]
I think we should go into the retry loop only if we receive a `ServerErrorException` and for other exceptions we shouldn't catch the error at state level. Can you think of an exception which would should be a cause of entering the retry loop, but is not `ServerErrorException`?

**Comment by amulware** [comment]
Whatever exception happens when the user is offline, or maybe the reception is horrible and there is a timeout or other connection error. Should we not retry in those cases? If we don't, and the user doesn't bother forcing sync, we might not sync for much longer than we should.

Also, even if this is not a problem, do we not want to show 'Failed' or whatever when we enter the retry loop? Essentially, as long as we are waiting to retry, we don't want to pretend we are syncing? Or maybe, at least if we enter the status-endpoint-retry-loop?

**Comment by simonrozsival** [comment]
I think all the cases you mention in the first paragraph should lead to `Offline` and then we shouldn't do retries, but abort the sync altogether. Because during retry user can't force-sync it and it can take a minute before it starts syncing things, and that might seem to the user as if the app does not function properly. We might then set some timeout which would init new sync (that is what client apps normally do - with some countdown or a force-sync option, even our webapp does that afaik).

Or we can implement it in such way, that force-sync either starts new Pull sync, or cancels any delays in the retry loop.

Maybe it would make sense to give up after some time of retrying (5 minutes?) and show "Failed" status to the user. But I wouldn't emit any of these states while `StateMachine` is running.

**Comment by amulware** [comment]
I see sense in injecting a timespan into the state machine, and if the retry tries to wait longer than that limit, it errors instead (should be injected because if we ever use this for non-mobile clients we can be much more generous with limits).

After failing sync, I'm also fine with the UI starting it again, whether by timeout (push only, or full? or by user input (full).

Force push cancelling the retry loop isn't a bad idea either... though I'm not sure if there might be unintended consequences.

I can't really make up my mind right now. I'm also uncertain how this interacts with our handling of the special 4xx errors.

**Comment by simonrozsival** [comment]
If our retry-loop is not infinite, but dies after some time, then we shouldn't let user cancel it. Which also makes it certain that the user wouldn't flood the server with requests by forc-syncing like crazy.

I think we should have extra transitions for special 4xx erros or not catch them at all (or rathr rethrow them), so they will be only processed in the `StateMachine` or in `StateMachineOrchestrator` - we shouldn't continue any sync when we run into these and we should inform the UI accordingly, so it navigates the user to a different view.

**Comment by amulware** [comment]
Let me try to summarize:

- add a new observable in the orchestrator (that we expose in the manager as well)
- on sync start report `syncing`
- if sync ends with dead end, we report `synced`
-  if we encounter a non-server exception abort sync and report `offline`
  - in the future we can add a ui-based retry (with a counter or whatever) for that case
  - or can we maybe tell being-offline apart from other unexpected errors (and have those lead to `failed`)?
- for server errors we enter the api retry, but if we get to the point of where it tries to start a retry-delay longer than X (injected value, what is reasonable?), we abort and report `failed`
- the 4xx responses also need to cause `failed` - I think this is as simple as throwing the exception in the state observable?

At least in the `failed` case, and maybe the `offline` case (unless we can definitely determine if being offline is the issue), we should attach the exception so that the UI can catch them.

**Comment by amulware** [comment]
An issue I see is that if the sync fails, the sync manager may try and start the next queued one, right? (because of the Pull Push separation we are doing).

**Comment by simonrozsival** [comment]
- we can mostly tell `failed` and `offline` apart - when offline we get `System.Net.Http.HttpRequestException`.
- for 4xx errors, we should report `failed` as well? You mean 401, 410, and 418, right? Or did you mean all 4xx (after marking some entity as unsyncable)?
- yes, after a pull comes a push, so even when pull fails, push will "cover" the failure with a `syncing` state, I'm not sure what would be a better solution - whether to abort sync and get rid of anything already queued, or if we would still process everything, but show `failed` afterwards..? the latter one seems weird, forget it.

**Comment by amulware** [comment]
Sorry, yes, I meant only the three special 400s. And yeah, we need a solution that stops all other sync probably.

**Comment by simonrozsival** [comment]
So the behavior would be: if sync runs into an error, it publishes `failed` and clears the queue - so we don't continue with any sync until it is requested again (user forces sync, user makes some changes and push is triggered). Is that correct?

What do you think about the specs of this feature, is this the way we will do it then? I think it should work well. I could start implementing this today, if I get a green light from you, @amulware.

**Comment by amulware** [comment]
Yes, that sounds good. I'm a bit worried about race conditions where the queue might be cleared just as the next please-sync call comes in. Maybe consider if that is a real issue we care about.

But otherwise and overall, this sounds fine, please feel free to proceed.

**Comment by simonrozsival** [comment]
I think if we clear the queue inside the `SyncManager` inside a locked block, it shouldn't cause problems. But I will keep it in mind.

**Comment by simonrozsival** [comment]
All the PRs were merged, so I close this issue manually now.
