### ISSUE TITLE
Add/Review analytics

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#7015]
Some of this will already be done, since we are taking some logic from the existing view models, but I want to have a separate issue for this because I think analytics for this specific part of the app are very important. 

I want a list of everything we are tracking in these screens (if possible confirming they are working) and maybe a list of more things we are not tracking, like UI stuff, for example.

**NOTE:** This issue is part of the `Onboarding refactor` project and it should be merged into the project branch and not into develop.

**Comment by sofokli1** [comment]
### OnboardingViewModel
#### is tracking:
- [x] `ContinueWithGoogle`
- [x] `Login` with google
- [x] `SignUp` with google
- [x] `UnknownSignUpFailure.Track(exception.GetType().FullName, exception.Message)` and `TrackAnonymized(exception)` in case of error during login with google
- [x] `UnknownSignUpFailure.Track(exception.GetType().FullName, exception.Message)` and `TrackAnonymized(exception)` in case of error during signup with google
#### is not tracking right now:
- [ ] login with apple
- [ ] signup with apple
- [ ] possible errors during signup with apple
the above should be resolved after the signup with apple is merged in develop

### SignUpViewModel
#### is tracking:
- [x] `Track(analyticsService.SignUp, AuthenticationMethod.EmailAndPassword)`
- [x] `Track(new SignupPasswordComplexityEvent(password))` in case the pass is valid. It logs info about the characters used (lowercase, uppercase, numbers, specials chars, length)
- [x] `UnknownSignUpFailure.Track(exception.GetType().FullName, exception.Message)` and `TrackAnonymized(exception)` in case we fail to signup
#### is not tracking, but open for discussion if it should track the following:
- [ ] `Incorrect email or password` responses from the server after attempting signup
- [ ] `email is already used` responses from the server after attempting signup
- [ ] before signup request `email validation errors` we do our own validation of the email but we do not log how many times this happens
- [ ] before signup request ` email not provided errors` similar to the above we check if an email is provided at all but we do not log this
- [ ] before signup request ` password validation errors` we do our own validation of the password but we do not log how many times this happens
- [ ] before signup request ` password not provided errors` similar to the above we check if a password is provided at all but we do not log this
- [ ] attempts of signup without a country id are not logged
- [ ] passwordVisibility toggl use is not logged (not sure this is interesting information)

### EmailLoginViewModel
#### is tracking:
- [ ] `analyticsService.Login, AuthenticationMethod.EmailAndPassword`
- [ ] `UnknownLoginFailure.Track(exception.GetType().FullName, exception.Message)` and `TrackAnonymized(exception)` when failed to login

#### is not tracking, but open for discussion if it should track the following:
- [ ] `IncorrectEmailOrPassword` responses from the server
- [ ] before login request `email validation errors` we do our own validation of the email but we do not log how many times this happens
- [ ] before login request ` email not provided errors` similar to the above we check if an email is provided at all but we do not log this
- [ ] before login request ` password not provided errors` we check if a password is provided at all but we do not log this

### TermsAndCountryViewModel
#### is tracking:
- [x] nothing
#### is not tracking, but open for discussion if it should track the following:
- [ ] log when county is not selected error
- [ ] log selected county
- [ ] log when Privacy Policy is opened
- [ ] log when Terms of Service is opened
- [ ] log the taps on the agree button
- [ ] log the taps on the close button

@Odrakir and @maritoggl what do you think we should track?
Will keep the checklist here but will remove the ones we are not going implement at all.

**Comment by maritoggl** [comment]
Thanks for the list. Everything you've listed seems to make sense and also seems interesting, left a few unchecked mainly because of additional questions, not necessarily because I wouldn't track them. The only thing I'm not very interested in is the password visibility toggle. 

OnboardingViewModel
Checked:
-  login with apple
-  signup with apple
-  possible errors during signup with apple

SignUpViewModel
Checked:
- email is already used responses from the server after attempting signup
- before signup request email validation errors we do our own validation of the email but we do not log how many times this happens
- before signup request password validation errors we do our own validation of the password but we do not log how many times this happens

Did not check - see questions/comments: 
- Incorrect email or password responses from the server after attempting signup **???** shouldn't there be two events for that? one for incorrect email (user with such email does not exist, essentially) and another for incorrect password (user exists, password is wrong)?
- before signup request email not provided errors similar to the above we check if an email is provided at all but we do not log this **???** do we need a separate event for that or could that be together with the generic validation error? Assuming we specify some sort of an error "type"?
- before signup request password not provided errors similar to the above we check if a password is provided at all but we do not log this **???** same question as for e-mail - do we need a separate event for that or could that be together with the generic validation error? 

EmailLoginViewModel
Checked:
- before login request email validation errors we do our own validation of the email but we do not log how many times this happens
- before login request password not provided errors we check if a password is provided at all but we do not log this

Did not check - see questions/comments: 
- IncorrectEmailOrPassword responses from the server **???** same question as for signup - shouldn't there be two events?
- before login request email not provided errors similar to the above we check if an email is provided at all but we do not log this **???** same question as for signup - does this need to be separate from validation error?

TermsAndCountryViewModel
Checked all, since I figure these would help with tracking how seamless the signup flow is and whether there are significant blockers at any step that require improvements in the UX.

**Comment by sofokli1** [comment]
@maritoggl 

signup
> - Incorrect email or password responses from the server after attempting signup ??? shouldn't there be two events for that? one for incorrect email (user with such email does not exist, essentially) and another for incorrect password (user exists, password is wrong)?

From the code that I see we get one exception for both. IMO it makes sense from the security standpoint because if we just say wrong password we are leaking information about the used email of having or not an account at toggl. (not sure what is the situation regarding GDPR and this cases)

> - before signup request email not provided errors similar to the above we check if an email is provided at all but we do not log this ??? do we need a separate event for that or could that be together with the generic validation error? Assuming we specify some sort of an error "type"?

This case does not fire an exception and it blocks the signup request that is going to the server from happening. Thats why I thought of tracking this separately. We could have one analytic event for `invalid signup credentials` and a parameter for the origin, like email, password, email+password (at the same time)

> - before signup request password not provided errors similar to the above we check if a password is provided at all but we do not log this ??? same question as for e-mail - do we need a separate event for that or could that be together with the generic validation error?

same as above

login
> - IncorrectEmailOrPassword responses from the server ??? same question as for signup - shouldn't there be two events?
> - before login request email not provided errors similar to the above we check if an email is provided at all but we do not log this ??? same question as for signup - does this need to be separate from validation error?

same answer for both as signup above

**Comment by sofokli1** [comment]
@juanlaube since this will be a PR in onboarding project, I will leave the apple part of the analytics to you for the apple login branch. Is that ok?

**Comment by sofokli1** [comment]
@maritoggl 
in terms and country view
> log the taps on the close button

This was a bit tricky and is not in the PR above since it needed more time, trying and hacking to get right. Let me know if it is ok that this is missing. Or if more work should be put on this.

**Comment by maritoggl** [comment]
That's ok, shouldn't be a blocker and isn't worth hacky approaches.
