### ISSUE TITLE
verify / enforce time entry time && duration

### ISSUE THREAD

**Issue by webervin** [toggl/mobileapp#705]
please validate/ensure that:
  a) start time is not sub second precise (round/truncate it to seconds only part).
  b) stop time is not sub second precise (round/truncate it to seconds only part).
  c) duration is non-decimal number of full seconds between start and stop for stopped time 
entries. 
  d) duration field for running time entries encodes same moment of time as start field.

**Comment by amulware** [comment]
@webervin "Same date as start time" - except as negative unix timestamp, as before, correct?

**Comment by webervin** [comment]
encoding for any fields does not change. 
just ensure that duration   for running time entry describes moment of 'start' not some other moment near it.

**Comment by amulware** [comment]
Let's make sure in Foundation that time entries are only ever started/stopped/edited to full round seconds.

**Comment by simonrozsival** [comment]
- the duration field is `long`, so it does not ever have any decimal places
- stop time is calculated as `start` + `duration`
- serialization of running time entry is handled correctly
- so this boils down to verifying `a)`, which should be trivial:
    - `DateTimeOffset` is sub-second precise
    - when we serialize stat time, we trim this sub-second precision
    - whenever we receive data from the API, we replace our local information so the sub-second information is lost
    - serialization of the `DateTimeOffset` to ISO 8601 uses the same rounding as converting it to unix timestamp

We can still make changes in our code to make sure we throw away any sub-second information, but I don't think that it is necessary.

What I think might be useful is to add tests for the serialization/deserialization of `DateTimeOffset` and the conversion to the unix timestamp (more so that we're going to change the way we convert to unix timestamps in the future when we can use newer versions of .NET Framework). Other than that I don't think we need to change anything in our code.

**Comment by amulware** [comment]
We (should) use the `TimeService` to get any times for the UI if I'm not mistaken. Can we not use the same (or if needed a different) service for all creation/stopping/editing of time entries and make sure the service always reports full seconds?

**Comment by simonrozsival** [comment]
We use `TimeService`. We can change it there.
