### ISSUE TITLE
Animate time entries entrance on screen

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#7052]
The idea is to use `AnimationUtils.LoadLayoutAnimation` to create a `LayoutAnimationController` together with some animation xml files.

A slide in animation could look cool.
But! I wouldn't add the animation if adds any jank into the main log.

**Comment by semanticer** [comment]
This is really tricky to do correctly IMO. It has to feel super fast and fluid. There is a big chance some of the users will perceive this as us showing off rather than giving him his content as fast as possible so he can click on something a leave in 3s (as they do). Also, this is a very prominent place and it can feel repetitive over time to watch the same animation over and over again(we should definitely display this only for the cold start)
That being said I'm definitely not against - if done properly, it might be super cool, we just need to be very careful.

**Comment by daividssilverio** [comment]
@semanticer totally agree. I should happen only once and only for cold starts.

**Comment by semanticer** [comment]
Also, it might look cool with the possible new design here https://toggl.invisionapp.com/d/main?origin=v7#/console/19262591/402298873/preview?scrollOffset=3610
We would just slide in the cards. It would be faster and it's a pretty common behavior for cards

**Comment by heytherewill** [comment]
@daividssilverio Do you think it's still worth working on this in Xamarin or would you rather not?

**Comment by heytherewill** [comment]
Discussed internally as not worth working on
