### ISSUE TITLE
Add a temporary animated "splash screen"/transition continuation for the MainTabBar

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#7053]
The idea is to have something following the splash screen.

We could even create a transition between the `SplashScreen` and the `MainTabBar`. We could maybe animate the logo up and display the `Toggl` name bellow it.

This transition can ease up how the users feel about the load times during cold starts on Android.

Since we are currently working on improving the overall performance of the app, this could be a temporary measure or it could stay there if people enjoy it.

**Comment by daividssilverio** [comment]
Hey @maritoggl here's the details for the idea discussed on https://toggl.slack.com/archives/C02APMYTM/p1580342393146800

Let's do this?

**Comment by maritoggl** [comment]
I'm ok with what you have proposed. Let's make things smooth and improve the perceived speed of the app, but be super careful of adding any transitions/animations that seem like they're there just to be there. I also want us to avoid any personalized screens for the sake of simplicity - we don't have good enough data to do anything with usernames, various cool quotes and stuff would also be tricky since we need to consider localization etc. So let's just play with the Toggl logo and brand name for the time being.

**Comment by heytherewill** [comment]
Superseded by #7055
