### ISSUE TITLE
Create an interactor for gathering all dirty entities

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#7281]
## 🎯 What needs to be done?
We need an interactor that will fetch all the dirty entities from the database.

## 🛠 Technical remarks
Well, in my opinion, instead of duplicating all the properties for 3-way merging, I'd rather have an additional copy of an entity in the database that represents a `base` entity (for 3-way merge).

When an entity is changed locally, a copy of it is made and from then on, the copy is edited and pushed to the server. During the pull/merge, both the `copy` (local) and the `base` (local) are used in 3-way merging with the `server` version. When all of the changes are merged, the `base` one is used as a merged version and the `copy` is deleted (until the next local change).

For this I'd propose the following extension on the data model:

* Additional boolean property `IsActiveEntity` (set by default to all entities) on an entity
* A new `enum EntityMode { Original, Copy }` type
* Additional `EntityMode` property `Mode` on an entity

Marking things as such, the local edits would simply copy the entity, mark the original with `Mode = Original, IsActiveEntity = false` and the copy with `Mode = Copy, IsActiveEntity = true`. The merging process would use all of the entities, while the rest of the system would simply work only on entities with the `IsActiveEntity == true`. 

That would make the interactor of this issue very trivial. The `dirtyness` would be implied by the `Mode`. So, just fetch all the copies.

## 🖼 Express your sentiment towards the issue
![](https://media.giphy.com/media/YPU1TiJH2UD8Q/giphy-downsized.gif)

**Comment by heytherewill** [comment]
Ref #7104 
Possibly requires changing the work done in #7262

**Comment by simonrozsival** [comment]
I think this is a nice idea and it would work, although I think it would require quite a few changes in the app's codebase. I think we'll need to keep the data of the entity before it was changed, but I don't like the idea of adding more properties to the current models. I propose that we would add a new table/repository for each entity type where we would store "backups" of the original entities. I'd still use the current `SyncStatus`, because that's necessary also for the UI.

**Comment by kornelijepetak** [comment]
@simonrozsival so, let me get it straight.
On local change:
* Copy the original (before the change) to the backup table
* Allow changes on the original 
* During merge
	* use entity from normal table, entity from the backup table and the server entity to
	* merge (with conflict resolution) into the normal table, and
	* delete entity from the backup table

**Comment by simonrozsival** [comment]
@kornelijepetak Yes. That was my idea 👍

**Comment by kornelijepetak** [comment]
Well I don't mind doing it that way either. 
That was the alternative version in my mind, but it felt to me that it's easier to add two properties than a bunch of new repositories and tables, all things Realm considered.

But I think your suggestion will perform better because for the majority of the operations, it will work without any WHERE conditions constantly applied.

That being said, let's proceed with this the way you described, but we gotta think good about how to ensure transactional integrity across all db operations, so that while the merge/CR is happening, no changes can mess up the app. That's the most scary part. ;)

**Comment by simonrozsival** [comment]
Transactions won't be a problem in Realm 😄 My main concern is that we would miss some part of the code that pulls data the from the storage and shows them somewhere and users would start seeing some entities twice, because we forgot to add some `Where` or something like that. Another concern was that we would have two entities with the same ID in one table/repo. That could also force us to change code in several places across the app.

Let's leverage the fact that we can bypass the abstractions and access the global Realm instance anywhere and we don't need our repository abstractions for the new "tables".

**Comment by kornelijepetak** [comment]
Closed by #7324
