### ISSUE TITLE
Decide how the new onboarding tooltips will be shown

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#7367]
## 🎯 What needs to be done?
Since the old `IOnboardingStep` and `DismissableOnboardingStep` combination was buggy, we need to come up with a better system.

## 📝 Detailed explanation
We need to decide how to do the onboarding steps better - where will we put the logic of when the step is show. We could do go for a similar approach of having a structure that holds that and other tooltip related info, or each view model could be responsible for their own tooltips. Discuss!

## 🏆 Outcome
- [x] A new system is agreed upon
- [x] The plumbing for that system is implemented (if the decided system needs some plumbing)

**Comment by heytherewill** [comment]
For the new system I'd go with something really foolproof:

- We persist whether the tooltip's condition was met or not in our Key-Value Storage
- We create an `OnboardingCondition` class that controls whether a tooltip is visible or not
- The condition is always `!wasShownBefore && predicate`
- This is part is all handled by the shared layer; I have no idea why we have so much client code for the current implementation but it shouldn't be needed
- The tooltips in the new system should not be added dynamically. Instead, let's just add them to our views with `IsHidden=true`/`visibility=gone`. This way we don't have to care about null exceptions and all that jazz and the front-end code is limited to adding the arrow view and controlling its. The text for the arrow view should, ideally, come from the shared layer as well, since it can then be localized
