### ISSUE TITLE
Use Noda Time

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#75]
Because DateTime.

**Comment by willsb** [comment]
According to [ze docs](https://github.com/nodatime/nodatime/blob/1b0a67151379f71325017a37aa4ac08e82972caf/src/NodaTime.Web/Markdown/1.3.x/serialization.md#supported-types-and-default-representations), the default parser for the [`Instant`](http://nodatime.org/1.3.x/api/NodaTime.Instant.html) type does not accept RFC3339, but ISO-8601 instead. Since backend is returning RFC3339, we have the following options:

- Write our own parsers and stick to `Instant`.
- Use [`OffsetDateTime`](http://nodatime.org/1.3.x/api/NodaTime.OffsetDateTime.html) instead, since it can be serialized from/to RFC3339 out of the box.

We need to decide this before further work can be done.

**Comment by willsb** [comment]
Looking at [ze docs](https://realm.io/docs/xamarin/latest/#date-type) for Realm, I think we might consider using `DateTimeOffset` for practical reasons and forget NodaTime altogether, since Noda 2.0 does not support PCL anyways 🤔

**Comment by amulware** [comment]
Let's go with DateTimeOffset instead then, and hope things don't get confusing. I.e. I'm keeping the option to switch to Noda Time open for the future.
