### ISSUE TITLE
Sync manager does not revert to old one after beta flag gets turned off

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#7547]
## 🐛 Bug Report
After the sync manager is once switched to v2, and later on reverted on backoffice, the app failes to return to old sync manager.

## Context
Build/Branch: `sync-team/sync`
Phone OS: Android
Phone model: Probably all.

## Expected behavior
The app should retrieve the beta flags values at the start of the lifecycle.
On the next app start it should use that value to initialize the proper sync manager.

## To reproduce
* Log in to the app with user A.
* Turn off the app.
* Go to backoffice and turn **on** the `mobile_sync_client` for user A.
* Turn on the app. 
* Go to settings and verify that the app version still ends with `/1` (which represents a sync version, under `About`).
* Turn off the app.
* Turn on the app. 
* The app should now use sync `/2`, verify that in the settings.
* Turn off the app.
* In backoffice, turn off the `mobile_sync_client` feature flag.
* Turn on the app. The app should now be instructed to use `/1` on the next run, so
* Turn off the app
* Turn on the app
* 🐛 Instead of `/1` (desired behavior), there is still a `/2` (actual behavior).

**Comment by simonrozsival** [comment]
It works well on iOS and it's in shared code, so it should also work on Android. There was an issue with deserialization of Preferences which could have caused this problem (#7546) and it's now fixed. Can you try if this issue was already resolved, or if you're still experiencing it? I'll double check that iOS can really downgrade from V2 to V1 and post an update.

**Comment by simonrozsival** [comment]
Confirmation: downgrading works well in yesterday's AdHoc build.

**Comment by kornelijepetak** [comment]
Closed by #7561
