### ISSUE TITLE
UI: Cancel Sync on Logout

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#786]
1) Indicate syncing in Settings view even before user taps 'Sign Out'
![toggl - ios - settings loading v1 1x](https://user-images.githubusercontent.com/5064445/31984260-8e597f46-b969-11e7-85c5-c636bf4355f3.png)

2) When user taps 'Sign Out' while we're syncing, show confirmation dialog:
![toggl - ios - settings sign out confirmation 1x](https://user-images.githubusercontent.com/5064445/31984312-c64579a0-b969-11e7-9d9a-3a005113563a.png)

a) When user still decides to continue and taps 'Sign Out' again, disable 'back' button and show 'Logging you out securely…':
![toggl - ios - settings loading v3 1x](https://user-images.githubusercontent.com/5064445/31984466-5587d1b2-b96a-11e7-8c97-fdb25e1b88b7.png)

b) When user taps 'Cancel', close the dialog and go back to Settings page where we display 'Syncing' and 'Synced' when syncing is complete:
![toggl - ios - settings loading v1 1x](https://user-images.githubusercontent.com/5064445/31984729-3f24d216-b96b-11e7-8c4e-f4c4548d88d8.png) ![toggl - ios - settings synced 1x](https://user-images.githubusercontent.com/5064445/31984733-41702c5a-b96b-11e7-9802-dcf255ebf41c.png)

**Comment by simonrozsival** [comment]
I have a question about the "Synced [tick]" status message - when and how exactly should it be shown? I think this message should only be displayed for a short while after the sync process finishes (like the pull-to-refresh status message is hidden after few seconds), because it can become outdated if the user edits something and the sync doesn't start for some reason (e.g., user is offline).

**Comment by amulware** [comment]
But the user cannot edit data on this screen. I think it should always show it, just as a nice confirmation to the user that they can log out safely.

**Comment by simonrozsival** [comment]
That is true. As long as the state of the screen is not preserved when the user goes back and forth, which I believe is not, then it doesn't have to be hidden.

**Comment by simonrozsival** [comment]
Since we changed the behavior of the dialog in #835 with @amulware - the dialog shows not only if the sync is running at the moment, but also when there is some unsynced time entry in the local database - the title and the message of the dialog should be changed to reflect this. It doesn't make to show "We're syncing your data" to a user, who is offline.
