### ISSUE TITLE
'New project' view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#798]
Needed fields:
- [x] Project name (inline)
- [x] Workspace (opens WS list)
- [x] Client (opens Clients list)
- [x] ~~Template (opens Templates list)~~
- [x] Public/private switch
- [x] Color (opens Color picker popup)

Other notes:
- [x] When user taps 'Create', save and select project and direct user back to
  - [x] time entry edit view
  - [x] time entry creation view
- [x] When user taps 'X', close 'New project' view and direct user back to
  - [x] projects list view
  - [x] time entry creation view

![toggl - ios - add new project 1x](https://user-images.githubusercontent.com/5064445/32043256-e3ca8fcc-ba42-11e7-9313-b533f8fa2910.png)

**Comment by amulware** [comment]
I suggest we implement this without any of the child screens so that those can be implemented in parallel and one by one for easier review.

**Comment by willsb** [comment]
What's the default color for projects?

**Comment by pe0ny** [comment]
As far as I know there isn't default color. Webapp assigns different color every time and perhaps we can do the same - randomly pick one color from the list?

**Comment by amulware** [comment]
I think picking a random colour from the pre-set ones is a decent solution.

But question: Do we want to allow the user to set the 'default billable' flag? If so, workspaces have a 'projects default billable flag default' that should probably be respected when selecting a workspace (and as default from the default workspace)?

**Comment by amulware** [comment]
Also: How do we prevent duplicate project names?

**Comment by pe0ny** [comment]
Let's not add billable flag atm because then it makes sense to let user set billable rate as well. But yes, when it's set in ws settings, we should take this into account.

**Comment by amulware** [comment]
So we will use the default settings from the workspace and just take that value 'secretely' behind the scenes?

**Comment by amulware** [comment]
Note that there are several fields that have to be set as well, even though they are not exposed in the UI:

Since they are not shown in the UI, they can probably just be computed when the project is finally created.

Note that these properties also only should be set if the workspace has the Pro feature enabled.

- `Billable` if there is a template, take its value for this field, otherwise, take the workspace's `ProjectsBillableByDefault `
- `AutoEstimates` is taken from template - otherwise null

@pe0ny please check if these are the only fields that have to be set next to the list in the original comment.


Also note that templates can only be selected when the Pro feature is enabled. @pe0ny What does the UI show for free workspaces - is the templates field hidden or disabled?

**Comment by amulware** [comment]
We are skipping on templates for now, so the above is hardly relevant, except that we do need to get the billable flag from the workspace.
